FROM docker.io/sonarsource/sonar-scanner-cli:12.1.0.3233_8.0.1@sha256:23ca0f137965d9dff2198074043fd48d386280bc5d0ccac8c8349cea4cf096a9

USER root
RUN dnf install -y gcc \
    && dnf clean all \
    && rm -rf /var/cache/dnf
USER scanner-cli
