//! Misc .NET API contracts: culture, locking, tests, exceptions, dispose.

mod array_arguments_for_params_calls;
mod assembly_versions;
mod collection_property_setters;
mod culture_less_comparisons;
mod culture_less_conversions;
mod culture_less_searches;
mod datetime_key_members;
mod debugger_display_references;
mod dispose_needs_interface;
mod dispose_pattern;
mod double_reported_catches;
mod explicit_rethrows;
mod foreach_iteration_casts;
mod general_exception_catches;
mod hardcoded_connection_passwords;
mod ignored_generic_exceptions;
mod indexer_parameter_types;
mod literal_assertions;
mod locks_on_locals;
mod locks_on_mutable_fields;
mod lowercase_normalization;
mod mergeable_try_statements;
mod null_reference_catches;
mod outdated_base_types;
mod overlapping_optional_overloads;
mod public_list_signatures;
mod pure_debug_assertions;
mod readonly_primitive_fields;
mod redundant_modifiers;
mod reserved_exception_throws;
mod rethrow_only_catches;
mod reversed_assertion_arguments;
mod strings_matching_parameters;
mod support;
mod task_returns_null;
mod test_classes_contain_tests;
mod test_method_signatures;
mod tests_include_assertions;
mod throws_in_finally;
mod transposed_operators;
mod unchecked_sums;
mod unconstrained_assertions;
mod utility_class_constructors;
mod weak_identity_locks;

pub(crate) use array_arguments_for_params_calls::check as check_array_arguments_for_params_calls;
pub(crate) use assembly_versions::check as check_assembly_versions;
pub(crate) use collection_property_setters::check as check_collection_property_setters;
pub(crate) use culture_less_comparisons::check as check_culture_less_comparisons;
pub(crate) use culture_less_conversions::check as check_culture_less_conversions;
pub(crate) use culture_less_searches::check as check_culture_less_searches;
pub(crate) use datetime_key_members::check as check_datetime_key_members;
pub(crate) use debugger_display_references::check as check_debugger_display_references;
pub(crate) use dispose_needs_interface::check as check_dispose_needs_interface;
pub(crate) use dispose_pattern::check as check_dispose_pattern;
pub(crate) use double_reported_catches::check as check_double_reported_catches;
pub(crate) use explicit_rethrows::check as check_explicit_rethrows;
pub(crate) use foreach_iteration_casts::check as check_foreach_iteration_casts;
pub(crate) use general_exception_catches::check as check_general_exception_catches;
pub(crate) use hardcoded_connection_passwords::check as check_hardcoded_connection_passwords;
pub(crate) use ignored_generic_exceptions::check as check_ignored_generic_exceptions;
pub(crate) use indexer_parameter_types::check as check_indexer_parameter_types;
pub(crate) use literal_assertions::check as check_literal_assertions;
pub(crate) use locks_on_locals::check as check_locks_on_locals;
pub(crate) use locks_on_mutable_fields::check as check_locks_on_mutable_fields;
pub(crate) use lowercase_normalization::check as check_lowercase_normalization;
pub(crate) use mergeable_try_statements::check as check_mergeable_try_statements;
pub(crate) use null_reference_catches::check as check_null_reference_catches;
pub(crate) use outdated_base_types::check as check_outdated_base_types;
pub(crate) use overlapping_optional_overloads::check as check_overlapping_optional_overloads;
pub(crate) use public_list_signatures::check as check_public_list_signatures;
pub(crate) use pure_debug_assertions::check as check_pure_debug_assertions;
pub(crate) use readonly_primitive_fields::check as check_readonly_primitive_fields;
pub(crate) use redundant_modifiers::check as check_redundant_modifiers;
pub(crate) use reserved_exception_throws::check as check_reserved_exception_throws;
pub(crate) use rethrow_only_catches::check as check_rethrow_only_catches;
pub(crate) use reversed_assertion_arguments::check as check_reversed_assertion_arguments;
pub(crate) use strings_matching_parameters::check as check_strings_matching_parameters;
pub(crate) use support::comment_tag_issues;
pub(crate) use task_returns_null::check as check_task_returns_null;
pub(crate) use test_classes_contain_tests::check as check_test_classes_contain_tests;
pub(crate) use test_method_signatures::check as check_test_method_signatures;
pub(crate) use tests_include_assertions::check as check_tests_include_assertions;
pub(crate) use throws_in_finally::check as check_throws_in_finally;
pub(crate) use transposed_operators::check as check_transposed_operators;
pub(crate) use unchecked_sums::check as check_unchecked_sums;
pub(crate) use unconstrained_assertions::check as check_unconstrained_assertions;
pub(crate) use utility_class_constructors::check as check_utility_class_constructors;
pub(crate) use weak_identity_locks::check as check_weak_identity_locks;
