//! Misc .NET API contracts: culture, locking, tests, exceptions, dispose.

pub(crate) mod array_arguments_for_params_calls;
pub(crate) mod assembly_versions;
pub(crate) mod collection_property_setters;
pub(crate) mod culture_less_comparisons;
pub(crate) mod culture_less_conversions;
pub(crate) mod culture_less_searches;
pub(crate) mod datetime_key_members;
pub(crate) mod debugger_display_references;
pub(crate) mod dispose_needs_interface;
pub(crate) mod dispose_pattern;
pub(crate) mod double_reported_catches;
pub(crate) mod explicit_rethrows;
pub(crate) mod foreach_iteration_casts;
pub(crate) mod general_exception_catches;
pub(crate) mod hardcoded_connection_passwords;
pub(crate) mod ignored_generic_exceptions;
pub(crate) mod indexer_parameter_types;
pub(crate) mod literal_assertions;
pub(crate) mod locks_on_locals;
pub(crate) mod locks_on_mutable_fields;
pub(crate) mod lowercase_normalization;
pub(crate) mod mergeable_try_statements;
pub(crate) mod null_reference_catches;
pub(crate) mod outdated_base_types;
pub(crate) mod overlapping_optional_overloads;
pub(crate) mod public_list_signatures;
pub(crate) mod pure_debug_assertions;
pub(crate) mod readonly_primitive_fields;
pub(crate) mod redundant_modifiers;
pub(crate) mod reserved_exception_throws;
pub(crate) mod rethrow_only_catches;
pub(crate) mod reversed_assertion_arguments;
pub(crate) mod strings_matching_parameters;
mod support;
pub(crate) mod task_returns_null;
pub(crate) mod test_classes_contain_tests;
pub(crate) mod test_method_signatures;
pub(crate) mod tests_include_assertions;
pub(crate) mod throws_in_finally;
pub(crate) mod transposed_operators;
pub(crate) mod unchecked_sums;
pub(crate) mod unconstrained_assertions;
pub(crate) mod utility_class_constructors;
pub(crate) mod weak_identity_locks;

pub(crate) use array_arguments_for_params_calls::check as check_array_arguments_for_params_calls;
pub(crate) use assembly_versions::check as check_assembly_versions;
pub(crate) use collection_property_setters::check as check_collection_property_setters;
pub(crate) use culture_less_comparisons::check as check_culture_less_comparisons;
pub(crate) use culture_less_conversions::check as check_culture_less_conversions;
pub(crate) use culture_less_searches::check as check_culture_less_searches;
pub(crate) use datetime_key_members::check as check_datetime_key_members;
pub(crate) use debugger_display_references::check as check_debugger_display_references;
pub(crate) use dispose_needs_interface::check as check_dispose_needs_interface;
pub(crate) use dispose_pattern::check as check_dispose_pattern;
pub(crate) use double_reported_catches::check as check_double_reported_catches;
pub(crate) use explicit_rethrows::check as check_explicit_rethrows;
pub(crate) use foreach_iteration_casts::check as check_foreach_iteration_casts;
pub(crate) use general_exception_catches::check as check_general_exception_catches;
pub(crate) use hardcoded_connection_passwords::check as check_hardcoded_connection_passwords;
pub(crate) use ignored_generic_exceptions::check as check_ignored_generic_exceptions;
pub(crate) use indexer_parameter_types::check as check_indexer_parameter_types;
pub(crate) use literal_assertions::check as check_literal_assertions;
pub(crate) use locks_on_locals::check as check_locks_on_locals;
pub(crate) use locks_on_mutable_fields::check as check_locks_on_mutable_fields;
pub(crate) use lowercase_normalization::check as check_lowercase_normalization;
pub(crate) use mergeable_try_statements::check as check_mergeable_try_statements;
pub(crate) use null_reference_catches::check as check_null_reference_catches;
pub(crate) use outdated_base_types::check as check_outdated_base_types;
pub(crate) use overlapping_optional_overloads::check as check_overlapping_optional_overloads;
pub(crate) use public_list_signatures::check as check_public_list_signatures;
pub(crate) use pure_debug_assertions::check as check_pure_debug_assertions;
pub(crate) use readonly_primitive_fields::check as check_readonly_primitive_fields;
pub(crate) use redundant_modifiers::check as check_redundant_modifiers;
pub(crate) use reserved_exception_throws::check as check_reserved_exception_throws;
pub(crate) use rethrow_only_catches::check as check_rethrow_only_catches;
pub(crate) use reversed_assertion_arguments::check as check_reversed_assertion_arguments;
pub(crate) use strings_matching_parameters::check as check_strings_matching_parameters;
pub(crate) use support::comment_tag_issues;
pub(crate) use task_returns_null::check as check_task_returns_null;
pub(crate) use test_classes_contain_tests::check as check_test_classes_contain_tests;
pub(crate) use test_method_signatures::check as check_test_method_signatures;
pub(crate) use tests_include_assertions::check as check_tests_include_assertions;
pub(crate) use throws_in_finally::check as check_throws_in_finally;
pub(crate) use transposed_operators::check as check_transposed_operators;
pub(crate) use unchecked_sums::check as check_unchecked_sums;
pub(crate) use unconstrained_assertions::check as check_unconstrained_assertions;
pub(crate) use utility_class_constructors::check as check_utility_class_constructors;
pub(crate) use weak_identity_locks::check as check_weak_identity_locks;
