[package]
name = "hoonarqube-python"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
hoonarqube-ir = { version = "0.2.4", path = "../hoonarqube-ir" }
ruff_python_ast = "0.0.10"
ruff_python_parser = "0.0.10"
ruff_source_file = "0.0.10"
ruff_text_size = "0.0.10"

[lints]
workspace = true
