//! Modifiers and declaration shape (Tier A3).

pub(crate) mod abstract_class_constructors;
pub(crate) mod arglist_usage;
pub(crate) mod async_void_methods;
pub(crate) mod attribute_classes_sealed;
pub(crate) mod break_statements;
pub(crate) mod caller_information_parameters_last;
pub(crate) mod contextual_keyword_identifiers;
pub(crate) mod default_parameter_value_needs_optional;
pub(crate) mod default_value_attribute_parameters;
pub(crate) mod enum_underlying_types;
pub(crate) mod exception_visibility;
pub(crate) mod goto_statements;
pub(crate) mod iequatable_classes_sealed;
pub(crate) mod member_visibility_above_type;
pub(crate) mod multidimensional_arrays;
pub(crate) mod mutable_public_static_fields;
pub(crate) mod native_methods_wrapped;
pub(crate) mod nested_generics_in_signatures;
pub(crate) mod non_private_fields;
pub(crate) mod only_private_constructors;
pub(crate) mod optional_attribute_on_ref_out_parameters;
pub(crate) mod optional_parameters;
pub(crate) mod out_ref_parameters;
pub(crate) mod pinvoke_visibility;
pub(crate) mod private_types_sealed;
pub(crate) mod public_constants;
pub(crate) mod public_instance_fields;
pub(crate) mod public_multidimensional_parameters;
pub(crate) mod public_pointer_signatures;
pub(crate) mod sealed_protected_members;
mod support;
pub(crate) mod type_parameter_counts;
pub(crate) mod unsafe_code;
pub(crate) mod unused_type_parameters;
pub(crate) mod unused_type_parameters_in_parameters;
pub(crate) mod virtual_field_events;
pub(crate) mod visible_static_fields;
mod walker;

pub(crate) use support::accessibility_rank;
pub(crate) use support::has_ancestor_with_kind;
pub(crate) use support::has_any_accessibility;
pub(crate) use support::has_any_attribute;
pub(crate) use support::has_attribute;
pub(crate) use support::has_modifier;
pub(crate) use support::subtree_contains_kind;
pub(crate) use support::type_declared_rank;
pub(crate) use support::type_parameter_list_of;
pub(crate) use walker::modifier_issues;
