mod arrow_body_consistency;
mod aws_cdk;
pub(crate) mod batch2d;
pub(crate) mod batch5;
mod binding;
mod brace_style;
mod call_argument_lines;
pub(crate) mod duplicate;
mod embedded_effects;
mod eval;
mod exception_handling;
pub(crate) mod expression;
mod flow_nesting;
mod func_len;
mod function_contexts;
mod function_structures;
pub(crate) mod jsx_a11y;
mod label_usage;
mod loops;
mod naming;
pub(crate) mod one_stmt;
pub(crate) mod react_jsx;
pub(crate) mod regex_family;
mod s103_line_length;
mod s104_lines_of_code;
mod s105_tab_characters;
mod s1131_trailing_whitespace;
mod s1134_s1135_task_tags;
mod s113_newline_at_eof;
mod s125_commented_out_code;
mod s1291_nosonar;
mod s139_disallowed_comment_pattern;
mod s1451_file_header;
mod self_assignments;
pub(crate) mod shared;
pub(crate) mod statement;
mod statement_sequences;
mod swapped_call_arguments;
pub(crate) mod switch_flow;
pub(crate) mod tier_b;
mod tier_c;

use crate::Issue;
use crate::context::AnalysisContext;

/// Runs every migrated rule against the context.
pub(crate) fn run_all(ctx: &AnalysisContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    issues.extend(arrow_body_consistency::run_all(ctx));
    issues.extend(aws_cdk::run_all(ctx));
    issues.extend(batch2d::run_all(ctx));
    issues.extend(batch5::run_all(ctx));
    issues.extend(binding::run_all(ctx));
    issues.extend(brace_style::run_all(ctx));
    issues.extend(call_argument_lines::run_all(ctx));
    issues.extend(duplicate::run_all(ctx));
    issues.extend(embedded_effects::run_all(ctx));
    issues.extend(eval::run_all(ctx));
    issues.extend(exception_handling::run_all(ctx));
    issues.extend(expression::run_all(ctx));
    issues.extend(flow_nesting::run_all(ctx));
    issues.extend(func_len::run_all(ctx));
    issues.extend(function_contexts::run_all(ctx));
    issues.extend(function_structures::run_all(ctx));
    issues.extend(jsx_a11y::run_all(ctx));
    issues.extend(label_usage::run_all(ctx));
    issues.extend(loops::run_all(ctx));
    issues.extend(naming::run_all(ctx));
    issues.extend(one_stmt::run_all(ctx));
    issues.extend(react_jsx::run_all(ctx));
    issues.extend(regex_family::run_all(ctx));
    issues.extend(self_assignments::run_all(ctx));
    issues.extend(statement::run_all(ctx));
    issues.extend(statement_sequences::run_all(ctx));
    issues.extend(swapped_call_arguments::run_all(ctx));
    issues.extend(switch_flow::run_all(ctx));
    issues.extend(tier_b::run_all(ctx));
    issues.extend(tier_c::run_all(ctx));
    issues.extend(s103_line_length::check(ctx));
    issues.extend(s105_tab_characters::check(ctx));
    issues.extend(s113_newline_at_eof::check(ctx));
    issues.extend(s1131_trailing_whitespace::check(ctx));
    issues.extend(s104_lines_of_code::check(ctx));
    issues.extend(s1451_file_header::check(ctx));
    issues.extend(s1134_s1135_task_tags::check(ctx));
    issues.extend(s1291_nosonar::check(ctx));
    issues.extend(s139_disallowed_comment_pattern::check(ctx));
    issues.extend(s125_commented_out_code::check(ctx));
    issues
}
