// Generated by jsts_split.py - deterministic rule dispatch.
pub(crate) mod s103_line_length;
pub(crate) mod s104_lines_of_code;
pub(crate) mod s105_tab_characters;
pub(crate) mod s1131_trailing_whitespace;
pub(crate) mod s1134_s1135_task_tags;
pub(crate) mod s113_newline_at_eof;
pub(crate) mod s125_commented_out_code;
pub(crate) mod s1291_nosonar;
pub(crate) mod s139_disallowed_comment_pattern;
pub(crate) mod s1451_file_header;
pub(crate) mod binding;
pub(crate) mod duplicate;
pub(crate) mod eval;
pub(crate) mod expression;
pub(crate) mod func_len;
pub(crate) mod naming;
pub(crate) mod one_stmt;
pub(crate) mod statement;

use crate::context::AnalysisContext;
use crate::Issue;

/// Runs every migrated rule against the context.
pub(crate) fn run_migrated(ctx: &AnalysisContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    issues.extend(binding::run_all(ctx));
    issues.extend(duplicate::run_all(ctx));
    issues.extend(eval::run_all(ctx));
    issues.extend(expression::run_all(ctx));
    issues.extend(func_len::run_all(ctx));
    issues.extend(naming::run_all(ctx));
    issues.extend(one_stmt::run_all(ctx));
    issues.extend(statement::run_all(ctx));
    issues.extend(s103_line_length::check(ctx));
    issues.extend(s105_tab_characters::check(ctx));
    issues.extend(s113_newline_at_eof::check(ctx));
    issues.extend(s1131_trailing_whitespace::check(ctx));
    issues.extend(s104_lines_of_code::check(ctx));
    issues.extend(s1451_file_header::check(ctx));
    issues.extend(s1134_s1135_task_tags::check(ctx));
    issues.extend(s1291_nosonar::check(ctx));
    issues.extend(s139_disallowed_comment_pattern::check(ctx));
    issues.extend(s125_commented_out_code::check(ctx));
    issues
}