mod arrow_body_consistency;
mod aws_cdk;
mod batch2d;
mod batch5;
mod binding;
mod brace_style;
mod call_argument_lines;
mod duplicate;
mod embedded_effects;
mod eval;
mod exception_handling;
mod expression;
mod flow_nesting;
mod func_len;
mod function_contexts;
mod function_structures;
mod jsx_a11y;
mod label_usage;
mod loops;
mod naming;
pub(crate) mod one_stmt;
pub(crate) mod quickfix;
mod react_jsx;
mod regex_family;
mod s103_line_length;
mod s104_lines_of_code;
mod s105_tab_characters;
mod s1131_trailing_whitespace;
mod s1134_s1135_task_tags;
mod s113_newline_at_eof;
mod s125_commented_out_code;
mod s1291_nosonar;
mod s139_disallowed_comment_pattern;
mod s1438_semicolon;
mod s1451_file_header;
mod s3512_template_literal;
mod s5906_prefer_specific_assertion;
mod s7719_date_clone;
mod s7721_consistent_function_scoping;
mod s7722_error_message;
mod s7723_new_for_builtins;
mod s7724_eslint_disable;
mod s7726_named_default_export;
mod s7728_no_array_for_each;
mod s7737_object_default_param;
mod s7741_typeof_undefined;
mod s7744_useless_fallback_spread;
mod s7746_useless_promise_resolve_reject;
mod s7751_prefer_array_flat;
mod s7754_prefer_array_some;
mod s7755_prefer_at;
mod s7765_prefer_includes;
mod s7766_prefer_math_min_max;
mod s7770_native_coercion_functions;
mod s7772_prefer_node_protocol;
mod s7773_prefer_number_properties;
mod s7776_prefer_set_has;
mod s7780_prefer_string_raw;
mod s7781_prefer_string_replace_all;
mod s7786_prefer_type_error;
mod self_assignments;
pub(crate) mod semantic_context;
pub(crate) mod shared;
mod statement;
mod statement_sequences;
mod swapped_call_arguments;
mod switch_flow;
mod tier_b;
mod tier_c;

use crate::Issue;
use crate::context::AnalysisContext;

/// Runs every migrated rule against the context.
pub(crate) fn run_all(ctx: &AnalysisContext) -> Vec<Issue> {
    let mut issues = Vec::new();
    issues.extend(arrow_body_consistency::run_all(ctx));
    issues.extend(aws_cdk::run_all(ctx));
    issues.extend(batch2d::run_all(ctx));
    issues.extend(batch5::run_all(ctx));
    issues.extend(binding::run_all(ctx));
    issues.extend(brace_style::run_all(ctx));
    issues.extend(call_argument_lines::run_all(ctx));
    issues.extend(duplicate::run_all(ctx));
    issues.extend(embedded_effects::run_all(ctx));
    issues.extend(eval::run_all(ctx));
    issues.extend(exception_handling::run_all(ctx));
    issues.extend(expression::run_all(ctx));
    issues.extend(flow_nesting::run_all(ctx));
    issues.extend(func_len::run_all(ctx));
    issues.extend(function_contexts::run_all(ctx));
    issues.extend(function_structures::run_all(ctx));
    issues.extend(jsx_a11y::run_all(ctx));
    issues.extend(label_usage::run_all(ctx));
    issues.extend(loops::run_all(ctx));
    issues.extend(naming::run_all(ctx));
    issues.extend(one_stmt::run_all(ctx));
    issues.extend(react_jsx::run_all(ctx));
    issues.extend(regex_family::run_all(ctx));
    issues.extend(s3512_template_literal::check(ctx));
    issues.extend(s5906_prefer_specific_assertion::check(ctx));
    issues.extend(s7721_consistent_function_scoping::check(ctx));
    issues.extend(s7728_no_array_for_each::check(ctx));
    issues.extend(s7737_object_default_param::check(ctx));
    issues.extend(s7741_typeof_undefined::check(ctx));
    issues.extend(s7744_useless_fallback_spread::check(ctx));
    issues.extend(s7746_useless_promise_resolve_reject::check(ctx));
    issues.extend(s7751_prefer_array_flat::check(ctx));
    issues.extend(s7754_prefer_array_some::check(ctx));
    issues.extend(s7755_prefer_at::check(ctx));
    issues.extend(s7765_prefer_includes::check(ctx));
    issues.extend(s7766_prefer_math_min_max::check(ctx));
    issues.extend(s7770_native_coercion_functions::check(ctx));
    issues.extend(s7772_prefer_node_protocol::check(ctx));
    issues.extend(s7773_prefer_number_properties::check(ctx));
    issues.extend(s7776_prefer_set_has::check(ctx));
    issues.extend(s7780_prefer_string_raw::check(ctx));
    issues.extend(s7781_prefer_string_replace_all::check(ctx));
    issues.extend(s7786_prefer_type_error::check(ctx));
    issues.extend(self_assignments::run_all(ctx));
    issues.extend(statement::run_all(ctx));
    issues.extend(statement_sequences::run_all(ctx));
    issues.extend(swapped_call_arguments::run_all(ctx));
    issues.extend(switch_flow::run_all(ctx));
    issues.extend(tier_b::run_all(ctx));
    issues.extend(tier_c::run_all(ctx));
    issues.extend(s103_line_length::check(ctx));
    issues.extend(s105_tab_characters::check(ctx));
    issues.extend(s113_newline_at_eof::check(ctx));
    issues.extend(s1131_trailing_whitespace::check(ctx));
    issues.extend(s104_lines_of_code::check(ctx));
    issues.extend(s1451_file_header::check(ctx));
    issues.extend(s7719_date_clone::check(ctx));
    issues.extend(s7722_error_message::check(ctx));
    issues.extend(s7723_new_for_builtins::check(ctx));
    issues.extend(s7724_eslint_disable::check(ctx));
    issues.extend(s7726_named_default_export::check(ctx));
    issues.extend(s1134_s1135_task_tags::check(ctx));
    issues.extend(s1291_nosonar::check(ctx));
    issues.extend(s139_disallowed_comment_pattern::check(ctx));
    issues.extend(s1438_semicolon::check(ctx));
    issues.extend(s125_commented_out_code::check(ctx));
    issues
}
