// Rule module s8754_unique_test_titles (generated).
//
// `javascript:S8754` + `typescript:S8754` — SonarJS S8754 "Test titles
// should be unique within a suite" (the SonarJS-owned rule, not a wrapped
// eslint rule): within one suite frame, a second test declaration
// (`it`/`specify`/`test`, plus Playwright `test`/`test.only`/`test.fail`)
// carrying the same static string or template-literal title is reported
// on the title argument with "Rename this test title to make it unique
// within the suite.". Suite frames nest with `describe`/`context`/`suite`
// (mocha-style) and Playwright `test.describe[.parallel|.serial][.only]`;
// each suite gets a fresh title map and the file root is the outermost
// frame. Only concrete constructs count: modifiers outside the concrete
// set (`only`/`concurrent`, jest `failing`, vitest `sequential`) make a
// suite ignored (`describe.skip`, `xdescribe`, `describe.each`) or a test
// non-declaring (`it.skip`, `xit`, `it.each`, `test.skip`), and neither
// registers titles nor contributes findings. A test is collected only
// when every enclosing function is a concrete suite callback — tests
// inside helper functions, ignored suites, or other tests stay silent —
// and only when it has a callback and a static first argument. Suite
// titles are not tracked (the reference registers test titles only).
// Construct identities resolve through imports/requires of the supported
// frameworks (`bun:test`, `jest`, `mocha`, `node:test`, `vitest`,
// `@playwright/test`) or unbound globals; locally bound names are not
// test constructs. Helper-function expansion (the reference's
// `checkHelperDefinedTests`) is out of scope: tests generated by local
// helpers stay silent. No auto-fix is offered.
//
// SonarJS reports the rule with scope TEST: only files the pinned server
// classifies as test files (the analyzer's filename-based `is_test_file`)
// are checked.
//
// The regression tests below are committed first at the pristine campaign
// base and must fail (RED) until the detector lands.

use crate::context::AnalysisContext;
use crate::support::{IssueSink, RuleScope, is_test_file, unparenthesized};
use hoonarqube_ir::Issue;
use oxc_ast::AstKind;
use oxc_ast::ast::{
    BindingPattern, CallExpression, Expression, IdentifierReference, ModuleExportName,
};
use oxc_semantic::Semantic;
use oxc_span::GetSpan;
use oxc_syntax::node::NodeId;
use oxc_syntax::symbol::SymbolId;
use std::collections::HashMap;

/// Test function names (mocha-style): `it`, `specify`, `test`.
const TEST_NAMES: [&str; 3] = ["it", "specify", "test"];
/// Suite function names (mocha-style): `describe`, `context`, `suite`.
const SUITE_NAMES: [&str; 3] = ["describe", "context", "suite"];
/// Mocha-style frameworks for fully-qualified-name resolution.
const MOCHA_FRAMEWORKS: [&str; 5] = ["bun:test", "jest", "mocha", "test", "vitest"];
/// Modifiers that keep a mocha construct concrete regardless of
/// framework.
const COMMON_MODIFIERS: [&str; 2] = ["only", "concurrent"];
/// Playwright `test.*` qualifiers that still produce a test.
const PLAYWRIGHT_TEST_MODIFIERS: [&str; 2] = ["only", "fail"];
/// Playwright `test.describe.*` runnable modifiers.
const PLAYWRIGHT_DESCRIBE_MODIFIERS: [&str; 2] = ["parallel", "serial"];
/// Playwright describe modifiers that disable the suite.
const PLAYWRIGHT_DISABLED_DESCRIBE: [&str; 2] = ["skip", "fixme"];

/// How a call expression participates in the test model.
#[derive(Clone, Copy, PartialEq, Eq)]
enum CallKind {
    /// Concrete suite: pushes a fresh title frame.
    Suite,
    /// Disabled/non-runnable suite: contents are ignored entirely.
    IgnoredSuite,
    /// Concrete test declaration with a callback.
    Test,
    /// Anything else.
    Other,
}

/// Entry point: `javascript:S8754` + `typescript:S8754` unique-test-title
/// check over the parsed program.
pub(crate) fn check(ctx: &AnalysisContext) -> Vec<Issue> {
    let mut sink = IssueSink {
        index: ctx.index,
        language: ctx.language,
        issues: Vec::new(),
    };
    if !is_test_file(ctx.path) {
        // Scope TEST: the pinned server classifies by filename.
        return sink.issues;
    }
    let Some(semantic) = ctx.semantic else {
        return sink.issues;
    };
    let model = TestModel::new(semantic);
    // Frame 0 is the file root; each concrete suite call gets its own
    // frame id recorded in `suite_frame_of`.
    let mut frames: Vec<std::collections::HashSet<String>> = vec![std::collections::HashSet::new()];
    let mut suite_frame_of: HashMap<NodeId, usize> = HashMap::new();
    for node in semantic.nodes().iter() {
        let AstKind::CallExpression(call) = node.kind() else {
            continue;
        };
        match model.classify(semantic, call) {
            CallKind::Suite => {
                frames.push(std::collections::HashSet::new());
                suite_frame_of.insert(node.id(), frames.len() - 1);
            }
            CallKind::Test => {
                let Some(frame_id) =
                    model.enclosing_suite_frame(semantic, node.id(), &suite_frame_of)
                else {
                    continue;
                };
                let Some(title_expression) = call
                    .arguments
                    .first()
                    .and_then(|argument| argument.as_expression())
                else {
                    continue;
                };
                let Some(title) = static_title(title_expression) else {
                    continue;
                };
                if !frames[frame_id].insert(title.to_string()) {
                    sink.emit_span(
                        RuleScope::Both,
                        "S8754",
                        "Rename this test title to make it unique within the suite.",
                        title_expression.span(),
                    );
                }
            }
            _ => {}
        }
    }
    sink.issues
}

/// Static title text: a string literal or an expression-free template
/// literal.
fn static_title<'a>(expression: &'a Expression<'a>) -> Option<&'a str> {
    match unparenthesized(expression) {
        Expression::StringLiteral(literal) => Some(literal.value.as_str()),
        Expression::TemplateLiteral(template) if template.expressions.is_empty() => template
            .quasis
            .first()
            .and_then(|quasi| quasi.value.cooked.as_ref().map(oxc_ast::ast::Str::as_str)),
        _ => None,
    }
}

/// Resolved test-construct model for one file: which frameworks are
/// active through imports.
struct TestModel {
    jest_active: bool,
    vitest_active: bool,
}

impl TestModel {
    fn new(semantic: &Semantic<'_>) -> Self {
        let mut model = Self {
            jest_active: false,
            vitest_active: false,
        };
        for node in semantic.nodes().iter() {
            if let AstKind::ImportDeclaration(import) = node.kind() {
                let source = import.source.value.as_str();
                model.jest_active |= matches!(source, "jest" | "@jest/globals");
                model.vitest_active |= source == "vitest";
            }
        }
        model
    }

    /// Classifies one call expression against the reference test model.
    fn classify(&self, semantic: &Semantic<'_>, call: &CallExpression<'_>) -> CallKind {
        if let Some(kind) = self.classify_mocha(semantic, call) {
            return kind;
        }
        Self::classify_playwright(semantic, call)
    }

    /// Mocha-style constructs: `describe`/`context`/`suite` and
    /// `it`/`specify`/`test` with concrete modifiers.
    fn classify_mocha(
        &self,
        semantic: &Semantic<'_>,
        call: &CallExpression<'_>,
    ) -> Option<CallKind> {
        let (base, modifiers) = callee_parts(&call.callee)?;
        let construct = Self::construct_name(semantic, base, &modifiers)?;
        if TEST_NAMES.contains(&construct.as_str()) {
            if !self.all_concrete(&modifiers) {
                return Some(CallKind::Other);
            }
            return Some(if has_callback(call) {
                CallKind::Test
            } else {
                CallKind::Other
            });
        }
        if SUITE_NAMES.contains(&construct.as_str()) {
            return Some(if self.all_concrete(&modifiers) {
                CallKind::Suite
            } else {
                CallKind::IgnoredSuite
            });
        }
        Some(CallKind::Other)
    }

    /// Playwright constructs: `test.describe[.parallel|.serial][.only]`
    /// suites and `test[.only|.fail]` tests.
    fn classify_playwright(semantic: &Semantic<'_>, call: &CallExpression<'_>) -> CallKind {
        let Some((base, qualifiers)) = member_chain(&call.callee) else {
            return CallKind::Other;
        };
        let Some(first) = qualifiers.first().copied() else {
            return CallKind::Other;
        };
        if first == "describe" {
            // `test.describe…` qualifies on the bare `test` identifier
            // name, matching the reference helper.
            if base != "test" {
                return CallKind::Other;
            }
            let modifiers = &qualifiers[1..];
            if modifiers
                .iter()
                .any(|modifier| PLAYWRIGHT_DISABLED_DESCRIBE.contains(modifier))
            {
                return CallKind::IgnoredSuite;
            }
            let runnable = match modifiers.last() {
                Some(&"only") => &modifiers[..modifiers.len() - 1],
                _ => modifiers,
            };
            if runnable
                .iter()
                .all(|modifier| PLAYWRIGHT_DESCRIBE_MODIFIERS.contains(modifier))
            {
                return CallKind::Suite;
            }
            return CallKind::Other;
        }
        // `test[.only|.fail]`: the base must resolve to a
        // `@playwright/test` import.
        if !qualifiers
            .iter()
            .all(|qualifier| PLAYWRIGHT_TEST_MODIFIERS.contains(qualifier))
        {
            return CallKind::Other;
        }
        if !Self::is_playwright_test_base(semantic, &call.callee) {
            return CallKind::Other;
        }
        if qualifiers.contains(&"fail") && !has_callback(call) {
            return CallKind::Other;
        }
        CallKind::Test
    }

    /// Whether the callee's base identifier binds to a
    /// `@playwright/test` `test` import.
    fn is_playwright_test_base(semantic: &Semantic<'_>, callee: &Expression<'_>) -> bool {
        let Expression::Identifier(base) = callee_root(callee) else {
            return false;
        };
        base.name == "test"
            && matches!(
                binding_fqn(semantic, base),
                Some(fqn) if fqn == "@playwright.test.test"
            )
    }

    /// Resolves the construct name for a callee base identifier:
    /// framework-bound imports/requires map through their
    /// fully-qualified name, unbound globals use their own name, and
    /// locally bound identifiers are not constructs.
    fn construct_name(
        semantic: &Semantic<'_>,
        base: &IdentifierReference<'_>,
        modifiers: &[String],
    ) -> Option<String> {
        if reference_symbol(semantic, base).is_none() {
            // Unbound global: the identifier's own name.
            return Some(base.name.to_string());
        }
        let fqn = binding_fqn(semantic, base)?;
        if fqn == "test"
            && let Some(first) = modifiers.first()
            && (TEST_NAMES.contains(&first.as_str()) || SUITE_NAMES.contains(&first.as_str()))
        {
            // `test.describe`/`test.it` on a node:test default binding:
            // the first modifier becomes the construct.
            return Some(first.clone());
        }
        let mut parts = fqn.split('.');
        let framework = parts.next()?;
        let construct = parts.next()?;
        if parts.next().is_some() || !MOCHA_FRAMEWORKS.contains(&framework) {
            return None;
        }
        Some(construct.to_string())
    }

    /// Whether every modifier keeps the construct concrete for the
    /// active frameworks.
    fn all_concrete(&self, modifiers: &[String]) -> bool {
        modifiers.iter().all(|modifier| {
            COMMON_MODIFIERS.contains(&modifier.as_str())
                || (self.jest_active && modifier == "failing")
                || (self.vitest_active && modifier == "sequential")
        })
    }

    /// The frame a test call registers in: the innermost enclosing
    /// concrete suite call, or the root frame. Returns `None` when any
    /// enclosing function is not a concrete suite callback or the test
    /// sits under an ignored suite or another test.
    fn enclosing_suite_frame(
        &self,
        semantic: &Semantic<'_>,
        call_node: NodeId,
        suite_frame_of: &HashMap<NodeId, usize>,
    ) -> Option<usize> {
        let mut frame = 0usize;
        let mut current = call_node;
        loop {
            let parent = semantic.nodes().parent_node(current);
            if parent.id() == current {
                // `Program` is its own parent: reached the root frame.
                return Some(frame);
            }
            match parent.kind() {
                AstKind::Function(_) | AstKind::ArrowFunctionExpression(_) => {
                    // Every enclosing function must be the callback of a
                    // concrete suite call; the innermost one supplies the
                    // frame.
                    let function_parent = semantic.nodes().parent_node(parent.id());
                    let AstKind::CallExpression(suite_call) = function_parent.kind() else {
                        return None;
                    };
                    if self.classify(semantic, suite_call) != CallKind::Suite {
                        return None;
                    }
                    frame = *suite_frame_of.get(&function_parent.id())?;
                }
                AstKind::CallExpression(call) => match self.classify(semantic, call) {
                    CallKind::IgnoredSuite | CallKind::Test => return None,
                    _ => {}
                },
                _ => {}
            }
            current = parent.id();
        }
    }
}

/// Whether a call has a function/arrow callback argument.
fn has_callback(call: &CallExpression<'_>) -> bool {
    call.arguments.iter().any(|argument| {
        matches!(
            argument.as_expression().map(unparenthesized),
            Some(Expression::FunctionExpression(_) | Expression::ArrowFunctionExpression(_))
        )
    })
}

/// The callee's root expression (leftmost object of a member chain).
fn callee_root<'a>(callee: &'a Expression<'a>) -> &'a Expression<'a> {
    let mut current = unparenthesized(callee);
    while let Expression::StaticMemberExpression(member) = current {
        current = unparenthesized(&member.object);
    }
    current
}

/// Splits a callee into its base identifier and modifier list, matching
/// the reference `getMochaCalleeParts`: member properties unshift as
/// modifiers, call applications unwrap to their callee, and a bare
/// `.each` factory (not applied as a call) disqualifies the construct.
fn callee_parts<'a>(
    callee: &'a Expression<'a>,
) -> Option<(&'a IdentifierReference<'a>, Vec<String>)> {
    let mut modifiers = Vec::new();
    let mut current = unparenthesized(callee);
    let mut applied_as_call = false;
    loop {
        match current {
            Expression::CallExpression(call) => {
                current = unparenthesized(&call.callee);
                applied_as_call = true;
            }
            Expression::StaticMemberExpression(member) => {
                if member.property.name == "each" && !applied_as_call {
                    return None;
                }
                modifiers.insert(0, member.property.name.to_string());
                current = unparenthesized(&member.object);
                applied_as_call = false;
            }
            Expression::Identifier(identifier) => return Some((identifier, modifiers)),
            _ => return None,
        }
    }
}

/// Collects a member chain's qualifier names and base identifier name
/// (`a.b.c` → (`a`, [`b`, `c`])); computed or optional segments yield
/// `None`.
fn member_chain<'a>(expression: &'a Expression<'a>) -> Option<(&'a str, Vec<&'a str>)> {
    let mut qualifiers = Vec::new();
    let mut current = unparenthesized(expression);
    while let Expression::StaticMemberExpression(member) = current {
        if member.optional {
            return None;
        }
        qualifiers.insert(0, member.property.name.as_str());
        current = unparenthesized(&member.object);
    }
    let Expression::Identifier(base) = current else {
        return None;
    };
    Some((base.name.as_str(), qualifiers))
}

/// Fully-qualified name of an identifier's binding, mirroring the
/// reference `getFullyQualifiedName` for the single-file subset:
/// `import {x} from 'm'` → `m.x`, `import x from 'm'`/`import * as x` →
/// `m`, `const {x} = require('m')` → `m.x`, `const x = require('m')` →
/// `m`, `const x = require('m').y` → `m.y`, and `const x = <expr>` where
/// `<expr>` resolves to another bound identifier → that binding's FQN.
/// `node:` prefixes are stripped. Anything else yields `None`.
fn binding_fqn(semantic: &Semantic<'_>, identifier: &IdentifierReference<'_>) -> Option<String> {
    let mut visited = std::collections::HashSet::new();
    binding_fqn_inner(semantic, identifier, &mut visited)
}

fn binding_fqn_inner(
    semantic: &Semantic<'_>,
    identifier: &IdentifierReference<'_>,
    visited: &mut std::collections::HashSet<SymbolId>,
) -> Option<String> {
    let symbol_id = reference_symbol(semantic, identifier)?;
    // Alias cycles (`const a = b; const b = a;`) resolve to nothing.
    if !visited.insert(symbol_id) {
        return None;
    }
    let mut declarations = semantic.scoping().symbol_declarations(symbol_id);
    let declaration = declarations.next()?;
    if declarations.next().is_some() {
        return None;
    }
    match semantic.nodes().get_node(declaration).kind() {
        AstKind::ImportSpecifier(specifier) => {
            import_specifier_fqn(semantic, declaration, specifier)
        }
        AstKind::ImportDefaultSpecifier(_) | AstKind::ImportNamespaceSpecifier(_) => {
            let module = import_source(semantic, declaration)?;
            Some(strip_node_prefix(&module).to_string())
        }
        AstKind::VariableDeclarator(declarator) => {
            declarator_fqn(semantic, declarator, symbol_id, visited)
        }
        _ => None,
    }
}

/// `import {x} from 'm'` → `m.x`; `import {x as y}` keeps `x`; a
/// `default` import specifier resolves to the bare module name.
fn import_specifier_fqn(
    semantic: &Semantic<'_>,
    declaration: NodeId,
    specifier: &oxc_ast::ast::ImportSpecifier<'_>,
) -> Option<String> {
    if specifier.import_kind.is_type() {
        return None;
    }
    let module = import_source(semantic, declaration)?;
    let imported = match &specifier.imported {
        ModuleExportName::IdentifierName(name) => name.name.as_str(),
        ModuleExportName::IdentifierReference(name) => name.name.as_str(),
        ModuleExportName::StringLiteral(literal) => literal.value.as_str(),
    };
    if imported == "default" {
        return Some(strip_node_prefix(&module).to_string());
    }
    Some(format!("{}.{}", strip_node_prefix(&module), imported))
}

/// `const x = <expr>` → the initializer's FQN; `const {x} = <expr>` /
/// `const {x: y} = <expr>` joins the destructured property name onto the
/// initializer's FQN.
fn declarator_fqn(
    semantic: &Semantic<'_>,
    declarator: &oxc_ast::ast::VariableDeclarator<'_>,
    symbol_id: SymbolId,
    visited: &mut std::collections::HashSet<SymbolId>,
) -> Option<String> {
    let init = declarator.init.as_ref()?;
    if let BindingPattern::ObjectPattern(object) = &declarator.id {
        let member = object.properties.iter().find_map(|property| {
            let BindingPattern::BindingIdentifier(bound) = &property.value else {
                return None;
            };
            if bound.symbol_id.get() == Some(symbol_id) {
                property.key.name().map(|name| name.to_string())
            } else {
                None
            }
        });
        let base = expression_fqn_inner(semantic, init, visited)?;
        return Some(match member {
            Some(member) => format!("{base}.{member}"),
            None => base,
        });
    }
    expression_fqn_inner(semantic, init, visited)
}

/// Symbol a resolved identifier reference points at; `None` for
/// unresolved (global) references.
fn reference_symbol(
    semantic: &Semantic<'_>,
    identifier: &IdentifierReference<'_>,
) -> Option<SymbolId> {
    identifier
        .reference_id
        .get()
        .and_then(|reference_id| semantic.scoping().get_reference(reference_id).symbol_id())
}

/// The `ImportDeclaration` source for an import specifier node.
fn import_source(semantic: &Semantic<'_>, declaration: NodeId) -> Option<String> {
    let AstKind::ImportDeclaration(import) = semantic.nodes().parent_kind(declaration) else {
        return None;
    };
    if import.import_kind.is_type() {
        return None;
    }
    Some(import.source.value.to_string())
}

/// FQN of an expression: `require('m')` → `m`, `require('m').x.y` →
/// `m.x.y`, `require('m')(...)` → `m`, a bound identifier → its
/// binding's FQN, member/call chains reduce through their object/callee.
fn expression_fqn_inner(
    semantic: &Semantic<'_>,
    expression: &Expression<'_>,
    visited: &mut std::collections::HashSet<SymbolId>,
) -> Option<String> {
    match unparenthesized(expression) {
        Expression::CallExpression(call) => {
            if let Expression::Identifier(callee) = unparenthesized(&call.callee)
                && callee.name == "require"
                && let Some(oxc_ast::ast::Argument::StringLiteral(module)) = call.arguments.first()
            {
                return Some(strip_node_prefix(module.value.as_str()).to_string());
            }
            expression_fqn_inner(semantic, &call.callee, visited)
        }
        Expression::StaticMemberExpression(member) => {
            let base = expression_fqn_inner(semantic, &member.object, visited)?;
            Some(format!("{base}.{}", member.property.name))
        }
        Expression::Identifier(identifier) => binding_fqn_inner(semantic, identifier, visited),
        _ => None,
    }
}

/// Strips the `node:` prefix like the reference helper.
fn strip_node_prefix(module: &str) -> &str {
    module.strip_prefix("node:").unwrap_or(module)
}

#[cfg(test)]
mod tests {
    use crate::test_support::*;

    #[test]
    fn s8754_flags_pinned_exceljs_duplicate_titles() {
        // Pinned oracle: exceljs@5bed18b spec/integration/worksheet.spec.js
        // (three `it('throws an error')` duplicates across nested
        // describes), spec/unit/doc/column.spec.js:124 and
        // spec/unit/doc/worksheet.merge.spec.js:109.
        let source = "\
describe('worksheet', () => {
  describe('when frozen', () => {
    it('throws an error', () => {});
    it('throws an error', () => {});
  });
  it('sets sparse column values', () => {});
});
describe('merges', () => {
  it('does not allow overlapping merges', () => {
    expect(1).toBe(1);
  });
  it('does not allow overlapping merges', () => {});
});
";
        let findings = test_file_keys(source);
        assert_eq!(count_key(&findings, "javascript:S8754"), 2);
        let report = crate::analyze(
            PathBuf::from("spec/unit/doc/column.spec.js"),
            source,
            crate::JstsLanguage::JavaScript,
            &AnalyzerOptions::default(),
        );
        let issue = report
            .issues
            .iter()
            .find(|issue| issue.rule_key == "javascript:S8754")
            .expect("duplicate title must be reported");
        assert_eq!(
            issue.message,
            "Rename this test title to make it unique within the suite."
        );
        assert_eq!(issue.range.start.line, 4);
    }

    #[test]
    fn s8754_same_title_in_different_suites_stays_silent() {
        let source = "\
describe('a', () => {
  it('does the thing', () => {});
});
describe('b', () => {
  it('does the thing', () => {});
});
";
        assert_eq!(count_key(&test_file_keys(source), "javascript:S8754"), 0);
    }

    #[test]
    fn s8754_ignored_suites_and_tests_stay_silent() {
        // `describe.skip`/`xdescribe` contents are ignored; `it.skip`/
        // `xit`/`it.each` are not test declarations; `describe.each` is
        // not a concrete suite.
        let source = "\
describe.skip('off', () => {
  it('dup', () => {});
  it('dup', () => {});
});
xdescribe('off', () => {
  it('dup', () => {});
  it('dup', () => {});
});
describe.each([[1], [2]])('param', () => {
  it('dup', () => {});
  it('dup', () => {});
});
describe('on', () => {
  it.skip('dup', () => {});
  it.skip('dup', () => {});
  xit('dup', () => {});
  xit('dup', () => {});
});
";
        assert_eq!(count_key(&test_file_keys(source), "javascript:S8754"), 0);
    }

    #[test]
    fn s8754_nested_helpers_and_tests_in_tests_stay_silent() {
        // Tests inside non-suite functions or inside other tests are not
        // collected (the reference requires every enclosing function to
        // be a concrete suite callback).
        let source = "\
function helper() {
  it('dup', () => {});
  it('dup', () => {});
}
describe('suite', () => {
  it('outer', () => {
    it('dup', () => {});
    it('dup', () => {});
  });
  const make = () => {
    it('dup', () => {});
    it('dup', () => {});
  };
});
";
        assert_eq!(count_key(&test_file_keys(source), "javascript:S8754"), 0);
    }

    #[test]
    fn s8754_bound_names_and_dynamic_titles_stay_silent() {
        // Locally defined `it`/`describe` are not test constructs;
        // non-static titles are not compared.
        let source = "\
function it(name, fn) { fn(); }
function describe(name, fn) { fn(); }
describe('x', () => {
  it('dup', () => {});
  it('dup', () => {});
});
";
        assert_eq!(count_key(&test_file_keys(source), "javascript:S8754"), 0);
        let dynamic = "\
describe('x', () => {
  it(`dup ${name}`, () => {});
  it(`dup ${name}`, () => {});
  it(title, () => {});
  it(title, () => {});
});
";
        assert_eq!(count_key(&test_file_keys(dynamic), "javascript:S8754"), 0);
    }

    #[test]
    fn s8754_framework_imports_and_template_titles() {
        // Framework-bound constructs and expression-free template titles.
        let source = "\
const {describe, it} = require('mocha');
describe('suite', () => {
  it(`same title`, () => {});
  it(`same title`, () => {});
});
";
        assert_eq!(count_key(&test_file_keys(source), "javascript:S8754"), 1);
    }

    #[test]
    fn s8754_reports_in_both_languages() {
        let source = "describe('s', () => {\n  it('t', () => {});\n  it('t', () => {});\n});\n";
        assert_eq!(count_key(&test_file_keys(source), "javascript:S8754"), 1);
        let ts_report = crate::analyze(
            PathBuf::from("component.test.ts"),
            source,
            crate::JstsLanguage::TypeScript,
            &AnalyzerOptions::default(),
        );
        assert_eq!(count_key(&report_keys(&ts_report), "typescript:S8754"), 1);
    }

    #[test]
    fn s8754_stays_silent_in_main_files_like_reference_test_scope() {
        let source = "describe('s', () => {\n  it('t', () => {});\n  it('t', () => {});\n});\n";
        let main_report = crate::analyze(
            PathBuf::from("lib/doc/column.js"),
            source,
            crate::JstsLanguage::JavaScript,
            &AnalyzerOptions::default(),
        );
        assert_eq!(count_key(&report_keys(&main_report), "javascript:S8754"), 0);
    }
}
