// Generated by jsts_split.py - part of the per-rule refactor.

/// Catalog-backed parameters for the batch rules that are not surfaced
/// through [`AnalyzerOptions`] yet. Defaults are the frozen catalog values:
/// `S104` `maximum=1000`, `S138` `max=200`, `S1451`
/// `headerFormat=<empty>` / `isRegularExpression=false`, `S139`
/// `pattern="^\s*[^\s]+$"`, `S2068`
/// `passwordWords="password,pwd,passwd,passphrase"`, `S6418`
/// `randomnessSensibility=5.0`,
/// `secretWords="api[_.-]?key,auth,credential,secret,token"`, `S100`/`S101`/
/// `S117` naming `format` regular expressions, `S1192`
/// `threshold=3` / `ignoreStrings="application/json"`, `S1441`
/// `singleQuotes=true`, and `S6747` `whitelist=<empty>`.
#[derive(Debug, Clone, PartialEq)]
pub(crate) struct RuleOptions {
    pub(crate) maximum_lines_of_code: u32,
    pub(crate) maximum_function_lines: u32,
    pub(crate) header_format: String,
    pub(crate) header_is_regular_expression: bool,
    pub(crate) comment_pattern: String,
    pub(crate) password_words: Vec<String>,
    pub(crate) secret_entropy_sensibility: f64,
    pub(crate) secret_words: Vec<String>,
    pub(crate) format_functions: String,
    pub(crate) format_classes: String,
    pub(crate) format_variables: String,
    pub(crate) duplicate_string_threshold: usize,
    pub(crate) ignored_strings: Vec<String>,
    pub(crate) single_quotes: bool,
    pub(crate) jsx_attribute_whitelist: Vec<String>,
}

impl Default for RuleOptions {
    fn default() -> Self {
        let split_words = |value: &str| {
            value
                .split(',')
                .filter(|word| !word.is_empty())
                .map(ToOwned::to_owned)
                .collect()
        };
        Self {
            maximum_lines_of_code: 1000,
            maximum_function_lines: 200,
            header_format: String::new(),
            header_is_regular_expression: false,
            comment_pattern: r"^\s*[^\s]+$".to_string(),
            password_words: split_words("password,pwd,passwd,passphrase"),
            secret_entropy_sensibility: 5.0,
            secret_words: split_words("api[_.-]?key,auth,credential,secret,token"),
            format_functions: r"^[_a-z][a-zA-Z0-9]*$".to_string(),
            format_classes: r"^[A-Z][a-zA-Z0-9]*$".to_string(),
            format_variables: r"^[_$A-Za-z][$A-Za-z0-9]*$|^[_$A-Z][_$A-Z0-9]+$".to_string(),
            duplicate_string_threshold: 3,
            ignored_strings: split_words("application/json"),
            single_quotes: true,
            jsx_attribute_whitelist: split_words(""),
        }
    }
}

use crate::support::LineIndex;
use crate::{AnalyzerOptions, JstsLanguage};

/// Everything a rule check needs: parsed program plus source state.
pub(crate) struct AnalysisContext<'a> {
    pub(crate) path: &'a std::path::Path,
    pub(crate) source: &'a str,
    pub(crate) program: &'a oxc_ast::ast::Program<'a>,
    pub(crate) index: &'a LineIndex,
    pub(crate) language: JstsLanguage,
    pub(crate) options: &'a AnalyzerOptions,
    pub(crate) rules: &'a RuleOptions,
}
