[package]
name = "hoonarqube-bench"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "hoonarqube-bench"
path = "src/main.rs"

[dependencies]
hoonarqube-csharp = { path = "../hoonarqube-csharp" }
hoonarqube-go = { path = "../hoonarqube-go" }
hoonarqube-jsts = { path = "../hoonarqube-jsts" }
hoonarqube-python = { path = "../hoonarqube-python" }
hoonarqube-rust = { path = "../hoonarqube-rust" }

[lints]
workspace = true
