//! Generated from `SonarQube` Community Build 26.8.0.126808 Rust oracle output.
//! Oracle report SHA-256: 108172f8b348f3e3f68138aa86861996cc2add7a1db6c1915bf97fcb7a96d285.
//! Regenerate with `tools/oracle/generate_rust_contract.py`.

#[derive(Clone, Copy)]
pub(super) struct FindingContract {
    pub key: &'static str,
    pub message: &'static str,
    pub anchor: &'static str,
    pub occurrence: usize,
    pub start_column: usize,
    pub end_line_delta: usize,
    pub end_column: usize,
}

pub(super) const MESSAGES: &[(&str, &str)] = &[
    (
        "rust:S106",
        "Use a logging framework to log this message to the console.",
    ),
    (
        "rust:S107",
        "Refactor the function to reduce the number of parameters.",
    ),
    ("rust:S1116", "Remove this semicolon."),
    (
        "rust:S126",
        "Add an `else` block to this `if`-`else if` chain.",
    ),
    (
        "rust:S1488",
        "Remove the `let` statement and return the expression directly.",
    ),
    (
        "rust:S1612",
        "Replace this closure with a method reference.",
    ),
    (
        "rust:S1656",
        "Remove or correct this useless self-assignment.",
    ),
    (
        "rust:S1751",
        "Refactor this loop to perform more than one iteration or remove it.",
    ),
    (
        "rust:S1764",
        "Correct expressions where identical variables are used on both sides of a binary operator.",
    ),
    (
        "rust:S1862",
        "Eliminate or alter consecutive `if` statements that share the same condition to prevent potential copy-paste errors.",
    ),
    (
        "rust:S2148",
        "Use underscore delimiters to make the literal easier to read.",
    ),
    (
        "rust:S2185",
        "Replace `x * 0`, `0 / x`, or `x & 0` with a direct constant value.",
    ),
    (
        "rust:S2193",
        "Avoid using floating-point numbers as loop counters.",
    ),
    (
        "rust:S2198",
        "Remove the unnecessary comparison or correct the logic to use an appropriate check.",
    ),
    (
        "rust:S2208",
        "Replace this wildcard import with specific imports.",
    ),
    ("rust:S2260", "A syntax error occurred during parsing."),
    ("rust:S2437", "Remove this unnecessary bit mask operation."),
    (
        "rust:S2479",
        "Remove this invisible character from this literal.",
    ),
    (
        "rust:S2589",
        "Simplify this boolean expression and eliminate unnecessary terminals.",
    ),
    ("rust:S3498", "Use the field init shorthand syntax."),
    (
        "rust:S3776",
        "Refactor this function to reduce its Cognitive Complexity from 21 to the 15 allowed.",
    ),
    ("rust:S4325", "Remove this unnecessary cast."),
    (
        "rust:S4962",
        "Use `ptr::null()` instead of `0 as` to cast to a null pointer.",
    ),
    (
        "rust:S5856",
        "Correct the regex pattern to ensure it compiles without errors.",
    ),
    (
        "rust:S6164",
        "Replace approximate floating-point literals with their corresponding predefined constants from the standard library.",
    ),
    (
        "rust:S6466",
        "Accessing an array with an out-of-bounds index will cause a runtime panic.",
    ),
    (
        "rust:S6913",
        "Correct the order of min and max functions to avoid unintended constant results.",
    ),
    (
        "rust:S7089",
        "Use a vector literal to initialize the vector.",
    ),
    (
        "rust:S7200",
        "Replace `Vec::resize(0, value)` with `Vec::clear()`, or swap the `Vec::resize` arguments.",
    ),
    (
        "rust:S7411",
        "Refactor the code to avoid duplicating logic in multiple branches.",
    ),
    (
        "rust:S7412",
        "Remove the use of `offset` or `wrapping_add`/`wrapping_sub` on pointers to zero-sized types.",
    ),
    (
        "rust:S7413",
        "Add `.await` to the returned future within the async context.",
    ),
    ("rust:S7414", "Remove or correct this transmute operation."),
    (
        "rust:S7415",
        "Ensure that variables within the while condition are mutated in the body of the loop.",
    ),
    (
        "rust:S7417",
        "Replace manual `PartialOrd` and `Ord` implementations with either entirely derived or entirely manual implementations.",
    ),
    (
        "rust:S7418",
        "Remove this useless lint attribute, or place it on the imported items themselves.",
    ),
    (
        "rust:S7419",
        "Process the entire buffer with `write_all(&buffer)` or `read_exact(&buffer)`.",
    ),
    (
        "rust:S7420",
        "Do not transmute collections of different types; use iteration and mapping instead.",
    ),
    (
        "rust:S7421",
        "Ensure the closure properly returns an `Ord` type or remove any extraneous semi-colons.",
    ),
    (
        "rust:S7422",
        "Replace `().hash(_)` with `0_u8.hash(_)` to yield a meaningful hash value.",
    ),
    (
        "rust:S7423",
        "Remove comparisons and asserts involving the unit type `()`.",
    ),
    (
        "rust:S7424",
        "Replace this manually implemented `PartialEq` with the derived implementation.",
    ),
    (
        "rust:S7425",
        "Prevent undefined behavior by not using `MaybeUninit::uninit().assume_init()`.",
    ),
    (
        "rust:S7426",
        "Replace this `repr(isize/usize)` with a portable type.",
    ),
    (
        "rust:S7427",
        "Use `Option` to represent a nullable reference",
    ),
    (
        "rust:S7428",
        "Refactor this `match` so that all arms compare strings in consistent casing.",
    ),
    (
        "rust:S7429",
        "Use `Option<fn()>` to safely represent a nullable function pointer.",
    ),
    ("rust:S7430", "Use `splitn` with at least two splits."),
    (
        "rust:S7431",
        "Use the element count directly instead of `size_of::<T>`.",
    ),
    (
        "rust:S7432",
        "Invert the start and end values of the range, and reverse it with `.rev()`.",
    ),
    (
        "rust:S7433",
        "Replace this potentially incorrect cast with a safe alternative.",
    ),
    (
        "rust:S7436",
        "Remove this redundant comparison, or correct the intended comparison logic.",
    ),
    (
        "rust:S7437",
        "Use `std::mem::swap(&mut var1, &mut var2)` instead of `var1 = var2; var2 = var1;`.",
    ),
    (
        "rust:S7438",
        "Correct this bit mask to ensure the comparison does not always yield the same result.",
    ),
    (
        "rust:S7439",
        "Refactor or remove this comparison that always evaluates to false.",
    ),
    (
        "rust:S7440",
        "Refactor this formatting implementation to avoid infinite recursion.",
    ),
    (
        "rust:S7441",
        "Always trim the trailing newline when using `Stdin::read_line`.",
    ),
    (
        "rust:S7442",
        "Avoid using `unwrap()` in conditions that will always cause a panic. Use explicit `panic!()` if panicking is intended.",
    ),
    (
        "rust:S7443",
        "Make sure that this call to `std::mem::transmute` is lazily evaluated.",
    ),
    (
        "rust:S7444",
        "Use safe methods like `checked_add` or `overflowing_add` instead of C-style overflow checks.",
    ),
    (
        "rust:S7445",
        "Use `env!(...)` to ensure compile-time checking of the environment variable.",
    ),
    (
        "rust:S7446",
        "Mark this function as `unsafe` to indicate that it dereferences raw pointer arguments.",
    ),
    (
        "rust:S7447",
        "Ensure that these file open options are consistent and do not conflict with each other.",
    ),
    (
        "rust:S7448",
        "Use octal values to set Unix file permissions.",
    ),
    (
        "rust:S7449",
        "Remove the `#[inline]` attribute from this trait method; it has no effect.",
    ),
    (
        "rust:S7451",
        "Refactor the code to remove the `% 1` or `% -1` operation.",
    ),
    ("rust:S7453", "Declare this parameter as mutable."),
    (
        "rust:S7454",
        "Use the correct suffix for this literal to represent the intended value.",
    ),
    (
        "rust:S7455",
        "Remove or replace the loop over the result of this `next()` call.",
    ),
    (
        "rust:S7456",
        "Remove `.skip(0)` from the iterator or change it to `.skip(1)` if the intention is to skip the first element.",
    ),
    (
        "rust:S7457",
        "Correct the step value in this `.step_by(0)` call.",
    ),
    (
        "rust:S7458",
        "Remove this `to_string` function as it will shadow the `Display` trait implementation.",
    ),
    ("rust:S7459", "Initialize this vector before using it."),
    ("rust:S7460", "Implement the `write_str` function as well."),
    (
        "rust:S7461",
        "Remove one of the incompatible `Hash`, `Borrow<str>` or `Borrow<[u8]>` implementations.",
    ),
    (
        "rust:S7462",
        "Replace this value with a safer alternative to avoid undefined behavior.",
    ),
    (
        "rust:S7463",
        "Substitute this conditional subtraction with `saturating_sub`.",
    ),
    (
        "rust:S7464",
        "Apply a terminating operation to this infinite iterator.",
    ),
    (
        "rust:S905",
        "Remove or correct this statement, as it has no effect.",
    ),
    (
        "rust:S920",
        "Replace this `match` expression with an `if-else` expression.",
    ),
];

pub(super) const FINDINGS: &[FindingContract] = &[
    FindingContract {
        key: "rust:S106",
        message: "Use a logging framework to log this message to the console.",
        anchor: "    println!(\"my message\");  // Noncompliant, output directly to stdout without a logger",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 26,
    },
    FindingContract {
        key: "rust:S107",
        message: "Refactor the function to reduce the number of parameters.",
        anchor: "fn set_coordinates(",
        occurrence: 0,
        start_column: 0,
        end_line_delta: 3,
        end_column: 1,
    },
    FindingContract {
        key: "rust:S1116",
        message: "Remove this semicolon.",
        anchor: "    }; // Noncompliant",
        occurrence: 0,
        start_column: 5,
        end_line_delta: 0,
        end_column: 6,
    },
    FindingContract {
        key: "rust:S1116",
        message: "Remove this semicolon.",
        anchor: "    }; // Noncompliant",
        occurrence: 1,
        start_column: 5,
        end_line_delta: 0,
        end_column: 6,
    },
    FindingContract {
        key: "rust:S126",
        message: "Add an `else` block to this `if`-`else if` chain.",
        anchor: "    } else if x == 1 {",
        occurrence: 0,
        start_column: 11,
        end_line_delta: 2,
        end_column: 5,
    },
    FindingContract {
        key: "rust:S1488",
        message: "Remove the `let` statement and return the expression directly.",
        anchor: "    let duration = (((hours * 60) + minutes) * 60 + seconds) * 1000;",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 68,
    },
    FindingContract {
        key: "rust:S1612",
        message: "Replace this closure with a method reference.",
        anchor: "    let result = Some('a').map(|s| s.to_uppercase());",
        occurrence: 0,
        start_column: 31,
        end_line_delta: 0,
        end_column: 51,
    },
    FindingContract {
        key: "rust:S1656",
        message: "Remove or correct this useless self-assignment.",
        anchor: "    x = x; // Self-assignment - does nothing",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 9,
    },
    FindingContract {
        key: "rust:S1751",
        message: "Refactor this loop to perform more than one iteration or remove it.",
        anchor: "    loop {",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 6,
        end_column: 5,
    },
    FindingContract {
        key: "rust:S1764",
        message: "Correct expressions where identical variables are used on both sides of a binary operator.",
        anchor: "fn same(x: i32) -> bool { x == x }",
        occurrence: 0,
        start_column: 26,
        end_line_delta: 0,
        end_column: 32,
    },
    FindingContract {
        key: "rust:S1862",
        message: "Eliminate or alter consecutive `if` statements that share the same condition to prevent potential copy-paste errors.",
        anchor: "    if param == 1 {",
        occurrence: 0,
        start_column: 7,
        end_line_delta: 0,
        end_column: 17,
    },
    FindingContract {
        key: "rust:S2148",
        message: "Use underscore delimiters to make the literal easier to read.",
        anchor: "    let large_number = 1000000000;",
        occurrence: 0,
        start_column: 23,
        end_line_delta: 0,
        end_column: 33,
    },
    FindingContract {
        key: "rust:S2148",
        message: "Use underscore delimiters to make the literal easier to read.",
        anchor: "    let precise_float = 1234567.890123;",
        occurrence: 0,
        start_column: 24,
        end_line_delta: 0,
        end_column: 38,
    },
    FindingContract {
        key: "rust:S2185",
        message: "Replace `x * 0`, `0 / x`, or `x & 0` with a direct constant value.",
        anchor: "    let result = 0 * x; // Noncompliant: Result is always zero.",
        occurrence: 0,
        start_column: 17,
        end_line_delta: 0,
        end_column: 22,
    },
    FindingContract {
        key: "rust:S2193",
        message: "Avoid using floating-point numbers as loop counters.",
        anchor: "    while counter < 10.0 {",
        occurrence: 0,
        start_column: 10,
        end_line_delta: 0,
        end_column: 24,
    },
    FindingContract {
        key: "rust:S2198",
        message: "Remove the unnecessary comparison or correct the logic to use an appropriate check.",
        anchor: "fn impossible(value: u32) -> bool { value < 0 }",
        occurrence: 0,
        start_column: 36,
        end_line_delta: 0,
        end_column: 45,
    },
    FindingContract {
        key: "rust:S2208",
        message: "Replace this wildcard import with specific imports.",
        anchor: "use std::collections::*; // Noncompliant",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 23,
    },
    FindingContract {
        key: "rust:S2260",
        message: "A syntax error occurred during parsing.",
        anchor: "// Hoonarqube oracle fixture: rust:S2260 bad",
        occurrence: 0,
        start_column: 0,
        end_line_delta: 4,
        end_column: 0,
    },
    FindingContract {
        key: "rust:S2260",
        message: "A syntax error occurred during parsing: missing \")\".",
        anchor: "fn broken( {",
        occurrence: 0,
        start_column: 9,
        end_line_delta: 0,
        end_column: 10,
    },
    FindingContract {
        key: "rust:S2437",
        message: "Remove this unnecessary bit mask operation.",
        anchor: "    if (x | 2) > 3 { // Noncompliant: Bit mask cannot affect this comparison",
        occurrence: 0,
        start_column: 7,
        end_line_delta: 0,
        end_column: 18,
    },
    FindingContract {
        key: "rust:S2479",
        message: "Remove this invisible character from this literal.",
        anchor: "fn hidden() { let value = \"a\u{200b}b\"; drop(value); }",
        occurrence: 0,
        start_column: 26,
        end_line_delta: 0,
        end_column: 31,
    },
    FindingContract {
        key: "rust:S2589",
        message: "Simplify this boolean expression and eliminate unnecessary terminals.",
        anchor: "    if a && b || a { // Noncompliant: `b` is redundant",
        occurrence: 0,
        start_column: 7,
        end_line_delta: 0,
        end_column: 18,
    },
    FindingContract {
        key: "rust:S3498",
        message: "Use the field init shorthand syntax.",
        anchor: "        a: a,  // Noncompliant",
        occurrence: 0,
        start_column: 8,
        end_line_delta: 0,
        end_column: 12,
    },
    FindingContract {
        key: "rust:S3776",
        message: "Refactor this function to reduce its Cognitive Complexity from 21 to the 15 allowed.",
        anchor: "fn complex(a:bool,b:bool,c:bool,d:bool,e:bool,f:bool){ if a { if b { if c { if d { if e { if f {} } } } } } } }",
        occurrence: 0,
        start_column: 3,
        end_line_delta: 0,
        end_column: 10,
    },
    FindingContract {
        key: "rust:S4325",
        message: "Remove this unnecessary cast.",
        anchor: "    let length = value.len() as usize; // Noncompliant: 'value.len()' already returns a 'usize'",
        occurrence: 0,
        start_column: 17,
        end_line_delta: 0,
        end_column: 37,
    },
    FindingContract {
        key: "rust:S4962",
        message: "Use `ptr::null()` instead of `0 as` to cast to a null pointer.",
        anchor: "    let ptr = 0 as *const i32;",
        occurrence: 0,
        start_column: 14,
        end_line_delta: 0,
        end_column: 29,
    },
    FindingContract {
        key: "rust:S4962",
        message: "Use `ptr::null()` instead of `0 as` to cast to a null pointer.",
        anchor: "    let mut_ptr = 0 as *mut i32;",
        occurrence: 0,
        start_column: 18,
        end_line_delta: 0,
        end_column: 31,
    },
    FindingContract {
        key: "rust:S5856",
        message: "Correct the regex pattern to ensure it compiles without errors.",
        anchor: "    let _ = Regex::new(\"(\");",
        occurrence: 0,
        start_column: 24,
        end_line_delta: 0,
        end_column: 25,
    },
    FindingContract {
        key: "rust:S6164",
        message: "Replace approximate floating-point literals with their corresponding predefined constants from the standard library.",
        anchor: "    let x = 3.14; // Noncompliant: Approximates PI",
        occurrence: 0,
        start_column: 12,
        end_line_delta: 0,
        end_column: 16,
    },
    FindingContract {
        key: "rust:S6164",
        message: "Replace approximate floating-point literals with their corresponding predefined constants from the standard library.",
        anchor: "    let y = 1_f64 / 3.1415926535; // Noncompliant: Approximates FRAC_1_PI",
        occurrence: 0,
        start_column: 20,
        end_line_delta: 0,
        end_column: 32,
    },
    FindingContract {
        key: "rust:S6466",
        message: "Accessing an array with an out-of-bounds index will cause a runtime panic.",
        anchor: "    println!(\"{}\", x[9]); // Out of bounds indexing",
        occurrence: 0,
        start_column: 19,
        end_line_delta: 0,
        end_column: 23,
    },
    FindingContract {
        key: "rust:S6913",
        message: "Correct the order of min and max functions to avoid unintended constant results.",
        anchor: "    let value = min(0, max(100, x));",
        occurrence: 0,
        start_column: 16,
        end_line_delta: 0,
        end_column: 35,
    },
    FindingContract {
        key: "rust:S7089",
        message: "Use a vector literal to initialize the vector.",
        anchor: "    let mut v = Vec::new();",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 3,
        end_column: 14,
    },
    FindingContract {
        key: "rust:S7200",
        message: "Replace `Vec::resize(0, value)` with `Vec::clear()`, or swap the `Vec::resize` arguments.",
        anchor: "    values.resize(0, 5); // Noncompliant: Resizing the vector to 0.",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 23,
    },
    FindingContract {
        key: "rust:S7411",
        message: "Refactor the code to avoid duplicating logic in multiple branches.",
        anchor: "    let result = if condition {",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 1,
        end_column: 32,
    },
    FindingContract {
        key: "rust:S7412",
        message: "Remove the use of `offset` or `wrapping_add`/`wrapping_sub` on pointers to zero-sized types.",
        anchor: "    unsafe { (&() as *const ()).offset(1); } // Noncompliant: No-op on zero-sized type pointer.",
        occurrence: 0,
        start_column: 13,
        end_line_delta: 0,
        end_column: 41,
    },
    FindingContract {
        key: "rust:S7413",
        message: "Add `.await` to the returned future within the async context.",
        anchor: "    let x = async {",
        occurrence: 0,
        start_column: 18,
        end_line_delta: 2,
        end_column: 5,
    },
    FindingContract {
        key: "rust:S7414",
        message: "Remove or correct this transmute operation.",
        anchor: "    let value: *const usize = unsafe { std::mem::transmute(6.0f64) }; // Noncompliant",
        occurrence: 0,
        start_column: 39,
        end_line_delta: 0,
        end_column: 66,
    },
    FindingContract {
        key: "rust:S7415",
        message: "Ensure that variables within the while condition are mutated in the body of the loop.",
        anchor: "    while i > 10 {",
        occurrence: 0,
        start_column: 10,
        end_line_delta: 0,
        end_column: 16,
    },
    FindingContract {
        key: "rust:S7417",
        message: "Replace manual `PartialOrd` and `Ord` implementations with either entirely derived or entirely manual implementations.",
        anchor: "#[derive(Ord, PartialEq, Eq)]",
        occurrence: 0,
        start_column: 9,
        end_line_delta: 0,
        end_column: 12,
    },
    FindingContract {
        key: "rust:S7418",
        message: "Remove this useless lint attribute, or place it on the imported items themselves.",
        anchor: "    #[allow(clippy::almost_swapped)] // Noncompliant: ineffective on import",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 36,
    },
    FindingContract {
        key: "rust:S7419",
        message: "Process the entire buffer with `write_all(&buffer)` or `read_exact(&buffer)`.",
        anchor: "    r.read(buffer)?; // Noncompliant: This might not read the entire buffer.",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 19,
    },
    FindingContract {
        key: "rust:S7419",
        message: "Process the entire buffer with `write_all(&buffer)` or `read_exact(&buffer)`.",
        anchor: "    w.write(b\"foo\")?; // Noncompliant: This might not write the entire buffer.",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 20,
    },
    FindingContract {
        key: "rust:S7420",
        message: "Do not transmute collections of different types; use iteration and mapping instead.",
        anchor: "        std::mem::transmute::<_, Vec<u32>>(values) // Noncompliant",
        occurrence: 0,
        start_column: 8,
        end_line_delta: 0,
        end_column: 50,
    },
    FindingContract {
        key: "rust:S7421",
        message: "Ensure the closure properly returns an `Ord` type or remove any extraneous semi-colons.",
        anchor: "    twins.sort_by_key(|x| { x.1; }); // Noncompliant: closure returns unit",
        occurrence: 0,
        start_column: 22,
        end_line_delta: 0,
        end_column: 25,
    },
    FindingContract {
        key: "rust:S7422",
        message: "Replace `().hash(_)` with `0_u8.hash(_)` to yield a meaningful hash value.",
        anchor: "        Foo::Empty => ().hash(&mut state), // Noncompliant",
        occurrence: 0,
        start_column: 22,
        end_line_delta: 0,
        end_column: 41,
    },
    FindingContract {
        key: "rust:S7423",
        message: "Remove comparisons and asserts involving the unit type `()`.",
        anchor: "    if {",
        occurrence: 0,
        start_column: 7,
        end_line_delta: 4,
        end_column: 5,
    },
    FindingContract {
        key: "rust:S7424",
        message: "Replace this manually implemented `PartialEq` with the derived implementation.",
        anchor: "#[derive(Hash)]",
        occurrence: 0,
        start_column: 9,
        end_line_delta: 0,
        end_column: 13,
    },
    FindingContract {
        key: "rust:S7425",
        message: "Prevent undefined behavior by not using `MaybeUninit::uninit().assume_init()`.",
        anchor: "    let _: usize = unsafe { MaybeUninit::uninit().assume_init() }; // Noncompliant",
        occurrence: 0,
        start_column: 28,
        end_line_delta: 0,
        end_column: 63,
    },
    FindingContract {
        key: "rust:S7426",
        message: "Replace this `repr(isize/usize)` with a portable type.",
        anchor: "    X = 0x1_0000_0000, // Noncompliant",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 21,
    },
    FindingContract {
        key: "rust:S7427",
        message: "Use `Option` to represent a nullable reference",
        anchor: "    let null_ref: &u64 = unsafe { std::mem::transmute(0 as *const u64) }; // Noncompliant",
        occurrence: 0,
        start_column: 34,
        end_line_delta: 0,
        end_column: 70,
    },
    FindingContract {
        key: "rust:S7428",
        message: "Refactor this `match` so that all arms compare strings in consistent casing.",
        anchor: "        \"Bar\" => {}, // Noncompliant: This arm cannot match lowercased text.",
        occurrence: 0,
        start_column: 8,
        end_line_delta: 0,
        end_column: 13,
    },
    FindingContract {
        key: "rust:S7429",
        message: "Use `Option<fn()>` to safely represent a nullable function pointer.",
        anchor: "    let null_fn: fn() = unsafe { std::mem::transmute(std::ptr::null::<()>()) }; // Noncompliant",
        occurrence: 0,
        start_column: 33,
        end_line_delta: 0,
        end_column: 76,
    },
    FindingContract {
        key: "rust:S7430",
        message: "Use `splitn` with at least two splits.",
        anchor: "    for part in text.splitn(1, \":\") { // Noncompliant",
        occurrence: 0,
        start_column: 16,
        end_line_delta: 0,
        end_column: 35,
    },
    FindingContract {
        key: "rust:S7431",
        message: "Use the element count directly instead of `size_of::<T>`.",
        anchor: "            x.as_ptr(), y.as_mut_ptr(), std::mem::size_of::<u16>()",
        occurrence: 0,
        start_column: 40,
        end_line_delta: 0,
        end_column: 66,
    },
    FindingContract {
        key: "rust:S7432",
        message: "Invert the start and end values of the range, and reverse it with `.rev()`.",
        anchor: "    (10..=0).for_each(|x| println!(\"{}\", x)); // Noncompliant: Empty range",
        occurrence: 0,
        start_column: 5,
        end_line_delta: 0,
        end_column: 11,
    },
    FindingContract {
        key: "rust:S7432",
        message: "Invert the start and end values of the range, and reverse it with `.rev()`.",
        anchor: "    let sub = &arr[3..1]; // Noncompliant: Reversed slice indexing",
        occurrence: 0,
        start_column: 19,
        end_line_delta: 0,
        end_column: 23,
    },
    FindingContract {
        key: "rust:S7433",
        message: "Replace this potentially incorrect cast with a safe alternative.",
        anchor: "    let p = &a as *const [u8] as *const [u32];",
        occurrence: 0,
        start_column: 12,
        end_line_delta: 0,
        end_column: 45,
    },
    FindingContract {
        key: "rust:S7436",
        message: "Remove this redundant comparison, or correct the intended comparison logic.",
        anchor: "    if status_code <= 400 && status_code < 500 { // Noncompliant",
        occurrence: 0,
        start_column: 7,
        end_line_delta: 0,
        end_column: 46,
    },
    FindingContract {
        key: "rust:S7437",
        message: "Use `std::mem::swap(&mut var1, &mut var2)` instead of `var1 = var2; var2 = var1;`.",
        anchor: "    foo = bar; // Noncompliant",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 1,
        end_column: 13,
    },
    FindingContract {
        key: "rust:S7438",
        message: "Correct this bit mask to ensure the comparison does not always yield the same result.",
        anchor: "    if x & 1 == 2 { // Noncompliant: impossible bit mask",
        occurrence: 0,
        start_column: 7,
        end_line_delta: 0,
        end_column: 17,
    },
    FindingContract {
        key: "rust:S7439",
        message: "Refactor or remove this comparison that always evaluates to false.",
        anchor: "fn impossible(value: i32) -> bool { value < 2 && value > 8 }",
        occurrence: 0,
        start_column: 36,
        end_line_delta: 0,
        end_column: 58,
    },
    FindingContract {
        key: "rust:S7440",
        message: "Refactor this formatting implementation to avoid infinite recursion.",
        anchor: "        write!(f, \"{}\", self.to_string()) // Noncompliant",
        occurrence: 0,
        start_column: 24,
        end_line_delta: 0,
        end_column: 40,
    },
    FindingContract {
        key: "rust:S7441",
        message: "Always trim the trailing newline when using `Stdin::read_line`.",
        anchor: "    let num: i32 = input.parse().expect(\"not a number\"); // Noncompliant",
        occurrence: 0,
        start_column: 25,
        end_line_delta: 0,
        end_column: 32,
    },
    FindingContract {
        key: "rust:S7442",
        message: "Avoid using `unwrap()` in conditions that will always cause a panic. Use explicit `panic!()` if panicking is intended.",
        anchor: "    if option.is_none() {",
        occurrence: 0,
        start_column: 7,
        end_line_delta: 0,
        end_column: 23,
    },
    FindingContract {
        key: "rust:S7443",
        message: "Make sure that this call to `std::mem::transmute` is lazily evaluated.",
        anchor: "    (op < 4).then_some(unsafe { std::mem::transmute(op) })",
        occurrence: 0,
        start_column: 32,
        end_line_delta: 0,
        end_column: 55,
    },
    FindingContract {
        key: "rust:S7444",
        message: "Use safe methods like `checked_add` or `overflowing_add` instead of C-style overflow checks.",
        anchor: "    if a + b < a { // Noncompliant: overflow check may itself panic",
        occurrence: 0,
        start_column: 7,
        end_line_delta: 0,
        end_column: 16,
    },
    FindingContract {
        key: "rust:S7445",
        message: "Use `env!(...)` to ensure compile-time checking of the environment variable.",
        anchor: "    let _ = option_env!(\"HOONARQUBE_ORACLE_UNSET\").unwrap(); // Noncompliant",
        occurrence: 0,
        start_column: 12,
        end_line_delta: 0,
        end_column: 59,
    },
    FindingContract {
        key: "rust:S7446",
        message: "Mark this function as `unsafe` to indicate that it dereferences raw pointer arguments.",
        anchor: "    println!(\"{}\", unsafe { *x });",
        occurrence: 0,
        start_column: 29,
        end_line_delta: 0,
        end_column: 30,
    },
    FindingContract {
        key: "rust:S7447",
        message: "Ensure that these file open options are consistent and do not conflict with each other.",
        anchor: "    let _ = OpenOptions::new().read(true).truncate(true).open(\"oracle.txt\"); // Noncompliant",
        occurrence: 0,
        start_column: 12,
        end_line_delta: 0,
        end_column: 75,
    },
    FindingContract {
        key: "rust:S7448",
        message: "Use octal values to set Unix file permissions.",
        anchor: "    options.mode(644); // Noncompliant: non-octal value used",
        occurrence: 0,
        start_column: 17,
        end_line_delta: 0,
        end_column: 20,
    },
    FindingContract {
        key: "rust:S7449",
        message: "Remove the `#[inline]` attribute from this trait method; it has no effect.",
        anchor: "    #[inline] // Noncompliant: Inline attribute on trait method without implementation.",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 13,
    },
    FindingContract {
        key: "rust:S7451",
        message: "Refactor the code to remove the `% 1` or `% -1` operation.",
        anchor: "    let a = x % 1; // Noncompliant: remainder by one",
        occurrence: 0,
        start_column: 12,
        end_line_delta: 0,
        end_column: 17,
    },
    FindingContract {
        key: "rust:S7453",
        message: "Declare this parameter as mutable.",
        anchor: "fn foo(x: &Foo) -> &mut Bar {",
        occurrence: 0,
        start_column: 19,
        end_line_delta: 0,
        end_column: 27,
    },
    FindingContract {
        key: "rust:S7454",
        message: "Use the correct suffix for this literal to represent the intended value.",
        anchor: "    let x = 2_32; // Noncompliant: mistyped literal suffix",
        occurrence: 0,
        start_column: 12,
        end_line_delta: 0,
        end_column: 16,
    },
    FindingContract {
        key: "rust:S7454",
        message: "Use the correct suffix for this literal to represent the intended value.",
        anchor: "    let y = 250_8;",
        occurrence: 0,
        start_column: 12,
        end_line_delta: 0,
        end_column: 17,
    },
    FindingContract {
        key: "rust:S7455",
        message: "Remove or replace the loop over the result of this `next()` call.",
        anchor: "    for value in iterator.next() { // Noncompliant",
        occurrence: 0,
        start_column: 17,
        end_line_delta: 0,
        end_column: 32,
    },
    FindingContract {
        key: "rust:S7456",
        message: "Remove `.skip(0)` from the iterator or change it to `.skip(1)` if the intention is to skip the first element.",
        anchor: "    let skipped = values.iter().skip(0).collect::<Vec<_>>(); // Noncompliant",
        occurrence: 0,
        start_column: 37,
        end_line_delta: 0,
        end_column: 38,
    },
    FindingContract {
        key: "rust:S7457",
        message: "Correct the step value in this `.step_by(0)` call.",
        anchor: "    for x in (0..100).step_by(0) { // Noncompliant: panics",
        occurrence: 0,
        start_column: 13,
        end_line_delta: 0,
        end_column: 32,
    },
    FindingContract {
        key: "rust:S7458",
        message: "Remove this `to_string` function as it will shadow the `Display` trait implementation.",
        anchor: "    pub fn to_string(&self) -> String {",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 2,
        end_column: 5,
    },
    FindingContract {
        key: "rust:S7459",
        message: "Initialize this vector before using it.",
        anchor: "    let mut vec: Vec<u8> = Vec::with_capacity(1000);",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 0,
        end_column: 52,
    },
    FindingContract {
        key: "rust:S7460",
        message: "Implement the `write_str` function as well.",
        anchor: "    fn visit_string<E>(self, _v: String) -> Result<Self::Value, E>",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 2,
        end_column: 28,
    },
    FindingContract {
        key: "rust:S7461",
        message: "Remove one of the incompatible `Hash`, `Borrow<str>` or `Borrow<[u8]>` implementations.",
        anchor: "impl Hash for Key { fn hash<H: Hasher>(&self, state: &mut H) { self.0.hash(state); } }",
        occurrence: 0,
        start_column: 5,
        end_line_delta: 0,
        end_column: 9,
    },
    FindingContract {
        key: "rust:S7462",
        message: "Replace this value with a safer alternative to avoid undefined behavior.",
        anchor: "    let taken_v = unsafe { mem::replace(v, mem::uninitialized()) }; // Noncompliant",
        occurrence: 0,
        start_column: 27,
        end_line_delta: 0,
        end_column: 64,
    },
    FindingContract {
        key: "rust:S7463",
        message: "Substitute this conditional subtraction with `saturating_sub`.",
        anchor: "    let result = if a > b { b - a } else { 0 }; // Noncompliant",
        occurrence: 0,
        start_column: 22,
        end_line_delta: 0,
        end_column: 23,
    },
    FindingContract {
        key: "rust:S7464",
        message: "Apply a terminating operation to this infinite iterator.",
        anchor: "    let values = iter::repeat(1_u8).collect::<Vec<_>>(); // Noncompliant: infinite iterator",
        occurrence: 0,
        start_column: 17,
        end_line_delta: 0,
        end_column: 55,
    },
    FindingContract {
        key: "rust:S905",
        message: "Remove or correct this statement, as it has no effect.",
        anchor: "        result == 0; // Noncompliant: no side effect, was an assignment intended?",
        occurrence: 0,
        start_column: 8,
        end_line_delta: 0,
        end_column: 20,
    },
    FindingContract {
        key: "rust:S920",
        message: "Replace this `match` expression with an `if-else` expression.",
        anchor: "    match value {",
        occurrence: 0,
        start_column: 4,
        end_line_delta: 3,
        end_column: 5,
    },
];
