//! `support` facade: one submodule per former section banner.

mod aws_call_shape_helpers;
mod django_conventions;
mod effect_effect_retention_tracking;
mod literal_kind_classification_for_operator_rules;
mod literal_kind_helpers_for_the_operator_exception_family;
mod pandas_heuristics;
mod per_rule_implementations;
mod prelude;
mod python_s2068_hard_coded_credentials;
mod python_s2092_s3330_cookie_secure_and_httponly_flags;
mod python_s2275_python_s3457_printf_style_formatting;
mod python_s2823_all_must_contain_only_strings;
mod python_s3699_output_of_functions_returning_nothing_should_not_be;
mod python_s3984_exception_instantiated_but_never_raised;
mod python_s4144_identical_sibling_function_implementations;
mod python_s5247_s5439_html_autoescaping_disabled;
mod python_s5709_custom_exceptions_inherit_exception;
mod python_s5713_subclass_and_parent_should_not_share_an_except_clau;
mod python_s5719_instance_class_methods_need_a_positional_parameter;
mod python_s5797_constant_conditions;
mod python_s5906_python_s5914_imprecise_and_unconditional_asserts;
mod python_s6418_python_s6437_hard_coded_secrets;
mod python_s6662_unhashable_set_members_and_dict_keys;
mod python_s6911_s6918_s6928_tf_function_contracts;
mod python_s6919_python_s6974_keras_model_baseestimator_subclass_con;
mod python_s6969_s6973_s6971_scikit_learn_contracts;
mod python_s7487_s7493_s7499_s7501_s7488_s7489_blocking_calls;
mod python_s7490_python_s7497_cancellation_contracts;
mod python_s7494_comprehension_over_a_generator_expression;
mod python_s7506_static_value_in_dict_comprehension;
mod python_s7508_redundant_identical_nested_constructors;
mod python_s7513_python_s7514_nursery_blocks;
mod python_s930_call_arguments_should_match_parameters;
mod shared_helpers_for_the_tier_a_rule_battery;
mod shared_literal_helpers;
mod style_shapes_s6353_s6396_s6397_s5869_s5868_s5843_s5857;
mod typing_syntax_rules_168_178;
mod unittest_misc_remainder_180_192_and_185_189_companions;

pub(crate) use aws_call_shape_helpers::*;
pub(crate) use django_conventions::*;
pub(crate) use effect_effect_retention_tracking::*;
pub(crate) use literal_kind_classification_for_operator_rules::*;
pub(crate) use literal_kind_helpers_for_the_operator_exception_family::*;
pub(crate) use pandas_heuristics::*;
pub(crate) use per_rule_implementations::*;
pub(crate) use prelude::*;
pub(crate) use python_s930_call_arguments_should_match_parameters::*;
pub(crate) use python_s2068_hard_coded_credentials::*;
pub(crate) use python_s2092_s3330_cookie_secure_and_httponly_flags::*;
pub(crate) use python_s2275_python_s3457_printf_style_formatting::*;
pub(crate) use python_s2823_all_must_contain_only_strings::*;
pub(crate) use python_s3699_output_of_functions_returning_nothing_should_not_be::*;
pub(crate) use python_s3984_exception_instantiated_but_never_raised::*;
pub(crate) use python_s4144_identical_sibling_function_implementations::*;
pub(crate) use python_s5247_s5439_html_autoescaping_disabled::*;
pub(crate) use python_s5709_custom_exceptions_inherit_exception::*;
pub(crate) use python_s5713_subclass_and_parent_should_not_share_an_except_clau::*;
pub(crate) use python_s5719_instance_class_methods_need_a_positional_parameter::*;
pub(crate) use python_s5797_constant_conditions::*;
pub(crate) use python_s5906_python_s5914_imprecise_and_unconditional_asserts::*;
pub(crate) use python_s6418_python_s6437_hard_coded_secrets::*;
pub(crate) use python_s6662_unhashable_set_members_and_dict_keys::*;
pub(crate) use python_s6911_s6918_s6928_tf_function_contracts::*;
pub(crate) use python_s6919_python_s6974_keras_model_baseestimator_subclass_con::*;
pub(crate) use python_s6969_s6973_s6971_scikit_learn_contracts::*;
pub(crate) use python_s7487_s7493_s7499_s7501_s7488_s7489_blocking_calls::*;
pub(crate) use python_s7490_python_s7497_cancellation_contracts::*;
pub(crate) use python_s7494_comprehension_over_a_generator_expression::*;
pub(crate) use python_s7506_static_value_in_dict_comprehension::*;
pub(crate) use python_s7508_redundant_identical_nested_constructors::*;
pub(crate) use python_s7513_python_s7514_nursery_blocks::*;
pub(crate) use shared_helpers_for_the_tier_a_rule_battery::*;
pub(crate) use shared_literal_helpers::*;
pub(crate) use style_shapes_s6353_s6396_s6397_s5869_s5868_s5843_s5857::*;
pub(crate) use typing_syntax_rules_168_178::*;
pub(crate) use unittest_misc_remainder_180_192_and_185_189_companions::*;
