[package]
name = "hoonarqube-jsts"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
hoonarqube-ir = { version = "0.3.1", path = "../hoonarqube-ir" }
oxc_allocator = "0.146.0"
oxc_ast_visit = "0.146.0"
oxc_ast = "0.146.0"
oxc_parser = "0.146.0"
oxc_span = "0.146.0"
oxc_syntax = "0.146.0"

[dev-dependencies]
hoonarqube-core = { version = "0.3.1", path = "../hoonarqube-core" }
[lints]
workspace = true
