// Generated by jsts_split.py - part of the per-rule refactor.
use crate::support::to_u32;
use oxc_ast::ast::{Expression, RegExpFlags, RegExpLiteral};
use oxc_span::{GetSpan, Span};

/// Whether a `/` at this point starts a regex literal instead of a division.
pub(crate) fn regex_can_start(prev: Option<char>, word: &str) -> bool {
    match prev {
        None => true,
        Some(c) => {
            matches!(
                c,
                '(' | ','
                    | '='
                    | ':'
                    | '['
                    | '!'
                    | '&'
                    | '|'
                    | '?'
                    | '{'
                    | '}'
                    | ';'
                    | '+'
                    | '-'
                    | '*'
                    | '%'
                    | '~'
                    | '^'
                    | '<'
                    | '>'
            ) || matches!(
                word,
                "return"
                    | "typeof"
                    | "case"
                    | "in"
                    | "of"
                    | "new"
                    | "delete"
                    | "void"
                    | "instanceof"
                    | "do"
                    | "else"
                    | "yield"
                    | "await"
            )
        }
    }
}

/// Skips a regex literal starting at `chars[i - 1] == '/'`; returns the index
/// of the closing `/` (or the line end on unterminated regexes).
pub(crate) fn skip_regex_literal(chars: &[char], mut i: usize) -> usize {
    while i < chars.len() {
        if chars[i] == '\\' {
            i += 2;
            continue;
        }
        if chars[i] == '[' {
            // Character class: `/` inside is literal.
            i += 1;
            while i < chars.len() && chars[i] != ']' {
                i += if chars[i] == '\\' { 2 } else { 1 };
            }
        } else if chars[i] == '/' || chars[i] == '\n' {
            break;
        }
        i += 1;
    }
    i
}

/// Minimal backtracking regex matcher for catalog string parameters
/// (`S139` `pattern`, `S1451` regular-expression header formats, `S6418`
/// `secretWords`). Supported: literals, `.`, `[…]` classes with ranges and
/// negation, `\d \D \w \W \s \S \t \n \r \\` escapes, `(…)` groups,
/// alternation, `* + ? {m} {m,} {m,n}` quantifiers, and `^`/`$` anchors
/// bound to the whole subject. Patterns using anything else fail to compile
/// and match nothing (tolerant, never panics).

#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum RegexNode {
    Char(char),
    /// `.`: any character except `\n`.
    AnyChar,
    Class {
        negated: bool,
        ranges: Vec<(char, char)>,
    },
    StartAnchor,
    EndAnchor,
    Group(Vec<Vec<RegexNode>>),
    Repeat {
        node: Box<RegexNode>,
        min: usize,
        max: Option<usize>,
    },
}

pub(crate) const CLASS_DIGIT: [(char, char); 1] = [('0', '9')];

pub(crate) const CLASS_WORD: [(char, char); 3] = [('a', 'z'), ('A', 'Z'), ('0', '9')];

pub(crate) fn regex_search(pattern: &str, subject: &str) -> bool {
    let Some(alternatives) = parse_regex(pattern) else {
        return false;
    };
    let chars: Vec<char> = subject.chars().collect();
    (0..=chars.len()).any(|start| match_alternatives(&alternatives, &chars, start, &mut |_| true))
}

/// Matches `subject` only where the match starts at offset zero.
pub(crate) fn regex_prefix_match(pattern: &str, subject: &str) -> bool {
    let Some(alternatives) = parse_regex(pattern) else {
        return false;
    };
    let chars: Vec<char> = subject.chars().collect();
    match_alternatives(&alternatives, &chars, 0, &mut |_| true)
}

pub(crate) fn match_alternatives(
    alternatives: &[Vec<RegexNode>],
    text: &[char],
    pos: usize,
    tail: &mut dyn FnMut(usize) -> bool,
) -> bool {
    alternatives
        .iter()
        .any(|sequence| match_sequence(sequence, text, pos, tail))
}

pub(crate) fn match_sequence(
    nodes: &[RegexNode],
    text: &[char],
    pos: usize,
    tail: &mut dyn FnMut(usize) -> bool,
) -> bool {
    let Some((first, rest)) = nodes.split_first() else {
        return tail(pos);
    };
    match_node(first, text, pos, &mut |next| {
        match_sequence(rest, text, next, tail)
    })
}

pub(crate) fn match_node(
    node: &RegexNode,
    text: &[char],
    pos: usize,
    tail: &mut dyn FnMut(usize) -> bool,
) -> bool {
    match node {
        RegexNode::Char(expected) => text.get(pos) == Some(expected) && tail(pos + 1),
        RegexNode::AnyChar => pos < text.len() && text[pos] != '\n' && tail(pos + 1),
        RegexNode::Class { negated, ranges } => {
            let Some(c) = text.get(pos) else {
                return false;
            };
            let hit = ranges.iter().any(|(low, high)| low <= c && c <= high);
            (hit != *negated) && tail(pos + 1)
        }
        RegexNode::StartAnchor => pos == 0 && tail(pos),
        RegexNode::EndAnchor => pos == text.len() && tail(pos),
        RegexNode::Group(alternatives) => match_alternatives(alternatives, text, pos, tail),
        RegexNode::Repeat { node, min, max } => match_repeat(node, *min, *max, 0, text, pos, tail),
    }
}

pub(crate) fn match_repeat(
    node: &RegexNode,
    min: usize,
    max: Option<usize>,
    count: usize,
    text: &[char],
    pos: usize,
    tail: &mut dyn FnMut(usize) -> bool,
) -> bool {
    let may_repeat_more = max.is_none_or(|limit| count < limit);
    if may_repeat_more
        && match_node(node, text, pos, &mut |next| {
            // Zero-width repetitions would loop forever; reject them.
            next != pos && match_repeat(node, min, max, count + 1, text, next, tail)
        })
    {
        return true;
    }
    count >= min && tail(pos)
}

pub(crate) fn parse_regex(pattern: &str) -> Option<Vec<Vec<RegexNode>>> {
    let mut parser = RegexParser {
        chars: pattern.chars().collect(),
        pos: 0,
    };
    let alternatives = parser.parse_group_body()?;
    parser.expect_end()?;
    Some(alternatives)
}

pub(crate) struct RegexParser {
    pub(crate) chars: Vec<char>,
    pub(crate) pos: usize,
}

impl RegexParser {
    pub(crate) fn peek(&self) -> Option<char> {
        self.chars.get(self.pos).copied()
    }

    pub(crate) fn bump(&mut self) -> Option<char> {
        let c = self.peek()?;
        self.pos += 1;
        Some(c)
    }

    pub(crate) fn eat(&mut self, expected: char) -> bool {
        if self.peek() == Some(expected) {
            self.pos += 1;
            true
        } else {
            false
        }
    }

    pub(crate) fn expect_end(&self) -> Option<()> {
        (self.pos == self.chars.len()).then_some(())
    }

    /// Alternatives up to an unmatched closing parenthesis.
    pub(crate) fn parse_group_body(&mut self) -> Option<Vec<Vec<RegexNode>>> {
        let mut alternatives = vec![self.parse_sequence()?];
        while self.eat('|') {
            alternatives.push(self.parse_sequence()?);
        }
        Some(alternatives)
    }

    pub(crate) fn parse_sequence(&mut self) -> Option<Vec<RegexNode>> {
        let mut nodes = Vec::new();
        while let Some(c) = self.peek()
            && c != '|'
            && c != ')'
        {
            nodes.push(self.parse_atom_quantified()?);
        }
        Some(nodes)
    }

    pub(crate) fn parse_atom_quantified(&mut self) -> Option<RegexNode> {
        let atom = self.parse_atom()?;
        let (min, max) = match self.peek() {
            Some('*') => {
                self.pos += 1;
                (0, None)
            }
            Some('+') => {
                self.pos += 1;
                (1, None)
            }
            Some('?') => {
                self.pos += 1;
                (0, Some(1))
            }
            Some('{') => self.parse_counted_range()?,
            _ => return Some(atom),
        };
        Some(RegexNode::Repeat {
            node: Box::new(atom),
            min,
            max,
        })
    }

    /// `{m}`, `{m,}` or `{m,n}` (the opening brace is unconsumed).
    pub(crate) fn parse_counted_range(&mut self) -> Option<(usize, Option<usize>)> {
        let saved = self.pos;
        self.pos += 1; // consume `{`
        let minimum = self.parse_number()?;
        let maximum = if self.eat(',') {
            if self.peek() == Some('}') {
                None
            } else {
                Some(self.parse_number()?)
            }
        } else {
            Some(minimum)
        };
        if !self.eat('}') || maximum.is_some_and(|max| max < minimum) {
            self.pos = saved;
            return None;
        }
        Some((minimum, maximum))
    }

    pub(crate) fn parse_number(&mut self) -> Option<usize> {
        let digits = self.chars[self.pos..]
            .iter()
            .copied()
            .take_while(char::is_ascii_digit)
            .collect::<String>();
        if digits.is_empty() {
            return None;
        }
        self.pos += digits.len();
        digits.parse().ok()
    }

    pub(crate) fn parse_atom(&mut self) -> Option<RegexNode> {
        match self.bump()? {
            '(' => {
                let alternatives = self.parse_group_body()?;
                if !self.eat(')') {
                    return None;
                }
                Some(RegexNode::Group(alternatives))
            }
            '[' => self.parse_class(),
            '.' => Some(RegexNode::AnyChar),
            '^' => Some(RegexNode::StartAnchor),
            '$' => Some(RegexNode::EndAnchor),
            '\\' => self.parse_escape(),
            '*' | '+' | '?' => None,
            literal => Some(RegexNode::Char(literal)),
        }
    }

    pub(crate) fn parse_class(&mut self) -> Option<RegexNode> {
        let negated = self.eat('^');
        let mut ranges = Vec::new();
        // A `]` directly after the (optional) `^` is a literal.
        if self.peek() == Some(']') {
            ranges.push((']', ']'));
            self.pos += 1;
        }
        loop {
            let first = match self.bump()? {
                ']' => break,
                '\\' => self.escape_ranges()?,
                literal => vec![(literal, literal)],
            };
            if self.peek() == Some('-')
                && self
                    .chars
                    .get(self.pos + 1)
                    .is_some_and(|&next| next != ']')
            {
                self.pos += 1; // consume `-`
                let upper = match self.bump()? {
                    '\\' => self.escape_ranges()?.pop()?.0,
                    upper => upper,
                };
                ranges.push((first.first()?.0, upper));
            } else {
                ranges.extend(first);
            }
        }
        Some(RegexNode::Class { negated, ranges })
    }

    /// One escape inside or outside a class as a range list.
    pub(crate) fn escape_ranges(&mut self) -> Option<Vec<(char, char)>> {
        match self.bump()? {
            'd' => Some(CLASS_DIGIT.to_vec()),
            // Negated shorthand inside classes (`[\D]`) is unsupported;
            // such patterns compile to nothing instead.
            'D' | 'W' => None,
            'w' => Some(CLASS_WORD.to_vec()),
            's' => Some(vec![(' ', ' '), ('\t', '\t'), ('\n', '\r')]),
            't' => Some(vec![('\t', '\t')]),
            'n' => Some(vec![('\n', '\n')]),
            'r' => Some(vec![('\r', '\r')]),
            escaped => Some(vec![(escaped, escaped)]),
        }
    }

    pub(crate) fn parse_escape(&mut self) -> Option<RegexNode> {
        match self.bump()? {
            'd' => Some(RegexNode::Class {
                negated: false,
                ranges: CLASS_DIGIT.to_vec(),
            }),
            'D' => Some(RegexNode::Class {
                negated: true,
                ranges: CLASS_DIGIT.to_vec(),
            }),
            'w' => Some(RegexNode::Class {
                negated: false,
                ranges: CLASS_WORD.to_vec(),
            }),
            'W' => Some(RegexNode::Class {
                negated: true,
                ranges: CLASS_WORD.to_vec(),
            }),
            's' => Some(RegexNode::Class {
                negated: false,
                ranges: vec![(' ', ' '), ('\t', '\t'), ('\n', '\r')],
            }),
            'S' => Some(RegexNode::Class {
                negated: true,
                ranges: vec![(' ', ' '), ('\t', '\t'), ('\n', '\r')],
            }),
            escaped => Some(RegexNode::Char(escaped)),
        }
    }
}

/// Character-class shorthand escapes (`\d`, `\w`, `\s` and negations).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum ShorthandClass {
    Digit,
    Word,
    Space,
}

/// Zero-width assertions understood by the pattern parser.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum AnchorKind {
    Start,
    End,
    WordBoundary,
    NotWordBoundary,
}

/// Group headers the mini parser understands; anything else (`(?P`, …) is a
/// definite syntax error for `S5856`.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum GroupKind {
    Capturing,
    Named(String),
    NonCapturing,
    Lookahead { negated: bool },
    Lookbehind { negated: bool },
}

impl GroupKind {
    pub(crate) fn is_lookaround(&self) -> bool {
        matches!(self, Self::Lookahead { .. } | Self::Lookbehind { .. })
    }
}

/// One item inside a `[...]` character class.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum ClassItem {
    Char {
        ch: char,
        pos: usize,
    },
    Range {
        low: char,
        high: char,
        start: usize,
    },
    Shorthand {
        negated: bool,
        kind: ShorthandClass,
        pos: usize,
    },
    Property {
        negated: bool,
        pos: usize,
    },
}

/// One node of the mini regex-pattern tree. Positions are byte offsets into
/// the pattern text so findings can be anchored at the offending construct.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum PatternNode {
    Literal {
        ch: char,
        pos: usize,
    },
    Dot,
    Class {
        negated: bool,
        items: Vec<ClassItem>,
        start: usize,
        end: usize,
    },
    ClassEscape {
        negated: bool,
        kind: ShorthandClass,
        pos: usize,
    },
    PropertyEscape {
        negated: bool,
        pos: usize,
    },
    Anchor {
        kind: AnchorKind,
        pos: usize,
    },
    Group {
        kind: GroupKind,
        alternatives: Vec<Vec<PatternNode>>,
        start: usize,
        end: usize,
    },
    BackReference {
        pos: usize,
    },
    Quantified {
        node: Box<PatternNode>,
        min: u32,
        max: Option<u32>,
        greedy: bool,
        pos: usize,
        /// Verbatim source text of the quantifier (`{1}` vs `{1,1}`).
        verbose: String,
    },
}

/// Parse result of [`parse_regex_pattern`].
pub(crate) struct ParsedRegex {
    pub(crate) alternatives: Vec<Vec<PatternNode>>,
    /// Byte offsets of empty alternation branches with at least one
    /// non-empty sibling (`S6323`); wholly empty groups belong to `S6331`.
    pub(crate) empty_branch_positions: Vec<usize>,
    pub(crate) capture_count: usize,
    pub(crate) capture_names: Vec<String>,
}

/// Parses the literal-syntax subset of ECMAScript regex patterns. Returns
/// `Err` only for definite syntax errors — unbalanced parentheses,
/// unterminated character classes, quantifiers with nothing to repeat,
/// unknown `(?…)` headers, reversed class ranges, and malformed `\u`/`\x`
/// forms in unicode mode. Anything merely unfamiliar parses conservatively
/// so the walker never invents findings (tolerant, never panics).
pub(crate) fn parse_regex_pattern(pattern: &str, unicode_mode: bool) -> Result<ParsedRegex, ()> {
    let mut parser = PatternParser {
        source: pattern,
        chars: pattern.char_indices().collect(),
        pos: 0,
        captures: Vec::new(),
        unicode_mode,
        empty_branch_positions: Vec::new(),
    };
    let alternatives = parser.parse_alternatives(None)?;
    Ok(ParsedRegex {
        capture_count: parser.captures.len(),
        capture_names: parser.captures.iter().flatten().cloned().collect(),
        alternatives,
        empty_branch_positions: parser.empty_branch_positions,
    })
}

pub(crate) struct PatternParser<'p> {
    /// The raw pattern text, for verbatim quantifier slices.
    pub(crate) source: &'p str,
    pub(crate) chars: Vec<(usize, char)>,
    pub(crate) pos: usize,
    pub(crate) captures: Vec<Option<String>>,
    pub(crate) unicode_mode: bool,
    pub(crate) empty_branch_positions: Vec<usize>,
}

impl PatternParser<'_> {
    pub(crate) fn peek(&self) -> Option<char> {
        self.chars.get(self.pos).map(|&(_, ch)| ch)
    }

    pub(crate) fn bump(&mut self) -> Option<char> {
        let ch = self.peek()?;
        self.pos += 1;
        Some(ch)
    }

    pub(crate) fn current_offset(&self) -> usize {
        self.chars
            .get(self.pos)
            .map_or_else(|| self.end_offset(), |&(off, _)| off)
    }

    pub(crate) fn end_offset(&self) -> usize {
        self.chars
            .last()
            .map_or(0, |&(off, ch)| off + ch.len_utf8())
    }

    /// Alternation body of the whole pattern (`terminator: None`) or of one
    /// group (`terminator: Some(')')`, consumed here).
    pub(crate) fn parse_alternatives(
        &mut self,
        terminator: Option<char>,
    ) -> Result<Vec<Vec<PatternNode>>, ()> {
        let mut alternatives = Vec::new();
        let mut local_empties = Vec::new();
        loop {
            let branch_start = self.current_offset();
            let nodes = self.parse_sequence(terminator)?;
            if nodes.is_empty() {
                local_empties.push(branch_start);
            }
            alternatives.push(nodes);
            if self.peek() == Some('|') {
                self.pos += 1;
            } else {
                break;
            }
        }
        // A single empty branch is either an empty pattern (clean) or a
        // wholly empty group (`S6331`); neither belongs to `S6323`.
        if !(alternatives.len() == 1 && alternatives[0].is_empty()) {
            self.empty_branch_positions.extend(local_empties);
        }
        match terminator {
            None => {
                if self.pos != self.chars.len() {
                    return Err(()); // stray `)`
                }
            }
            Some(expected) => {
                if self.peek() != Some(expected) {
                    return Err(()); // unclosed group
                }
                self.pos += 1;
            }
        }
        Ok(alternatives)
    }

    pub(crate) fn parse_sequence(
        &mut self,
        terminator: Option<char>,
    ) -> Result<Vec<PatternNode>, ()> {
        let mut nodes: Vec<PatternNode> = Vec::new();
        loop {
            match self.peek() {
                None | Some('|') => break,
                Some(')') => {
                    if terminator == Some(')') {
                        break;
                    }
                    return Err(()); // unbalanced `)`
                }
                // A quantifier here has nothing to repeat: sequence start,
                // after `|`, after `(`, or stacked onto another quantifier.
                Some('*' | '+' | '?') => return Err(()),
                _ => {}
            }
            let atom = self.parse_atom()?;
            let quantifier_pos = self.current_offset();
            if let Some((min, max)) = self.try_parse_quantifier()? {
                let mut greedy = true;
                if self.peek() == Some('?') {
                    self.pos += 1;
                    greedy = false;
                }
                let verbose = self.source[quantifier_pos..self.current_offset()].to_string();
                nodes.push(PatternNode::Quantified {
                    node: Box::new(atom),
                    min,
                    max,
                    greedy,
                    pos: quantifier_pos,
                    verbose,
                });
            } else {
                nodes.push(atom);
            }
        }
        Ok(nodes)
    }

    /// `Ok(None)` when the upcoming text is not a quantifier (malformed
    /// braces stay literal characters, per Annex B); `Err` for a definite
    /// `{m,n}` reversal in unicode mode.
    pub(crate) fn try_parse_quantifier(&mut self) -> Result<Option<(u32, Option<u32>)>, ()> {
        match self.peek() {
            Some('*') => {
                self.pos += 1;
                Ok(Some((0, None)))
            }
            Some('+') => {
                self.pos += 1;
                Ok(Some((1, None)))
            }
            Some('?') => {
                self.pos += 1;
                Ok(Some((0, Some(1))))
            }
            Some('{') => self.try_parse_brace_quantifier(),
            _ => Ok(None),
        }
    }

    pub(crate) fn try_parse_brace_quantifier(&mut self) -> Result<Option<(u32, Option<u32>)>, ()> {
        let save = self.pos;
        self.pos += 1; // `{`
        let Some(min) = self.parse_decimal() else {
            self.pos = save;
            return Ok(None);
        };
        let max = match self.peek() {
            Some('}') => {
                self.pos += 1;
                Some(min)
            }
            Some(',') => {
                self.pos += 1;
                let max = self.parse_decimal();
                if self.peek() != Some('}') {
                    self.pos = save;
                    return Ok(None);
                }
                self.pos += 1;
                max
            }
            _ => {
                self.pos = save;
                return Ok(None);
            }
        };
        if let Some(max) = max
            && max < min
        {
            if self.unicode_mode {
                return Err(());
            }
            self.pos = save;
            return Ok(None);
        }
        Ok(Some((min, max)))
    }

    pub(crate) fn parse_decimal(&mut self) -> Option<u32> {
        let mut value: Option<u32> = None;
        while let Some(digit) = self.peek().and_then(|next| next.to_digit(10)) {
            value = Some(value.unwrap_or(0).saturating_mul(10).saturating_add(digit));
            self.pos += 1;
        }
        value
    }

    pub(crate) fn parse_atom(&mut self) -> Result<PatternNode, ()> {
        let Some(&(pos, ch)) = self.chars.get(self.pos) else {
            return Err(());
        };
        self.pos += 1;
        match ch {
            '.' => Ok(PatternNode::Dot),
            '^' => Ok(PatternNode::Anchor {
                kind: AnchorKind::Start,
                pos,
            }),
            '$' => Ok(PatternNode::Anchor {
                kind: AnchorKind::End,
                pos,
            }),
            '[' => self.parse_class(pos),
            '(' => self.parse_group(pos),
            '\\' => self.parse_escape(pos),
            _ => Ok(PatternNode::Literal { ch, pos }),
        }
    }

    pub(crate) fn parse_group(&mut self, start: usize) -> Result<PatternNode, ()> {
        let kind = if self.peek() == Some('?') {
            self.pos += 1;
            match self.peek() {
                Some(':') => {
                    self.pos += 1;
                    GroupKind::NonCapturing
                }
                Some('=') => {
                    self.pos += 1;
                    GroupKind::Lookahead { negated: false }
                }
                Some('!') => {
                    self.pos += 1;
                    GroupKind::Lookahead { negated: true }
                }
                Some('<') => {
                    self.pos += 1;
                    match self.peek() {
                        Some('=') => {
                            self.pos += 1;
                            GroupKind::Lookbehind { negated: false }
                        }
                        Some('!') => {
                            self.pos += 1;
                            GroupKind::Lookbehind { negated: true }
                        }
                        _ => {
                            let name = self.parse_group_name()?;
                            self.captures.push(Some(name.clone()));
                            GroupKind::Named(name)
                        }
                    }
                }
                _ => return Err(()), // unknown `(?…)` header
            }
        } else {
            self.captures.push(None);
            GroupKind::Capturing
        };
        let alternatives = self.parse_alternatives(Some(')'))?;
        Ok(PatternNode::Group {
            kind,
            alternatives,
            start,
            end: self.end_offset(),
        })
    }

    pub(crate) fn parse_group_name(&mut self) -> Result<String, ()> {
        let mut name = String::new();
        loop {
            match self.bump() {
                None | Some('(' | '|') => return Err(()),
                Some('>') => break,
                Some(ch) => name.push(ch),
            }
        }
        if name.is_empty() {
            return Err(());
        }
        Ok(name)
    }

    pub(crate) fn parse_escape(&mut self, backslash_pos: usize) -> Result<PatternNode, ()> {
        let Some(&(char_pos, ch)) = self.chars.get(self.pos) else {
            return Err(()); // trailing backslash
        };
        self.pos += 1;
        match ch {
            'd' | 'D' | 'w' | 'W' | 's' | 'S' => {
                let (negated, kind) = match ch {
                    'D' => (true, ShorthandClass::Digit),
                    'W' => (true, ShorthandClass::Word),
                    'S' => (true, ShorthandClass::Space),
                    'd' => (false, ShorthandClass::Digit),
                    'w' => (false, ShorthandClass::Word),
                    _ => (false, ShorthandClass::Space),
                };
                Ok(PatternNode::ClassEscape {
                    negated,
                    kind,
                    pos: backslash_pos,
                })
            }
            'p' | 'P' => match self.peek() {
                Some('{') => {
                    self.skip_property_body()?;
                    Ok(PatternNode::PropertyEscape {
                        negated: ch == 'P',
                        pos: backslash_pos,
                    })
                }
                None => Err(()),
                Some(_) if self.unicode_mode => Err(()),
                Some(_) => Ok(PatternNode::Literal { ch, pos: char_pos }),
            },
            'b' => Ok(PatternNode::Anchor {
                kind: AnchorKind::WordBoundary,
                pos: backslash_pos,
            }),
            'B' => Ok(PatternNode::Anchor {
                kind: AnchorKind::NotWordBoundary,
                pos: backslash_pos,
            }),
            '1'..='9' => {
                while self.peek().is_some_and(|next| next.is_ascii_digit()) {
                    self.pos += 1;
                }
                Ok(PatternNode::BackReference { pos: backslash_pos })
            }
            'k' if self.peek() == Some('<') => {
                self.pos += 1;
                self.parse_group_name()?;
                Ok(PatternNode::BackReference { pos: backslash_pos })
            }
            'n' => Ok(PatternNode::Literal {
                ch: '\n',
                pos: char_pos,
            }),
            't' => Ok(PatternNode::Literal {
                ch: '\t',
                pos: char_pos,
            }),
            'r' => Ok(PatternNode::Literal {
                ch: '\r',
                pos: char_pos,
            }),
            'f' => Ok(PatternNode::Literal {
                ch: '\u{000C}',
                pos: char_pos,
            }),
            'v' => Ok(PatternNode::Literal {
                ch: '\u{000B}',
                pos: char_pos,
            }),
            '0' => Ok(PatternNode::Literal {
                ch: '\0',
                pos: char_pos,
            }),
            'u' if self.unicode_mode => Ok(PatternNode::Literal {
                ch: self.parse_unicode_escape()?,
                pos: char_pos,
            }),
            'x' if self.unicode_mode => Ok(PatternNode::Literal {
                ch: self.parse_hex_escape(2)?,
                pos: char_pos,
            }),
            'c' if self.unicode_mode => match self.peek() {
                Some(letter) if letter.is_ascii_alphabetic() => {
                    self.pos += 1;
                    Ok(PatternNode::Literal {
                        ch: (letter.to_ascii_uppercase() as u8 ^ 0x40) as char,
                        pos: char_pos,
                    })
                }
                _ => Err(()),
            },
            _ => Ok(PatternNode::Literal { ch, pos: char_pos }),
        }
    }

    /// `\u{HexDigits}` or `\uHHHH` in unicode mode; `u` already consumed.
    pub(crate) fn parse_unicode_escape(&mut self) -> Result<char, ()> {
        if self.peek() == Some('{') {
            self.pos += 1;
            let mut value: u32 = 0;
            let mut digits = 0;
            while let Some(next) = self.peek()
                && next != '}'
            {
                let Some(nibble) = next.to_digit(16) else {
                    return Err(());
                };
                value = value.saturating_mul(16).saturating_add(nibble);
                digits += 1;
                self.pos += 1;
            }
            if digits == 0 || digits > 6 || self.bump() != Some('}') {
                return Err(());
            }
            char::from_u32(value).ok_or(())
        } else {
            self.parse_hex_escape(4)
        }
    }

    /// Exactly `count` hex digits in unicode mode; `x`/`u` already consumed.
    pub(crate) fn parse_hex_escape(&mut self, count: usize) -> Result<char, ()> {
        let mut value: u32 = 0;
        for _ in 0..count {
            let nibble = self.peek().and_then(|next| next.to_digit(16)).ok_or(())?;
            value = value.saturating_mul(16).saturating_add(nibble);
            self.pos += 1;
        }
        char::from_u32(value).ok_or(())
    }

    pub(crate) fn skip_property_body(&mut self) -> Result<(), ()> {
        self.pos += 1; // `{`
        loop {
            match self.bump() {
                None | Some('(' | '|') => return Err(()),
                Some('}') => return Ok(()),
                Some(_) => {}
            }
        }
    }

    pub(crate) fn parse_class(&mut self, start: usize) -> Result<PatternNode, ()> {
        let negated = if self.peek() == Some('^') {
            self.pos += 1;
            true
        } else {
            false
        };
        let mut items = Vec::new();
        loop {
            let Some(&(item_pos, ch)) = self.chars.get(self.pos) else {
                return Err(()); // unterminated class
            };
            if ch == ']' {
                self.pos += 1;
                break;
            }
            let item = self.parse_class_item(item_pos, ch)?;
            if let ClassItem::Char {
                ch: low,
                pos: low_pos,
            } = item
                && let Some(range) = self.try_parse_class_range(low, low_pos)?
            {
                items.push(range);
            } else {
                items.push(item);
            }
        }
        Ok(PatternNode::Class {
            negated,
            items,
            start,
            end: self.end_offset(),
        })
    }

    /// Extends a lone class char into `low-high` when a dash and a further
    /// single char follow; otherwise rewinds so `-` stays literal.
    pub(crate) fn try_parse_class_range(
        &mut self,
        low: char,
        low_pos: usize,
    ) -> Result<Option<ClassItem>, ()> {
        if self.peek() != Some('-') {
            return Ok(None);
        }
        let save = self.pos;
        self.pos += 1; // `-`
        let Some(&(high_pos, high_ch)) = self.chars.get(self.pos) else {
            self.pos = save;
            return Ok(None);
        };
        if high_ch == ']' {
            self.pos = save;
            return Ok(None);
        }
        let ClassItem::Char { ch: high, .. } = self.parse_class_item(high_pos, high_ch)? else {
            // `a-\d`: Annex B keeps the dash literal; rewind and let the
            // shorthand be parsed as its own item.
            self.pos = save;
            return Ok(None);
        };
        if high < low {
            return Err(()); // reversed range
        }
        Ok(Some(ClassItem::Range {
            low,
            high,
            start: low_pos,
        }))
    }

    pub(crate) fn parse_class_item(&mut self, pos: usize, ch: char) -> Result<ClassItem, ()> {
        if ch != '\\' {
            self.pos += 1;
            return Ok(ClassItem::Char { ch, pos });
        }
        self.pos += 1; // backslash
        let Some(&(char_pos, esc)) = self.chars.get(self.pos) else {
            return Err(()); // trailing backslash
        };
        self.pos += 1;
        Ok(match esc {
            'd' => ClassItem::Shorthand {
                negated: false,
                kind: ShorthandClass::Digit,
                pos,
            },
            'D' => ClassItem::Shorthand {
                negated: true,
                kind: ShorthandClass::Digit,
                pos,
            },
            'w' => ClassItem::Shorthand {
                negated: false,
                kind: ShorthandClass::Word,
                pos,
            },
            'W' => ClassItem::Shorthand {
                negated: true,
                kind: ShorthandClass::Word,
                pos,
            },
            's' => ClassItem::Shorthand {
                negated: false,
                kind: ShorthandClass::Space,
                pos,
            },
            'S' => ClassItem::Shorthand {
                negated: true,
                kind: ShorthandClass::Space,
                pos,
            },
            'p' | 'P' => match self.peek() {
                Some('{') => {
                    self.skip_property_body()?;
                    ClassItem::Property {
                        negated: esc == 'P',
                        pos,
                    }
                }
                None => return Err(()),
                Some(_) if self.unicode_mode => return Err(()),
                Some(_) => ClassItem::Char {
                    ch: esc,
                    pos: char_pos,
                },
            },
            'b' => ClassItem::Char {
                ch: '\u{0008}',
                pos: char_pos,
            },
            'n' => ClassItem::Char {
                ch: '\n',
                pos: char_pos,
            },
            't' => ClassItem::Char {
                ch: '\t',
                pos: char_pos,
            },
            'r' => ClassItem::Char {
                ch: '\r',
                pos: char_pos,
            },
            'f' => ClassItem::Char {
                ch: '\u{000C}',
                pos: char_pos,
            },
            'v' => ClassItem::Char {
                ch: '\u{000B}',
                pos: char_pos,
            },
            '0' => ClassItem::Char {
                ch: '\0',
                pos: char_pos,
            },
            'u' if self.unicode_mode => ClassItem::Char {
                ch: self.parse_unicode_escape()?,
                pos: char_pos,
            },
            'x' if self.unicode_mode => ClassItem::Char {
                ch: self.parse_hex_escape(2)?,
                pos: char_pos,
            },
            _ => ClassItem::Char {
                ch: esc,
                pos: char_pos,
            },
        })
    }
}

/// Whether a sequence can match the empty string.
pub(crate) fn sequence_can_match_empty(sequence: &[PatternNode]) -> bool {
    sequence.iter().all(node_can_match_empty)
}

/// Whether one node can match the empty string; lookarounds and anchors are
/// zero-width, groups when any alternative is empty-capable.
pub(crate) fn node_can_match_empty(node: &PatternNode) -> bool {
    match node {
        PatternNode::Anchor { .. } => true,
        PatternNode::Group {
            kind, alternatives, ..
        } => {
            kind.is_lookaround()
                || alternatives
                    .iter()
                    .any(|alternative| sequence_can_match_empty(alternative))
        }
        PatternNode::Quantified { min, node, .. } => *min == 0 || node_can_match_empty(node),
        _ => false,
    }
}

/// Pre-order traversal of the pattern tree behind `sequence`.
pub(crate) fn walk_pattern_nodes(sequence: &[PatternNode], visit: &mut dyn FnMut(&PatternNode)) {
    for node in sequence {
        visit(node);
        match node {
            PatternNode::Group { alternatives, .. } => {
                for alternative in alternatives {
                    walk_pattern_nodes(alternative, visit);
                }
            }
            PatternNode::Quantified { node: inner, .. } => {
                walk_pattern_nodes(std::slice::from_ref(inner.as_ref()), visit);
            }
            _ => {}
        }
    }
}

/// Documented subset approximation of the `S5843` complexity score:
/// literals/dots/anchors cost 1, shorthands 2, backreferences 2, property
/// escapes 3, classes `2 + items`, groups 2 (lookarounds 4) plus their
/// body, quantifiers 2 plus their target, and each additional alternation
/// branch costs 1.
pub(crate) fn pattern_complexity(alternatives: &[Vec<PatternNode>]) -> u32 {
    let extra_branches = alternatives.len().saturating_sub(1);
    alternatives
        .iter()
        .map(|alternative| alternative.iter().map(node_complexity).sum::<u32>())
        .sum::<u32>()
        .saturating_add(to_u32(extra_branches))
}

pub(crate) fn node_complexity(node: &PatternNode) -> u32 {
    match node {
        PatternNode::Literal { .. } | PatternNode::Dot | PatternNode::Anchor { .. } => 1,
        PatternNode::BackReference { .. } | PatternNode::ClassEscape { .. } => 2,
        PatternNode::PropertyEscape { .. } => 3,
        PatternNode::Class { items, .. } => 2u32.saturating_add(to_u32(items.len())),
        PatternNode::Group {
            kind, alternatives, ..
        } => {
            let base: u32 = if kind.is_lookaround() { 4 } else { 2 };
            base.saturating_add(pattern_complexity(alternatives))
        }
        PatternNode::Quantified { node, .. } => 2u32.saturating_add(node_complexity(node)),
    }
}

// ----- Regex-site plumbing -----

/// One constant regex found in the AST: a regex literal or a `RegExp`
/// constructor call whose arguments are all literals. Pattern rules run the
/// shared mini walker over the pattern text; nothing is executed.
pub(crate) struct RegexSite {
    /// Fallback span for findings whose exact pattern offset is unknown
    /// (constructor-form offsets hide behind string escapes).
    pub(crate) span: Span,
    /// Source byte offset of `pattern[0]`; reliable only when
    /// [`RegexSite::exact`] holds.
    pub(crate) pattern_base: u32,
    /// Whether `pattern_base` maps pattern byte offsets exactly onto source.
    pub(crate) exact: bool,
    pub(crate) pattern: String,
    pub(crate) flags: String,
}

impl RegexSite {
    pub(crate) fn sub_span(&self, start: usize, end: usize) -> Span {
        if self.exact {
            Span::new(
                self.pattern_base.saturating_add(to_u32(start)),
                self.pattern_base.saturating_add(to_u32(end)),
            )
        } else {
            self.span
        }
    }

    pub(crate) fn whole_pattern_span(&self) -> Span {
        self.sub_span(0, self.pattern.len())
    }

    pub(crate) fn has_flag(&self, flag: char) -> bool {
        self.flags.contains(flag)
    }
}

/// Builds a site from a regex literal; its pattern text sits verbatim
/// between the slashes, so sub-spans are exact.
pub(crate) fn regex_site_from_literal(literal: &RegExpLiteral<'_>) -> RegexSite {
    RegexSite {
        span: literal.span,
        pattern_base: literal.span.start.saturating_add(1),
        exact: true,
        pattern: literal.regex.pattern.text.as_str().to_string(),
        flags: regex_flags_text(literal.regex.flags),
    }
}

/// Literal-form flags in canonical order; the constructor form keeps its
/// raw flags string instead.
pub(crate) fn regex_flags_text(flags: RegExpFlags) -> String {
    const ORDERED: [(RegExpFlags, char); 8] = [
        (RegExpFlags::G, 'g'),
        (RegExpFlags::I, 'i'),
        (RegExpFlags::M, 'm'),
        (RegExpFlags::S, 's'),
        (RegExpFlags::U, 'u'),
        (RegExpFlags::Y, 'y'),
        (RegExpFlags::D, 'd'),
        (RegExpFlags::V, 'v'),
    ];
    ORDERED
        .iter()
        .filter(|&(flag, _)| flags.contains(*flag))
        .map(|&(_, ch)| ch)
        .collect()
}

/// String value of a constant literal argument: a string literal or a
/// substitution-free template literal.
pub(crate) fn literal_string_value(argument: &oxc_ast::ast::Argument<'_>) -> Option<String> {
    match argument.as_expression()? {
        Expression::StringLiteral(string) => Some(string.value.as_str().to_string()),
        Expression::TemplateLiteral(template) if template.expressions.is_empty() => template
            .quasis
            .first()
            .and_then(|element| element.value.cooked.as_ref())
            .map(|atom| atom.as_str().to_string()),
        _ => None,
    }
}

/// Builds a site from `new RegExp(pattern, flags?)` / `RegExp(pattern,
/// flags?)` when every argument is a constant literal. Offsets inside
/// escaped strings are unreliable, so findings anchor at the argument span.
pub(crate) fn constructor_regex_site(
    arguments: &[oxc_ast::ast::Argument<'_>],
) -> Option<RegexSite> {
    let values: Vec<Option<String>> = arguments.iter().map(literal_string_value).collect();
    let pattern = values.first()?.clone()?;
    let flags = values.get(1).cloned().flatten().unwrap_or_default();
    Some(RegexSite {
        span: arguments.first()?.span(),
        pattern_base: 0,
        exact: false,
        pattern,
        flags,
    })
}

/// The regex literal behind an optional call argument, if it is one.
pub(crate) fn regex_literal_argument<'a>(
    argument: Option<&'a oxc_ast::ast::Argument<'a>>,
) -> Option<&'a oxc_ast::ast::RegExpLiteral<'a>> {
    match argument?.as_expression()? {
        Expression::RegExpLiteral(literal) => Some(literal),
        _ => None,
    }
}

/// Grapheme components that silently truncate inside a character class.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum GraphemeComponentKind {
    CombiningMark,
    JoinSequence,
    ModifiedEmoji,
    RegionalIndicator,
}

pub(crate) fn grapheme_component_kind(ch: char) -> Option<GraphemeComponentKind> {
    let kind = match ch {
        '\u{0300}'..='\u{036F}'
        | '\u{1AB0}'..='\u{1AFF}'
        | '\u{1DC0}'..='\u{1DFF}'
        | '\u{20D0}'..='\u{20F0}'
        | '\u{FE20}'..='\u{FE2F}' => GraphemeComponentKind::CombiningMark,
        '\u{200D}' => GraphemeComponentKind::JoinSequence,
        '\u{FE00}'..='\u{FE0F}' | '\u{1F3FB}'..='\u{1F3FF}' => GraphemeComponentKind::ModifiedEmoji,
        '\u{1F1E6}'..='\u{1F1FF}' => GraphemeComponentKind::RegionalIndicator,
        _ => return None,
    };
    Some(kind)
}

pub(crate) fn contains_unbounded_quantifier(node: &PatternNode) -> bool {
    match node {
        PatternNode::Quantified { max: None, .. } => true,
        PatternNode::Quantified { node: inner, .. } => contains_unbounded_quantifier(inner),
        PatternNode::Group { alternatives, .. } => alternatives
            .iter()
            .flatten()
            .any(contains_unbounded_quantifier),
        _ => false,
    }
}

// ----- Context-sensitive family members -----

/// One `$n` / `$<name>` reference found in a replacement string.
#[derive(Debug, Clone, PartialEq, Eq)]
pub(crate) enum GroupReference {
    Index(u32),
    Name(String),
}
