// Generated by jsts_split.py - part of the per-rule refactor.
use crate::support::{
    IssueSink, RuleScope, binding_identifier_name, identifier_name, member_object,
    property_key_name, source_slice, static_property_name, unparenthesized,
};
use oxc_ast::ast::{
    ArrowFunctionBody, ArrowFunctionExpression, AssignmentExpression, AssignmentOperator,
    AssignmentTarget, BinaryExpression, BinaryOperator, BindingIdentifier, BindingPattern,
    BlockStatement, BreakStatement, CallExpression, CatchClause, Class, ClassElement,
    ConditionalExpression, ContinueStatement, Declaration, DoWhileStatement,
    ExportDefaultDeclarationKind, ExportSpecifier, Expression, ForInStatement, ForOfStatement,
    ForStatement, FormalParameters, Function, IfStatement, ImportDeclaration,
    ImportDeclarationSpecifier, MemberExpression, MethodDefinition, MethodDefinitionKind,
    ModuleExportName, NewExpression, ReturnStatement, SimpleAssignmentTarget, Statement,
    StaticBlock, SwitchStatement, ThrowStatement, TryStatement, UnaryExpression, UnaryOperator,
    UpdateExpression, VariableDeclaration, VariableDeclarationKind, VariableDeclarator,
    WhileStatement,
};
use oxc_ast_visit::Visit;
use oxc_ast_visit::walk::{
    walk_arrow_function_expression, walk_binary_expression, walk_block_statement,
    walk_call_expression, walk_catch_clause, walk_class, walk_declaration,
    walk_export_default_declaration, walk_expression, walk_for_in_statement, walk_for_of_statement,
    walk_for_statement, walk_function, walk_method_definition, walk_new_expression, walk_program,
    walk_return_statement, walk_static_block, walk_switch_statement, walk_unary_expression,
    walk_variable_declaration, walk_variable_declarator,
};
use oxc_span::{GetSpan, Span};
use oxc_syntax::scope::ScopeFlags;
use std::collections::{BTreeMap, BTreeSet, HashMap};

/// Parameter names of named function declarations, for the `S2234` name
/// heuristic.
#[derive(Default)]
pub(crate) struct FunctionParamMapCollector {
    pub(crate) params_by_name: BTreeMap<String, Vec<String>>,
}

impl<'a> Visit<'a> for FunctionParamMapCollector {
    fn visit_declaration(&mut self, it: &Declaration<'a>) {
        if let Declaration::FunctionDeclaration(function) = it
            && let Some(id) = &function.id
        {
            let names: Vec<String> = function
                .params
                .items
                .iter()
                .filter_map(|item| binding_identifier_name(&item.pattern))
                .map(str::to_string)
                .collect();
            self.params_by_name.insert(id.name.to_string(), names);
        }
        walk_declaration(self, it);
    }
}

/// Names bound directly to an array literal anywhere in the file, for the
/// `S4619` heuristic (`const xs = []; ... x in xs`).
pub(crate) fn collect_array_binding_names(program: &oxc_ast::ast::Program<'_>) -> BTreeSet<String> {
    #[derive(Default)]
    struct Collector {
        names: BTreeSet<String>,
    }
    impl<'a> Visit<'a> for Collector {
        fn visit_variable_declarator(&mut self, it: &VariableDeclarator<'a>) {
            if matches!(&it.init, Some(Expression::ArrayExpression(_)))
                && let Some(name) = binding_identifier_name(&it.id)
            {
                self.names.insert(name.to_string());
            }
        }
    }
    let mut collector = Collector::default();
    collector.visit_program(program);
    collector.names
}

/// Names of a parameter list's simple identifiers.
pub(crate) fn parameter_names<'a>(params: &'a oxc_ast::ast::FormalParameters<'a>) -> Vec<&'a str> {
    params
        .items
        .iter()
        .filter_map(|item| binding_identifier_name(&item.pattern))
        .collect()
}

/// Body span of a function-valued expression, if it has one.
pub(crate) fn function_body_span(expression: &Expression<'_>) -> Option<Span> {
    match unparenthesized(expression) {
        Expression::FunctionExpression(function) => {
            function.body.as_deref().map(oxc_span::GetSpan::span)
        }
        Expression::ArrowFunctionExpression(arrow) => Some(arrow.body.span()),
        _ => None,
    }
}

/// Parameter list of a function-valued expression, if it has one.
pub(crate) fn function_parameters<'a>(
    expression: &'a Expression<'a>,
) -> Option<&'a oxc_ast::ast::FormalParameters<'a>> {
    match unparenthesized(expression) {
        Expression::FunctionExpression(function) => Some(&function.params),
        Expression::ArrowFunctionExpression(arrow) => Some(&arrow.params),
        _ => None,
    }
}

// ===========================================================================
// Tier B — file-local scope/symbol table
//
// One traversal records declarations plus every identifier event together
// with a snapshot of the active scope chain. Resolution is deferred until the
// walk finishes: lexical scoping ignores textual order, so a reference that
// precedes its declaration must still resolve to it (use-before-definition
// rules depend on exactly that).

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum TbKind {
    Var,
    Let,
    Const,
    Function,
    Class,
    Param,
    CatchParam,
    Import,
}

impl TbKind {
    /// Bindings `javascript:S1481` may flag as unused locals.
    pub(crate) fn is_local_value(self) -> bool {
        matches!(
            self,
            Self::Var | Self::Let | Self::Const | Self::Function | Self::Class
        )
    }
}

pub(crate) struct TbBinding<'a> {
    pub(crate) name: &'a str,
    pub(crate) kind: TbKind,
    /// Span of the declared name (declarator id, parameter, import local).
    pub(crate) decl: Span,
    pub(crate) reads: Vec<Span>,
    pub(crate) writes: Vec<Span>,
    /// For `var` declared inside a nested block: the innermost enclosing
    /// block span (`javascript:S2392`).
    pub(crate) home_block: Option<Span>,
    /// Signature shape when this binding names a function declaration
    /// (`javascript:S930` / `S4623`).
    pub(crate) arity: Option<TbSignature>,
    /// Declared at program/module top level (`S1481` exempts globals).
    pub(crate) global: bool,
    /// Initialized from an array literal (`javascript:S2870`).
    pub(crate) array_like: bool,
}

/// Aggregated shape of one function signature.
pub(crate) struct TbSignature {
    pub(crate) minimum: usize,
    pub(crate) maximum: Option<usize>,
    pub(crate) optional: Vec<usize>,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum TbScopeKind {
    Program,
    Function,
    Block,
}

pub(crate) struct TbScope {
    pub(crate) parent: Option<usize>,
    pub(crate) kind: TbScopeKind,
    pub(crate) span: Span,
    pub(crate) bindings: Vec<usize>,
}

/// One identifier occurrence awaiting resolution.
pub(crate) struct TbEvent<'a> {
    pub(crate) name: &'a str,
    pub(crate) span: Span,
    pub(crate) write: bool,
    /// Compound assignments (`+=`) and updates read as well as write.
    pub(crate) compound: bool,
    pub(crate) chain: Vec<usize>,
}

/// A resolved callee position (`call`/`new` of a file-local binding).
pub(crate) struct TbCallee<'a> {
    pub(crate) name: &'a str,
    pub(crate) span: Span,
    pub(crate) arity: usize,
    pub(crate) constructor: bool,
    pub(crate) chain: Vec<usize>,
    /// Argument positions spelled as bare `undefined` (`S4623`).
    pub(crate) explicit_undefined: Vec<usize>,
    /// Any spread argument disables positional matching.
    pub(crate) spread: bool,
}

/// A name occurrence awaiting lexical resolution (`delete X…`, `S2870`).
pub(crate) struct TbSite<'a> {
    pub(crate) name: &'a str,
    pub(crate) span: Span,
    pub(crate) chain: Vec<usize>,
}

pub(crate) struct TbCallSite {
    pub(crate) binding: usize,
    pub(crate) span: Span,
    pub(crate) arity: usize,
    pub(crate) explicit_undefined: Vec<usize>,
    pub(crate) spread: bool,
}

/// Model produced by [`build_tb_model`]; indexes are stable for the run.
pub(crate) struct TbModel<'a> {
    pub(crate) scopes: Vec<TbScope>,
    pub(crate) bindings: Vec<TbBinding<'a>>,
    pub(crate) events: Vec<TbEvent<'a>>,
    pub(crate) callees: Vec<TbCallee<'a>>,
    pub(crate) delete_sites: Vec<TbSite<'a>>,
    /// `(outer binding, inner declaration)` shadow chains (`S1117`).
    pub(crate) shadows: Vec<(usize, usize)>,
    /// `(first declaration, second declaration, name)` same-scope
    /// `var`/function duplicates (`S2814`, JS only).
    pub(crate) duplicates: Vec<(Span, Span, &'a str)>,
    /// Writes to names never declared anywhere (`S2703`, JS only).
    pub(crate) implicit_globals: Vec<(&'a str, Span)>,
    pub(crate) calls: Vec<TbCallSite>,
    /// `(binding, span)` of `new` sites resolving file-locally (`S3686`).
    pub(crate) news: Vec<(usize, Span)>,
    /// Resolved `delete` targets whose base is array-like.
    pub(crate) array_deletes: Vec<(usize, Span)>,
}

impl TbModel<'_> {
    pub(crate) fn shallow(&self, scope: usize, name: &str) -> Option<usize> {
        self.scopes[scope]
            .bindings
            .iter()
            .copied()
            .find(|id| self.bindings[*id].name == name)
    }

    pub(crate) fn resolve_chain(&self, chain: &[usize], name: &str) -> Option<usize> {
        chain
            .iter()
            .rev()
            .find_map(|scope| self.shallow(*scope, name))
    }
}

/// Distributes recorded events onto bindings once all declarations exist,
/// then derives shadow chains and same-scope duplicates.
pub(crate) fn finish_model(mut model: TbModel<'_>) -> TbModel<'_> {
    for event in std::mem::take(&mut model.events) {
        if let Some(id) = model.resolve_chain(&event.chain, event.name) {
            let binding = &mut model.bindings[id];
            if event.write {
                binding.writes.push(event.span);
            }
            if !event.write || event.compound {
                binding.reads.push(event.span);
            }
        } else if event.write {
            model.implicit_globals.push((event.name, event.span));
        }
    }
    for callee in std::mem::take(&mut model.callees) {
        if let Some(id) = model.resolve_chain(&callee.chain, callee.name) {
            let site = TbCallSite {
                binding: id,
                span: callee.span,
                arity: callee.arity,
                explicit_undefined: callee.explicit_undefined,
                spread: callee.spread,
            };
            if callee.constructor {
                model.news.push((id, callee.span));
            } else {
                model.calls.push(site);
            }
        }
    }
    for site in std::mem::take(&mut model.delete_sites) {
        if let Some(id) = model.resolve_chain(&site.chain, site.name)
            && model.bindings[id].array_like
        {
            model.array_deletes.push((id, site.span));
        }
    }
    for scope in 0..model.scopes.len() {
        let ids = model.scopes[scope].bindings.clone();
        for &id in &ids {
            let mut cursor = model.scopes[scope].parent;
            let mut shadowed = None;
            while let Some(ancestor) = cursor {
                if let Some(outer) = model.shallow(ancestor, model.bindings[id].name) {
                    shadowed = Some(outer);
                    break;
                }
                cursor = model.scopes[ancestor].parent;
            }
            if let Some(outer) = shadowed {
                model.shadows.push((outer, id));
            }
        }
        for (i, &left) in ids.iter().enumerate() {
            for &right in ids.iter().skip(i + 1) {
                let (a, b) = (&model.bindings[left], &model.bindings[right]);
                let duplicate_kinds = |kind| matches!(kind, TbKind::Var | TbKind::Function);
                if a.name == b.name && duplicate_kinds(a.kind) && duplicate_kinds(b.kind) {
                    model.duplicates.push((a.decl, b.decl, a.name));
                }
            }
        }
    }
    model
}

/// Builds the [`TbModel`] in one `Visit` pass. Writes versus reads are told
/// apart by an assignment/update depth guard: the default walk funnels both
/// assignment-target identifiers and ordinary references through
/// `visit_identifier_reference`.
pub(crate) struct TbBuilder<'a, 'm> {
    pub(crate) model: &'m mut TbModel<'a>,
    pub(crate) stack: Vec<usize>,
    pub(crate) write_depth: u32,
    pub(crate) compound: bool,
    pub(crate) skip_parameters: bool,
    /// Kind of the variable declaration currently being walked.
    pub(crate) pending_kind: TbKind,
}

impl<'a> TbBuilder<'a, '_> {
    pub(crate) fn push_scope(&mut self, kind: TbScopeKind, span: Span) {
        let parent = self.stack.last().copied();
        self.model.scopes.push(TbScope {
            parent,
            kind,
            span,
            bindings: Vec::new(),
        });
        self.stack.push(self.model.scopes.len() - 1);
    }

    pub(crate) fn pop_scope(&mut self) {
        self.stack.pop();
    }

    pub(crate) fn declare(&mut self, name: &'a str, kind: TbKind, decl: Span) -> usize {
        let target = match kind {
            // `var` hoists to the nearest function/program boundary; imports
            // always live at module top level.
            TbKind::Var => self.nearest_function_scope(),
            TbKind::Import => 0,
            _ => *self.stack.last().expect("scope stack is never empty"),
        };
        let home_block = match kind {
            TbKind::Var => self.home_block(),
            _ => None,
        };
        let global = self.model.scopes[target].kind == TbScopeKind::Program;
        let id = self.model.bindings.len();
        self.model.bindings.push(TbBinding {
            name,
            kind,
            decl,
            reads: Vec::new(),
            writes: Vec::new(),
            home_block,
            arity: None,
            global,
            array_like: false,
        });
        self.model.scopes[target].bindings.push(id);
        id
    }

    pub(crate) fn nearest_function_scope(&self) -> usize {
        self.stack
            .iter()
            .rev()
            .find(|s| self.model.scopes[**s].kind != TbScopeKind::Block)
            .copied()
            .unwrap_or(0)
    }

    /// Innermost enclosing block above the nearest function boundary — the
    /// home of a hoisted `var`, used by `S2392`.
    pub(crate) fn home_block(&self) -> Option<Span> {
        self.stack.iter().rev().find_map(|scope| {
            let scope = &self.model.scopes[*scope];
            match scope.kind {
                TbScopeKind::Block => Some(scope.span),
                TbScopeKind::Program | TbScopeKind::Function => None,
            }
        })
    }

    pub(crate) fn record_reference(&mut self, name: &'a str, span: Span) {
        self.model.events.push(TbEvent {
            name,
            span,
            write: self.write_depth > 0,
            compound: self.compound,
            chain: self.stack.clone(),
        });
    }

    pub(crate) fn record_callee(
        &mut self,
        expression: &Expression<'a>,
        arguments: &[oxc_ast::ast::Argument<'a>],
        constructor: bool,
    ) {
        let Expression::Identifier(reference) = unparenthesized(expression) else {
            return;
        };
        let mut explicit_undefined = Vec::new();
        let mut spread = false;
        for (position, argument) in arguments.iter().enumerate() {
            match argument.as_expression() {
                None => spread = true,
                Some(expression) => {
                    if let Expression::Identifier(name) = unparenthesized(expression)
                        && name.name == "undefined"
                    {
                        explicit_undefined.push(position);
                    }
                }
            }
        }
        self.model.callees.push(TbCallee {
            name: reference.name.as_str(),
            span: reference.span,
            arity: arguments.len(),
            constructor,
            chain: self.stack.clone(),
            explicit_undefined,
            spread,
        });
    }

    /// `delete x[i]` on an array-like binding (`S2870`).
    pub(crate) fn record_delete(&mut self, unary: &UnaryExpression<'a>) {
        if unary.operator != UnaryOperator::Delete {
            return;
        }
        if let Some(member) = unary.argument.as_member_expression()
            && let Expression::Identifier(object) = member_object(member)
        {
            self.model.delete_sites.push(TbSite {
                name: object.name.as_str(),
                span: unary.span,
                chain: self.stack.clone(),
            });
        }
    }

    pub(crate) fn declare_pattern(&mut self, pattern: &BindingPattern<'a>, kind: TbKind) {
        match pattern {
            BindingPattern::BindingIdentifier(identifier) => {
                self.declare(identifier.name.as_str(), kind, identifier.span);
            }
            BindingPattern::ObjectPattern(object) => {
                for property in &object.properties {
                    self.declare_pattern(&property.value, kind);
                }
                if let Some(rest) = &object.rest {
                    self.declare_pattern(&rest.argument, kind);
                }
            }
            BindingPattern::ArrayPattern(array) => {
                for element in array.elements.iter().flatten() {
                    self.declare_pattern(element, kind);
                }
                if let Some(rest) = &array.rest {
                    self.declare_pattern(&rest.argument, kind);
                }
            }
            BindingPattern::AssignmentPattern(assignment) => {
                self.declare_pattern(&assignment.left, kind);
            }
        }
    }

    pub(crate) fn declare_parameters(&mut self, parameters: &oxc_ast::ast::FormalParameters<'a>) {
        if self.skip_parameters {
            return;
        }
        for parameter in &parameters.items {
            // TypeScript parameter properties assign `this.x` implicitly;
            // they are never plain local parameters.
            if parameter.accessibility.is_none() && !parameter.readonly {
                self.declare_pattern(&parameter.pattern, TbKind::Param);
            }
        }
    }

    /// `for (let v of xs)` assigns `v` although no assignment node exists.
    pub(crate) fn mark_loop_bindings(&mut self, declaration: &VariableDeclaration<'a>, span: Span) {
        let kind = match declaration.kind {
            VariableDeclarationKind::Const => return,
            VariableDeclarationKind::Let => TbKind::Let,
            _ => TbKind::Var,
        };
        let _ = kind;
        for declarator in &declaration.declarations {
            if let BindingPattern::BindingIdentifier(identifier) = &declarator.id {
                self.model.events.push(TbEvent {
                    name: identifier.name.as_str(),
                    span,
                    write: true,
                    compound: false,
                    chain: self.stack.clone(),
                });
            }
        }
    }
    /// Declaration heads record their per-iteration writes while that scope
    /// is still on the chain, so they resolve onto the loop binding instead
    /// of degrading to implicit globals.
    fn visit_for_head(&mut self, left: &oxc_ast::ast::ForStatementLeft<'a>, loop_span: Span) {
        match left {
            oxc_ast::ast::ForStatementLeft::VariableDeclaration(declaration) => {
                self.visit_variable_declaration(declaration);
                self.mark_loop_bindings(declaration, loop_span);
            }
            left => self.visit_for_statement_left(left),
        }
    }
}

impl<'a> Visit<'a> for TbBuilder<'a, '_> {
    fn visit_program(&mut self, program: &oxc_ast::ast::Program<'a>) {
        self.push_scope(TbScopeKind::Program, program.span);
        walk_program(self, program);
        self.pop_scope();
    }

    fn visit_block_statement(&mut self, statement: &BlockStatement<'a>) {
        self.push_scope(TbScopeKind::Block, statement.span);
        walk_block_statement(self, statement);
        self.pop_scope();
    }

    fn visit_switch_statement(&mut self, statement: &SwitchStatement<'a>) {
        self.push_scope(TbScopeKind::Block, statement.span);
        walk_switch_statement(self, statement);
        self.pop_scope();
    }

    fn visit_static_block(&mut self, block: &StaticBlock<'a>) {
        self.push_scope(TbScopeKind::Function, block.span);
        walk_static_block(self, block);
        self.pop_scope();
    }

    fn visit_for_statement(&mut self, statement: &oxc_ast::ast::ForStatement<'a>) {
        self.push_scope(TbScopeKind::Block, statement.span);
        walk_for_statement(self, statement);
        self.pop_scope();
    }

    fn visit_for_in_statement(&mut self, statement: &oxc_ast::ast::ForInStatement<'a>) {
        self.push_scope(TbScopeKind::Block, statement.span);
        self.visit_for_head(&statement.left, statement.span);
        // The iterable resolves in the enclosing scope: the loop-head
        // binding is not yet initialized where the iterable evaluates.
        let head = self.stack.pop();
        self.visit_expression(&statement.right);
        if let Some(id) = head {
            self.stack.push(id);
        }
        self.visit_statement(&statement.body);
        self.pop_scope();
    }

    fn visit_for_of_statement(&mut self, statement: &oxc_ast::ast::ForOfStatement<'a>) {
        self.push_scope(TbScopeKind::Block, statement.span);
        self.visit_for_head(&statement.left, statement.span);
        // The iterable resolves in the enclosing scope: the loop-head
        // binding is not yet initialized where the iterable evaluates.
        let head = self.stack.pop();
        self.visit_expression(&statement.right);
        if let Some(id) = head {
            self.stack.push(id);
        }
        self.visit_statement(&statement.body);
        self.pop_scope();
    }

    fn visit_catch_clause(&mut self, clause: &oxc_ast::ast::CatchClause<'a>) {
        self.push_scope(TbScopeKind::Block, clause.span);
        if let Some(param) = &clause.param {
            self.declare_pattern(&param.pattern, TbKind::CatchParam);
        }
        walk_catch_clause(self, clause);
        self.pop_scope();
    }

    fn visit_function(&mut self, function: &oxc_ast::ast::Function<'a>, flags: ScopeFlags) {
        let declaration = function.r#type == oxc_ast::ast::FunctionType::FunctionDeclaration;
        let mut name_binding = None;
        if declaration && let Some(id) = &function.id {
            name_binding = Some(self.declare(id.name.as_str(), TbKind::Function, id.span));
        }
        self.push_scope(TbScopeKind::Function, function.span);
        if !declaration && let Some(id) = &function.id {
            self.declare(id.name.as_str(), TbKind::Function, id.span);
        }
        self.declare_parameters(&function.params);
        self.skip_parameters = false;
        let arity = signature_arity(&function.params);
        if let Some(binding) = name_binding {
            self.model.bindings[binding].arity = Some(arity);
        }
        walk_function(self, function, flags);
        self.pop_scope();
    }

    fn visit_arrow_function_expression(&mut self, arrow: &ArrowFunctionExpression<'a>) {
        self.push_scope(TbScopeKind::Function, arrow.span);
        self.declare_parameters(&arrow.params);
        walk_arrow_function_expression(self, arrow);
        self.pop_scope();
    }

    fn visit_method_definition(&mut self, method: &MethodDefinition<'a>) {
        // Setters legitimately leave their parameter unread (`S1172`); the
        // flag is consumed and cleared by the method's own `visit_function`.
        if method.kind == MethodDefinitionKind::Set {
            self.skip_parameters = true;
        }
        walk_method_definition(self, method);
        self.skip_parameters = false;
    }

    fn visit_class(&mut self, class: &Class<'a>) {
        let declaration = class.r#type == oxc_ast::ast::ClassType::ClassDeclaration;
        if declaration && let Some(id) = &class.id {
            self.declare(id.name.as_str(), TbKind::Class, id.span);
        }
        self.push_scope(TbScopeKind::Block, class.span);
        if !declaration && let Some(id) = &class.id {
            self.declare(id.name.as_str(), TbKind::Class, id.span);
        }
        walk_class(self, class);
        self.pop_scope();
    }

    fn visit_unary_expression(&mut self, unary: &UnaryExpression<'a>) {
        self.record_delete(unary);
        walk_unary_expression(self, unary);
    }

    fn visit_variable_declaration(&mut self, declaration: &VariableDeclaration<'a>) {
        let saved = self.pending_kind;
        self.pending_kind = match declaration.kind {
            VariableDeclarationKind::Var => TbKind::Var,
            VariableDeclarationKind::Let => TbKind::Let,
            _ => TbKind::Const,
        };
        walk_variable_declaration(self, declaration);
        self.pending_kind = saved;
    }

    fn visit_variable_declarator(&mut self, declarator: &VariableDeclarator<'a>) {
        let before = self.model.bindings.len();
        self.declare_pattern(&declarator.id, self.pending_kind);
        if before < self.model.bindings.len()
            && matches!(declarator.id, BindingPattern::BindingIdentifier(_))
            && matches!(declarator.init, Some(Expression::ArrayExpression(_)))
        {
            self.model.bindings[before].array_like = true;
        }
        walk_variable_declarator(self, declarator);
    }

    fn visit_import_declaration(&mut self, declaration: &ImportDeclaration<'a>) {
        let Some(specifiers) = &declaration.specifiers else {
            return;
        };
        for specifier in specifiers {
            let local = match specifier {
                ImportDeclarationSpecifier::ImportSpecifier(specifier) => &specifier.local,
                ImportDeclarationSpecifier::ImportDefaultSpecifier(specifier) => &specifier.local,
                ImportDeclarationSpecifier::ImportNamespaceSpecifier(specifier) => &specifier.local,
            };
            self.declare(local.name.as_str(), TbKind::Import, local.span);
        }
    }

    fn visit_export_specifier(&mut self, specifier: &ExportSpecifier<'a>) {
        // `export { local }` keeps the local binding alive.
        if let ModuleExportName::IdentifierReference(reference) = &specifier.local {
            self.record_reference(reference.name.as_str(), reference.span);
        }
    }

    fn visit_export_default_declaration(
        &mut self,
        declaration: &oxc_ast::ast::ExportDefaultDeclaration<'a>,
    ) {
        // `export default function name() {}` uses `name`.
        if let ExportDefaultDeclarationKind::FunctionDeclaration(function) =
            &declaration.declaration
            && let Some(id) = &function.id
        {
            self.record_reference(id.name.as_str(), id.span);
        }
        walk_export_default_declaration(self, declaration);
    }

    fn visit_assignment_expression(&mut self, assignment: &AssignmentExpression<'a>) {
        self.compound |= assignment.operator != AssignmentOperator::Assign;
        self.write_depth += 1;
        self.visit_assignment_target(&assignment.left);
        self.write_depth -= 1;
        self.compound = false;
        walk_expression(self, &assignment.right);
    }

    fn visit_update_expression(&mut self, update: &oxc_ast::ast::UpdateExpression<'a>) {
        self.compound = true;
        self.write_depth += 1;
        self.visit_simple_assignment_target(&update.argument);
        self.write_depth -= 1;
        self.compound = false;
    }

    fn visit_call_expression(&mut self, call: &CallExpression<'a>) {
        self.record_callee(&call.callee, &call.arguments, false);
        walk_call_expression(self, call);
    }

    fn visit_new_expression(&mut self, new: &NewExpression<'a>) {
        self.record_callee(&new.callee, &new.arguments, true);
        walk_new_expression(self, new);
    }

    fn visit_identifier_reference(&mut self, reference: &oxc_ast::ast::IdentifierReference<'a>) {
        self.record_reference(reference.name.as_str(), reference.span);
    }
}

/// `(minimum, hard maximum, optional positions)` of one signature; a rest
/// parameter removes the maximum.
pub(crate) fn signature_arity(parameters: &oxc_ast::ast::FormalParameters<'_>) -> TbSignature {
    let optional = parameters
        .items
        .iter()
        .enumerate()
        .filter(|(_, parameter)| parameter.initializer.is_some() || parameter.optional)
        .map(|(position, _)| position)
        .collect();
    let minimum = parameters
        .items
        .iter()
        .filter(|parameter| parameter.initializer.is_none() && !parameter.optional)
        .count();
    let maximum = parameters.rest.is_none().then(|| parameters.items.len());
    TbSignature {
        minimum,
        maximum,
        optional,
    }
}

pub(crate) fn build_tb_model<'a>(program: &'a oxc_ast::ast::Program<'a>) -> TbModel<'a> {
    let mut model = TbModel {
        scopes: Vec::new(),
        bindings: Vec::new(),
        events: Vec::new(),
        callees: Vec::new(),
        shadows: Vec::new(),
        duplicates: Vec::new(),
        implicit_globals: Vec::new(),
        calls: Vec::new(),
        news: Vec::new(),
        delete_sites: Vec::new(),
        array_deletes: Vec::new(),
    };
    let mut builder = TbBuilder {
        model: &mut model,
        stack: Vec::new(),
        write_depth: 0,
        compound: false,
        skip_parameters: false,
        pending_kind: TbKind::Let,
    };
    builder.visit_program(program);
    finish_model(model)
}

pub(crate) fn callee_member_name<'a>(call: &'a CallExpression<'a>) -> Option<&'a str> {
    call.callee
        .as_member_expression()
        .and_then(static_property_name)
}

/// Reachability of the code following the current point.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum TbHalt {
    Live,
    /// `break`/`continue`: only the innermost loop body ends here.
    Jumped,
    /// `return`/`throw`: everything after is unreachable.
    Exited,
}

/// One tracked value: where it was written and what it came from.
#[derive(Debug, Clone, Copy)]
pub(crate) struct TbPending {
    /// Identifier that received this value.
    pub(crate) site: Span,
    /// Value expression; `None` for compound writes and updates.
    pub(crate) value: Option<Span>,
    /// Value arrived from a parameter or loop variable (`S1226`).
    pub(crate) initial: bool,
}

pub(crate) type TbEnv<'a> = HashMap<&'a str, TbPending>;

/// Straight-line per-function value tracker feeding `S1854`, `S2123`,
/// `S1226`, and `S4165`. Writes inside a branch are recorded but never
/// reported there; branch joins keep an entry only when both paths hold the
/// same write, so conditionally-live values are never flagged.
pub(crate) struct TbFlow<'p, 's, 'i> {
    pub(crate) source: &'s str,
    pub(crate) sink: &'s mut IssueSink<'i>,
    pub(crate) env: TbEnv<'p>,
    pub(crate) status: TbHalt,
    /// Branch nesting depth; findings emit only at depth 0.
    pub(crate) depth: u32,
    pub(crate) mutable_decl: bool,
}

impl<'p> TbFlow<'p, '_, '_> {
    pub(crate) fn read(&mut self, name: &'p str) {
        self.env.remove(name);
    }

    pub(crate) fn write(&mut self, name: &'p str, site: Span, value: Option<Span>, initial: bool) {
        let previous = self.env.get(name).copied();
        if self.depth == 0
            && let Some(previous) = previous
            && !initial
        {
            if previous.initial {
                self.sink.emit_span(
                    RuleScope::Both,
                    "S1226",
                    &format!(
                        "Assign '{name}' to a new variable instead of overwriting its incoming value."
                    ),
                    site,
                );
            } else {
                let same_value = matches!(
                    (previous.value, value),
                    (Some(old), Some(new))
                        if source_slice(self.source, old) == source_slice(self.source, new)
                );
                if same_value {
                    self.sink.emit_span(
                        RuleScope::Both,
                        "S4165",
                        &format!("Remove this redundant assignment of the same value to '{name}'."),
                        site,
                    );
                } else {
                    self.sink.emit_span(
                        RuleScope::Both,
                        "S1854",
                        &format!("Remove this unused assignment of '{name}'."),
                        previous.site,
                    );
                }
            }
        }
        self.env.insert(
            name,
            TbPending {
                site,
                value,
                initial,
            },
        );
    }

    pub(crate) fn seed_parameter(&mut self, pattern: Option<&BindingPattern<'p>>) {
        if let Some(BindingPattern::BindingIdentifier(identifier)) = pattern {
            let name = identifier.name.as_str();
            self.env.insert(
                name,
                TbPending {
                    site: identifier.span,
                    value: None,
                    initial: true,
                },
            );
        }
    }

    pub(crate) fn enter_function(&mut self, parameters: &FormalParameters<'p>) {
        self.env.clear();
        self.status = TbHalt::Live;
        for parameter in &parameters.items {
            self.seed_parameter(Some(&parameter.pattern));
        }
        if let Some(rest) = &parameters.rest {
            self.seed_parameter(Some(&rest.rest.argument));
        }
    }

    pub(crate) fn process_statements(&mut self, statements: &[Statement<'p>]) {
        for statement in statements {
            if self.status != TbHalt::Live {
                return;
            }
            self.visit_statement(statement);
        }
    }

    /// Merges two branch outcomes; `pre` is the environment before branching.
    pub(crate) fn join(
        &mut self,
        then_state: (TbEnv<'p>, TbHalt),
        else_state: (TbEnv<'p>, TbHalt),
        pre: TbEnv<'p>,
    ) {
        match (then_state.1, else_state.1) {
            (TbHalt::Live, TbHalt::Live) => {
                self.env = intersect_envs(then_state.0, &else_state.0);
                self.status = TbHalt::Live;
            }
            (TbHalt::Live, _) => {
                self.env = then_state.0;
                self.status = TbHalt::Live;
            }
            (_, TbHalt::Live) => {
                self.env = else_state.0;
                self.status = TbHalt::Live;
            }
            (_, TbHalt::Exited) | (TbHalt::Exited, _) => {
                self.env = pre;
                self.status = TbHalt::Exited;
            }
            _ => {
                self.env = pre;
                self.status = TbHalt::Jumped;
            }
        }
    }

    /// Loop bodies may re-read every value on the next iteration, and values
    /// written inside may be read by the test or update expressions, so all
    /// tracking is dropped at the loop boundary.
    pub(crate) fn end_loop(&mut self) {
        self.env.clear();
        if self.status != TbHalt::Exited {
            self.status = TbHalt::Live;
        }
    }
}

impl<'p> Visit<'p> for TbFlow<'p, '_, '_> {
    fn visit_program(&mut self, program: &oxc_ast::ast::Program<'p>) {
        self.process_statements(&program.body);
    }

    fn visit_block_statement(&mut self, block: &BlockStatement<'p>) {
        self.process_statements(&block.body);
    }

    fn visit_static_block(&mut self, block: &StaticBlock<'p>) {
        let saved = (std::mem::take(&mut self.env), self.status, self.depth);
        self.status = TbHalt::Live;
        self.process_statements(&block.body);
        self.env = saved.0;
        self.status = saved.1;
        self.depth = saved.2;
    }

    fn visit_function(&mut self, function: &Function<'p>, _flags: ScopeFlags) {
        let saved = (std::mem::take(&mut self.env), self.status, self.depth);
        self.enter_function(&function.params);
        if let Some(body) = &function.body {
            self.process_statements(&body.statements);
        }
        self.env = saved.0;
        self.status = saved.1;
        self.depth = saved.2;
    }

    fn visit_arrow_function_expression(&mut self, arrow: &ArrowFunctionExpression<'p>) {
        let saved = (std::mem::take(&mut self.env), self.status, self.depth);
        self.enter_function(&arrow.params);
        if let ArrowFunctionBody::FunctionBody(body) = &arrow.body {
            self.process_statements(&body.statements);
        } else if let Some(expression) = arrow.body.as_expression() {
            self.visit_expression(expression);
        }
        self.env = saved.0;
        self.status = saved.1;
        self.depth = saved.2;
    }

    fn visit_catch_clause(&mut self, clause: &CatchClause<'p>) {
        let saved = (std::mem::take(&mut self.env), self.status, self.depth);
        self.seed_parameter(clause.param.as_ref().map(|param| &param.pattern));
        self.process_statements(&clause.body.body);
        self.env = saved.0;
        self.status = saved.1;
        self.depth = saved.2;
    }

    fn visit_if_statement(&mut self, node: &IfStatement<'p>) {
        self.visit_expression(&node.test);
        let pre = self.env.clone();
        let pre_join = self.env.clone();
        let saved_depth = self.depth;
        self.depth += 1;
        self.visit_statement(&node.consequent);
        let then_state = (std::mem::replace(&mut self.env, pre.clone()), self.status);
        let else_state = match &node.alternate {
            Some(alternate) => {
                self.status = TbHalt::Live;
                self.visit_statement(alternate);
                (std::mem::replace(&mut self.env, pre_join), self.status)
            }
            None => (pre.clone(), TbHalt::Live),
        };
        self.depth = saved_depth;
        self.join(then_state, else_state, pre);
    }

    fn visit_conditional_expression(&mut self, node: &ConditionalExpression<'p>) {
        self.visit_expression(&node.test);
        let pre = self.env.clone();
        let pre_join = self.env.clone();
        let saved_depth = self.depth;
        self.depth += 1;
        self.visit_expression(&node.consequent);
        let then_state = (std::mem::replace(&mut self.env, pre.clone()), self.status);
        self.status = TbHalt::Live;
        self.visit_expression(&node.alternate);
        let else_state = (std::mem::replace(&mut self.env, pre_join), self.status);
        self.depth = saved_depth;
        self.join(then_state, else_state, pre);
    }

    fn visit_switch_statement(&mut self, node: &SwitchStatement<'p>) {
        self.visit_expression(&node.discriminant);
        let pre = self.env.clone();
        let pre_fallback = self.env.clone();
        let saved_depth = self.depth;
        self.depth += 1;
        let mut joined: Option<TbEnv<'p>> = None;
        for case in &node.cases {
            self.env = pre.clone();
            self.status = TbHalt::Live;
            if let Some(test) = &case.test {
                self.visit_expression(test);
            }
            self.process_statements(&case.consequent);
            if self.status == TbHalt::Live {
                let current = std::mem::replace(&mut self.env, pre.clone());
                joined = Some(match joined {
                    None => current,
                    Some(existing) => intersect_envs(existing, &current),
                });
            }
        }
        self.depth = saved_depth;
        // A default-less switch or a final break keeps executing after the
        // switch, so treat the join point as live regardless.
        self.status = TbHalt::Live;
        self.env = joined.unwrap_or(pre_fallback);
    }

    fn visit_try_statement(&mut self, node: &TryStatement<'p>) {
        let pre = self.env.clone();
        let pre_join = self.env.clone();
        let saved_depth = self.depth;
        self.depth += 1;
        self.process_statements(&node.block.body);
        let try_state = (std::mem::replace(&mut self.env, pre.clone()), self.status);
        let handler_state = match &node.handler {
            Some(handler) => {
                self.status = TbHalt::Live;
                // The catch body runs on its own straight-line path, so its
                // writes are reportable even though the try block is not.
                let handler_depth = std::mem::replace(&mut self.depth, 0);
                self.visit_catch_clause(handler);
                self.depth = handler_depth;
                (std::mem::replace(&mut self.env, pre_join), self.status)
            }
            None => (pre.clone(), TbHalt::Live),
        };
        self.depth = saved_depth;
        self.join(try_state, handler_state, pre);
        if let Some(finalizer) = &node.finalizer {
            self.visit_block_statement(finalizer);
        }
    }

    fn visit_while_statement(&mut self, node: &WhileStatement<'p>) {
        for name in subtree_names(&[&node.test], &[&node.body]) {
            self.env.remove(name);
        }
        self.visit_expression(&node.test);
        self.visit_statement(&node.body);
        self.end_loop();
    }

    fn visit_do_while_statement(&mut self, node: &DoWhileStatement<'p>) {
        for name in subtree_names(&[&node.test], &[&node.body]) {
            self.env.remove(name);
        }
        self.visit_statement(&node.body);
        self.visit_expression(&node.test);
        self.end_loop();
    }

    fn visit_for_statement(&mut self, node: &ForStatement<'p>) {
        let mut parts: Vec<&Expression<'p>> = Vec::new();
        if let Some(test) = &node.test {
            parts.push(test);
        }
        if let Some(update) = &node.update {
            parts.push(update);
        }
        for name in subtree_names(&parts, &[&node.body]) {
            self.env.remove(name);
        }
        walk_for_statement(self, node);
        self.end_loop();
    }

    fn visit_for_in_statement(&mut self, node: &ForInStatement<'p>) {
        for name in subtree_names(&[&node.right], &[&node.body]) {
            self.env.remove(name);
        }
        walk_for_in_statement(self, node);
        self.end_loop();
    }

    fn visit_for_of_statement(&mut self, node: &ForOfStatement<'p>) {
        for name in subtree_names(&[&node.right], &[&node.body]) {
            self.env.remove(name);
        }
        walk_for_of_statement(self, node);
        self.end_loop();
    }

    fn visit_break_statement(&mut self, _: &BreakStatement<'p>) {
        self.status = TbHalt::Jumped;
    }

    fn visit_continue_statement(&mut self, _: &ContinueStatement<'p>) {
        self.status = TbHalt::Jumped;
    }

    fn visit_return_statement(&mut self, node: &ReturnStatement<'p>) {
        if let Some(argument) = &node.argument {
            self.visit_expression(argument);
        }
        self.status = TbHalt::Exited;
    }

    fn visit_throw_statement(&mut self, node: &ThrowStatement<'p>) {
        self.visit_expression(&node.argument);
        self.status = TbHalt::Exited;
    }

    fn visit_assignment_expression(&mut self, assign: &AssignmentExpression<'p>) {
        if let Some(update_span) = self_overwrite_target(assign) {
            self.sink.emit_span(
                RuleScope::Both,
                "S2123",
                "This increment/decrement result is unused; the variable is overwritten immediately.",
                update_span,
            );
            if let Some((name, _)) = tb_assignment_target(&assign.left) {
                self.read(name);
            }
            return;
        }
        self.visit_expression(&assign.right);
        if let Some((name, span)) = tb_assignment_target(&assign.left) {
            if assign.operator != AssignmentOperator::Assign {
                self.read(name);
            }
            self.write(name, span, Some(assign.right.span()), false);
        } else {
            self.visit_assignment_target(&assign.left);
        }
    }

    fn visit_update_expression(&mut self, update: &UpdateExpression<'p>) {
        match &update.argument {
            SimpleAssignmentTarget::AssignmentTargetIdentifier(identifier) => {
                let name = identifier.name.as_str();
                self.read(name);
                self.write(name, identifier.span, None, false);
            }
            other => self.visit_simple_assignment_target(other),
        }
    }

    fn visit_variable_declaration(&mut self, declaration: &VariableDeclaration<'p>) {
        let saved = self.mutable_decl;
        self.mutable_decl = declaration.kind != VariableDeclarationKind::Const;
        for declarator in &declaration.declarations {
            self.visit_variable_declarator(declarator);
        }
        self.mutable_decl = saved;
    }

    fn visit_variable_declarator(&mut self, declarator: &VariableDeclarator<'p>) {
        if let Some(init) = &declarator.init {
            self.visit_expression(init);
        }
        match &declarator.id {
            BindingPattern::BindingIdentifier(identifier) => {
                let name = identifier.name.as_str();
                if self.mutable_decl {
                    let value = declarator.init.as_ref().map(GetSpan::span);
                    self.write(name, identifier.span, value, false);
                } else {
                    self.env.remove(name);
                }
            }
            pattern => {
                for name in bound_names(pattern) {
                    self.env.remove(name);
                }
            }
        }
    }
}

pub(crate) fn intersect_envs<'p>(left: TbEnv<'p>, right: &TbEnv<'p>) -> TbEnv<'p> {
    left.into_iter()
        .filter(|(name, pending)| {
            right
                .get(name)
                .is_some_and(|other| other.site == pending.site)
        })
        .collect()
}

pub(crate) fn tb_assignment_target<'data>(
    target: &AssignmentTarget<'data>,
) -> Option<(&'data str, Span)> {
    match target {
        AssignmentTarget::AssignmentTargetIdentifier(identifier) => {
            Some((identifier.name.as_str(), identifier.span))
        }
        _ => None,
    }
}

/// Span of the `++`/`--` when an assignment overwrites its own updated
/// operand (`x = x++`, `x += x--`): the update's effect is discarded (`S2123`).
pub(crate) fn self_overwrite_target(assign: &AssignmentExpression<'_>) -> Option<Span> {
    let (target_name, _) = tb_assignment_target(&assign.left)?;
    let Expression::UpdateExpression(update) = unparenthesized(&assign.right) else {
        return None;
    };
    let SimpleAssignmentTarget::AssignmentTargetIdentifier(operand) = &update.argument else {
        return None;
    };
    (operand.name.as_str() == target_name).then_some(update.span)
}

#[derive(Default)]
pub(crate) struct TbReferenceNames<'a> {
    pub(crate) names: Vec<&'a str>,
}

impl<'a> Visit<'a> for TbReferenceNames<'a> {
    fn visit_identifier_reference(&mut self, reference: &oxc_ast::ast::IdentifierReference<'a>) {
        self.names.push(reference.name.as_str());
    }
}

#[derive(Default)]
pub(crate) struct TbBoundNames<'a> {
    pub(crate) names: Vec<&'a str>,
}

impl<'a> Visit<'a> for TbBoundNames<'a> {
    fn visit_binding_identifier(&mut self, identifier: &BindingIdentifier<'a>) {
        self.names.push(identifier.name.as_str());
    }
}

pub(crate) fn bound_names<'a>(pattern: &'a BindingPattern<'a>) -> Vec<&'a str> {
    let mut collector = TbBoundNames::default();
    collector.visit_binding_pattern(pattern);
    collector.names
}

/// Names read or written anywhere in the given expression/statement parts.
pub(crate) fn subtree_names<'a>(
    expressions: &[&Expression<'a>],
    statements: &[&Statement<'a>],
) -> Vec<&'a str> {
    let mut collector = TbReferenceNames::default();
    for expression in expressions {
        collector.visit_expression(expression);
    }
    for statement in statements {
        collector.visit_statement(statement);
    }
    collector.names
}

pub(crate) fn member_optional(member: &MemberExpression<'_>) -> bool {
    match member {
        MemberExpression::StaticMemberExpression(expression) => expression.optional,
        MemberExpression::ComputedMemberExpression(expression) => expression.optional,
        MemberExpression::PrivateFieldExpression(expression) => expression.optional,
    }
}

// --- Tier C: operator/literal rules over a shared literal classifier ---

/// Literal classification used by the Tier-C operator checks; `None` means
/// the operand's type is unknown (identifiers, calls, ...).
#[derive(Debug, Clone, Copy, PartialEq, Eq, PartialOrd, Ord)]
pub(crate) enum LiteralKind {
    String,
    Number,
    BigInt,
    Boolean,
    Null,
    Undefined,
    Array,
    Object,
    RegExp,
    Function,
}

/// Classifies an expression that is a literal (or literal-shaped, such as
/// `-1` or a template without substitutions).
pub(crate) fn literal_kind(expression: &Expression<'_>) -> Option<LiteralKind> {
    match unparenthesized(expression) {
        Expression::StringLiteral(_) | Expression::TemplateLiteral(_) => Some(LiteralKind::String),
        Expression::NumericLiteral(_) => Some(LiteralKind::Number),
        Expression::BigIntLiteral(_) => Some(LiteralKind::BigInt),
        Expression::BooleanLiteral(_) => Some(LiteralKind::Boolean),
        Expression::NullLiteral(_) => Some(LiteralKind::Null),
        Expression::Identifier(identifier) => match identifier.name.as_str() {
            "undefined" => Some(LiteralKind::Undefined),
            "NaN" | "Infinity" => Some(LiteralKind::Number),
            _ => None,
        },
        Expression::UnaryExpression(unary) => {
            let numeric = matches!(
                unary.operator,
                UnaryOperator::UnaryNegation | UnaryOperator::UnaryPlus
            ) && matches!(
                unparenthesized(&unary.argument),
                Expression::NumericLiteral(_)
            );
            numeric.then_some(LiteralKind::Number)
        }
        Expression::ArrayExpression(_) => Some(LiteralKind::Array),
        Expression::ObjectExpression(_) => Some(LiteralKind::Object),
        Expression::RegExpLiteral(_) => Some(LiteralKind::RegExp),
        Expression::FunctionExpression(_) | Expression::ArrowFunctionExpression(_) => {
            Some(LiteralKind::Function)
        }
        _ => None,
    }
}

/// Whether a classified literal behaves numerically (`S3760`).
pub(crate) fn kind_is_numeric(kind: LiteralKind) -> bool {
    matches!(kind, LiteralKind::Number | LiteralKind::BigInt)
}

/// Whether a classified literal coerces to `'[object Object]'` (`S3758`).
pub(crate) fn kind_is_composite(kind: LiteralKind) -> bool {
    matches!(
        kind,
        LiteralKind::Array | LiteralKind::Object | LiteralKind::RegExp | LiteralKind::Function
    )
}

/// Per-function facts recorded by [`FunctionCensus`].
#[derive(Default)]
pub(crate) struct FnFacts {
    pub(crate) r#async: bool,
    pub(crate) generator: bool,
    pub(crate) return_kinds: Vec<LiteralKind>,
    /// Span of a parameter that only selects the function's behavior.
    pub(crate) selector_span: Option<Span>,
    pub(crate) span: Span,
}

impl FnFacts {
    /// Whether calls of this function provably produce no usable value.
    pub(crate) fn is_void(&self) -> bool {
        !self.r#async && !self.generator && self.return_kinds.is_empty()
    }
}

/// File-local function facts used by the Tier-C call checks: declaration and
/// `const`-bound function/arrow names with their flags, spans, and the
/// literal kinds of their valued `return`s.
#[derive(Default)]
pub(crate) struct FunctionCensus {
    pub(crate) functions: BTreeMap<String, FnFacts>,
}

/// Parameter names treated as behavior selectors by `S2301` (weak subset).
pub(crate) const SELECTOR_PARAM_NAMES: [&str; 5] = ["type", "kind", "action", "mode", "command"];

/// Scoped scan of one function body: collects valued-return literal kinds
/// and branch logic driven by named parameters, without descending into
/// nested function-like nodes.
#[derive(Default)]
pub(crate) struct BodyScan {
    pub(crate) params: Vec<(String, Span)>,
    pub(crate) return_kinds: Vec<LiteralKind>,
    pub(crate) selector_comparisons: u32,
    pub(crate) switches_on_param: bool,
}

impl<'a> Visit<'a> for BodyScan {
    fn visit_return_statement(&mut self, it: &ReturnStatement<'a>) {
        if let Some(argument) = &it.argument
            && let Some(kind) = literal_kind(argument)
        {
            self.return_kinds.push(kind);
        }
        walk_return_statement(self, it);
    }

    fn visit_binary_expression(&mut self, it: &BinaryExpression<'a>) {
        if matches!(
            it.operator,
            BinaryOperator::Equality
                | BinaryOperator::StrictEquality
                | BinaryOperator::Inequality
                | BinaryOperator::StrictInequality
        ) {
            let left_is_param = self.param_index(&it.left).is_some();
            let right_is_param = self.param_index(&it.right).is_some();
            let other = if left_is_param {
                Some(&it.right)
            } else if right_is_param {
                Some(&it.left)
            } else {
                None
            };
            if other.is_some_and(|expression| literal_kind(expression).is_some()) {
                self.selector_comparisons += 1;
            }
        }
        walk_binary_expression(self, it);
    }

    fn visit_switch_statement(&mut self, it: &SwitchStatement<'a>) {
        if self.param_index(&it.discriminant).is_some() {
            self.switches_on_param = true;
        }
        walk_switch_statement(self, it);
    }

    /// Nested function-like subtrees belong to other functions.
    fn visit_function(&mut self, _it: &Function<'_>, _flags: ScopeFlags) {}
    fn visit_arrow_function_expression(&mut self, _it: &ArrowFunctionExpression<'_>) {}
    fn visit_method_definition(&mut self, _it: &MethodDefinition<'_>) {}
}

impl BodyScan {
    pub(crate) fn param_index(&self, expression: &Expression<'_>) -> Option<usize> {
        let name = identifier_name(expression)?;
        self.params.iter().position(|(param, _)| param == name)
    }

    /// The span of the first parameter that only selects behavior. A weak
    /// heuristic: switch over the parameter or at least two equality
    /// comparisons against literals.
    pub(crate) fn selector_span(&self) -> Option<Span> {
        let driven = self.switches_on_param || self.selector_comparisons >= 2;
        if !driven {
            return None;
        }
        self.params
            .iter()
            .find(|(name, _)| SELECTOR_PARAM_NAMES.contains(&name.as_str()))
            .map(|(_, span)| *span)
    }
}

pub(crate) fn scan_body(statements: &[Statement<'_>], params: Vec<(String, Span)>) -> BodyScan {
    let mut scan = BodyScan {
        params,
        ..BodyScan::default()
    };
    for statement in statements {
        scan.visit_statement(statement);
    }
    scan
}

pub(crate) fn parameter_spans(params: &oxc_ast::ast::FormalParameters<'_>) -> Vec<(String, Span)> {
    params
        .items
        .iter()
        .filter_map(|item| {
            binding_identifier_name(&item.pattern).map(|name| (name.to_string(), item.span))
        })
        .collect()
}

impl<'a> Visit<'a> for FunctionCensus {
    fn visit_declaration(&mut self, it: &Declaration<'a>) {
        if let Declaration::FunctionDeclaration(function) = it
            && let Some(id) = &function.id
        {
            let scan = function
                .body
                .as_ref()
                .map(|body| scan_body(&body.statements, parameter_spans(&function.params)))
                .unwrap_or_default();
            let facts = FnFacts {
                r#async: function.r#async,
                generator: function.generator,
                selector_span: scan.selector_span(),
                return_kinds: scan.return_kinds,
                span: id.span(),
            };
            self.functions.insert(id.name.to_string(), facts);
        }
        walk_declaration(self, it);
    }

    fn visit_variable_declarator(&mut self, it: &VariableDeclarator<'a>) {
        if let Some(name) = binding_identifier_name(&it.id)
            && let Some(init) = &it.init
        {
            match unparenthesized(init) {
                Expression::ArrowFunctionExpression(arrow) => {
                    let scan = if let ArrowFunctionBody::FunctionBody(body) = &arrow.body {
                        scan_body(&body.statements, parameter_spans(&arrow.params))
                    } else {
                        let mut scan = BodyScan::default();
                        if let Some(kind) = arrow.body.as_expression().and_then(literal_kind) {
                            scan.return_kinds.push(kind);
                        }
                        scan
                    };
                    let facts = FnFacts {
                        r#async: arrow.r#async,
                        // Arrow functions cannot be generators.
                        generator: false,
                        selector_span: scan.selector_span(),
                        return_kinds: scan.return_kinds,
                        span: arrow.span,
                    };
                    self.functions.insert(name.to_string(), facts);
                }
                Expression::FunctionExpression(function) => {
                    let scan = function
                        .body
                        .as_ref()
                        .map(|body| scan_body(&body.statements, parameter_spans(&function.params)))
                        .unwrap_or_default();
                    let facts = FnFacts {
                        r#async: function.r#async,
                        generator: function.generator,
                        selector_span: scan.selector_span(),
                        return_kinds: scan.return_kinds,
                        span: function.span,
                    };
                    self.functions.insert(name.to_string(), facts);
                }
                _ => {}
            }
        }
        walk_variable_declarator(self, it);
    }
}

// --- Tier C: file-local class facts for `S6551` ---

/// File-local class facts used by `S6551`: which classes declare a
/// `toString` member and which locals are constructed from classes that
/// do not.
#[derive(Default)]
pub(crate) struct ClassCensus {
    /// Class declaration name -> whether a `toString` member exists.
    pub(crate) classes: BTreeMap<String, bool>,
    /// Local name -> class name for locals bound through `new C(...)`
    /// where `C` declares no `toString` member.
    pub(crate) instances: BTreeMap<String, String>,
}

impl<'a> Visit<'a> for ClassCensus {
    fn visit_declaration(&mut self, it: &Declaration<'a>) {
        if let Declaration::ClassDeclaration(class) = it
            && let Some(id) = &class.id
        {
            self.classes
                .insert(id.name.to_string(), class_declares_to_string(class));
        }
        walk_declaration(self, it);
    }

    fn visit_variable_declarator(&mut self, it: &VariableDeclarator<'a>) {
        if let Some(name) = binding_identifier_name(&it.id)
            && let Some(init) = &it.init
            && let Expression::NewExpression(constructor) = unparenthesized(init)
            && let Expression::Identifier(callee) = &constructor.callee
            && self.classes.get(callee.name.as_str()) == Some(&false)
        {
            self.instances
                .insert(name.to_string(), callee.name.to_string());
        }
        walk_variable_declarator(self, it);
    }
}

/// Whether the class declares a `toString` method or property directly.
/// String-literal and computed keys are outside this subset.
pub(crate) fn class_declares_to_string(class: &Class<'_>) -> bool {
    class.body.body.iter().any(|element| match element {
        ClassElement::MethodDefinition(method)
            if !matches!(
                method.kind,
                MethodDefinitionKind::Constructor
                    | MethodDefinitionKind::Get
                    | MethodDefinitionKind::Set
            ) =>
        {
            property_key_name(&method.key) == Some("toString")
        }
        ClassElement::PropertyDefinition(property) => {
            property_key_name(&property.key) == Some("toString")
        }
        _ => false,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use oxc_allocator::Allocator;
    use oxc_parser::Parser;
    use oxc_span::SourceType;

    fn binding<'m>(model: &'m TbModel<'_>, name: &str, global: bool) -> &'m TbBinding<'m> {
        model
            .bindings
            .iter()
            .find(|binding| binding.name == name && binding.global == global)
            .unwrap_or_else(|| panic!("no `{name}` binding with global={global}"))
    }
    fn with_model(source: &str, check: impl FnOnce(&TbModel<'_>)) {
        let allocator = Allocator::default();
        let parsed = Parser::new(&allocator, source, SourceType::mjs()).parse();
        let model = build_tb_model(&parsed.program);
        check(&model);
    }
    /// The per-iteration write of a `for (let v of …)` / `for (let v in …)`
    /// head must resolve onto the loop binding itself: its event is recorded
    #[test]
    fn loop_head_let_write_lands_on_the_binding() {
        for source in [
            "let xs = [1];\nfor (let v of xs) {\n}\n",
            "let xs = [1];\nfor (let v in xs) {\n}\n",
        ] {
            with_model(source, |model| {
                let binding = binding(model, "v", false);
                assert_eq!(binding.kind, TbKind::Let);
                assert_eq!(
                    binding.writes.len(),
                    1,
                    "per-iteration write must resolve in the loop scope",
                );
                assert!(
                    !model.implicit_globals.iter().any(|(name, _)| *name == "v"),
                    "`v` is declared; its write must not look implicit",
                );
            });
        }
    }

    #[test]
    fn loop_head_var_write_still_lands_on_the_hoisted_binding() {
        with_model("let xs = [1];\nfor (var w of xs) {\n}\n", |model| {
            let binding = binding(model, "w", true);
            assert_eq!(binding.kind, TbKind::Var);
            assert_eq!(binding.writes.len(), 1);
            assert!(!model.implicit_globals.iter().any(|(name, _)| *name == "w"));
        });
    }

    /// `const x = 1; for (const x of [x]) {}` — the iterable's `x` refers
    /// to the outer binding: the loop-head binding is not yet initialized
    /// where the iterable evaluates (TDZ), so it must not shadow there.
    #[test]
    fn iterable_resolves_outside_the_loop_head_scope() {
        with_model("const x = 1;\nfor (const x of [x]) {\n}\n", |model| {
            let outer = binding(model, "x", true);
            let head = binding(model, "x", false);
            assert_eq!(outer.reads.len(), 1, "iterable must read the outer `x`");
            assert!(
                head.reads.is_empty(),
                "iterable must not see the head binding"
            );
        });
    }

    #[test]
    fn body_and_closures_still_see_the_loop_head_binding() {
        let source = "const fns = [];\nfor (const x of [1]) {\n    fns.push(() => x);\n}\n";
        with_model(source, |model| {
            let head = binding(model, "x", false);
            assert_eq!(head.reads.len(), 1, "the arrow body reads the head binding");
        });
    }
}
