[package]
name = "hoonarqube-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"
[dependencies]
hoonarqube-csharp = { version = "0.2.0", path = "../hoonarqube-csharp" }
hoonarqube-go = { version = "0.2.0", path = "../hoonarqube-go" }
hoonarqube-ir = { version = "0.2.0", path = "../hoonarqube-ir" }
hoonarqube-jsts = { version = "0.2.0", path = "../hoonarqube-jsts" }
hoonarqube-python = { version = "0.2.0", path = "../hoonarqube-python" }
hoonarqube-rust = { version = "0.2.0", path = "../hoonarqube-rust" }

[lints]
workspace = true
