[package]
name = "hoonarqube"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
hoonarqube-catalog = { version = "0.2.3", path = "../hoonarqube-catalog" }
hoonarqube-core = { version = "0.2.3", path = "../hoonarqube-core" }
hoonarqube-ir = { version = "0.2.3", path = "../hoonarqube-ir" }

[lints]
workspace = true
