[package]
name = "hoonarqube-java"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
publish.workspace = true

[lib]
path = "src/lib.rs"

[dependencies]
hoonarqube-ir = { version = "0.4.2", path = "../hoonarqube-ir" }
tree-sitter = "0.25.10"
tree-sitter-java = "0.23.5"

[lints]
workspace = true
