//! Structural statement checks (Tier A4).
//! A4 — structural statement checks

pub(crate) mod abstract_member_mix;
pub(crate) mod chains_end_with_else;
pub(crate) mod cognitive_complexity;
pub(crate) mod condition_only_for_loops;
pub(crate) mod context_parentheses;
pub(crate) mod curly_braces;
pub(crate) mod cyclomatic_complexity;
pub(crate) mod default_clause_position;
pub(crate) mod empty_blocks;
pub(crate) mod empty_cases_before_default;
pub(crate) mod empty_classes_and_records;
pub(crate) mod empty_default_clauses;
pub(crate) mod empty_finalizers;
pub(crate) mod empty_interfaces;
pub(crate) mod empty_methods;
pub(crate) mod empty_namespaces;
pub(crate) mod empty_statements;
pub(crate) mod finalizer_throws;
pub(crate) mod for_increment_modifies_counter;
pub(crate) mod function_lengths;
pub(crate) mod logical_operator_counts;
pub(crate) mod mergeable_ifs;
pub(crate) mod method_parameter_counts;
pub(crate) mod multiline_embedded_statements;
pub(crate) mod nested_code_blocks;
pub(crate) mod nested_switches;
pub(crate) mod nesting_depth;
pub(crate) mod property_getter_throws;
pub(crate) mod redundant_parentheses;
mod support;
pub(crate) mod switch_case_counts;
pub(crate) mod switch_has_default;
pub(crate) mod switch_section_line_spans;
pub(crate) mod switch_section_statement_counts;
pub(crate) mod trivial_properties;
pub(crate) mod types_outside_namespaces;
mod walker;
pub(crate) mod write_only_properties;

pub(crate) use support::CALLABLE_BODY_OWNER_KINDS;
pub(crate) use support::accessor_keyword;
pub(crate) use support::accessors_of;
pub(crate) use support::binary_operator;
pub(crate) use support::body_of;
pub(crate) use support::counter_name;
pub(crate) use support::else_alternative;
pub(crate) use support::embedded_bodies;
pub(crate) use support::for_clauses;
pub(crate) use support::getter_field;
pub(crate) use support::is_attributed;
pub(crate) use support::is_else_alternative;
pub(crate) use support::is_statement_kind;
pub(crate) use support::name_anchor;
pub(crate) use support::section_statements;
pub(crate) use support::setter_field;
pub(crate) use support::switch_body_of;
pub(crate) use support::switch_sections_of;
pub(crate) use walker::structure_issues;
