// Residual rule machinery for 'react_jsx' (extracted from lib.rs).
use crate::rules::react_jsx::walker::{JsxOrNullScanner, body_returns_jsx_mode};
use oxc_ast::ast::{ArrowFunctionBody, Expression};
use oxc_ast_visit::Visit;

/// Known DOM and React attribute names (`S6747`). Event handlers (`on*`),
/// `data-*`/`aria-*` attributes, and the configured `whitelist` extend this
/// table.
pub(crate) const REACT_DOM_ATTRIBUTES: &[&str] = &[
    "accept",
    "acceptCharset",
    "accessKey",
    "action",
    "allowFullScreen",
    "alt",
    "async",
    "autoComplete",
    "autoFocus",
    "autoPlay",
    "autoSave",
    "capture",
    "cellPadding",
    "cellSpacing",
    "challenge",
    "charSet",
    "checked",
    "children",
    "className",
    "cite",
    "classId",
    "clipPath",
    "colSpan",
    "cols",
    "content",
    "contentEditable",
    "controls",
    "controlsList",
    "coords",
    "crossOrigin",
    "dangerouslySetInnerHTML",
    "dateTime",
    "decoding",
    "default",
    "defaultChecked",
    "defaultValue",
    "defer",
    "dir",
    "dirName",
    "disabled",
    "disablePictureInPicture",
    "disableRemotePlayback",
    "download",
    "draggable",
    "encType",
    "enterKeyHint",
    "fetchPriority",
    "form",
    "formAction",
    "formEncType",
    "formMethod",
    "formNoValidate",
    "formTarget",
    "frameBorder",
    "headers",
    "height",
    "hidden",
    "high",
    "href",
    "hrefLang",
    "htmlFor",
    "httpEquiv",
    "icon",
    "id",
    "inputMode",
    "integrity",
    "is",
    "itemID",
    "itemProp",
    "itemRef",
    "itemScope",
    "itemType",
    "key",
    "keyParams",
    "keyType",
    "kind",
    "label",
    "lang",
    "list",
    "loading",
    "loop",
    "low",
    "manifest",
    "marginHeight",
    "marginWidth",
    "max",
    "maxLength",
    "media",
    "mediaGroup",
    "method",
    "min",
    "minLength",
    "multiple",
    "muted",
    "name",
    "nonce",
    "noValidate",
    "open",
    "optimum",
    "pattern",
    "placeholder",
    "playsInline",
    "poster",
    "preload",
    "profile",
    "radioGroup",
    "readOnly",
    "referrerPolicy",
    "ref",
    "rel",
    "required",
    "reversed",
    "role",
    "rows",
    "rowSpan",
    "sandbox",
    "scope",
    "scoped",
    "scrolling",
    "seamless",
    "selected",
    "shape",
    "size",
    "sizes",
    "slot",
    "span",
    "spellCheck",
    "src",
    "srcDoc",
    "srcLang",
    "srcSet",
    "start",
    "step",
    "style",
    "summary",
    "suppressContentEditableWarning",
    "suppressHydrationWarning",
    "tabIndex",
    "target",
    "title",
    "translate",
    "type",
    "useMap",
    "value",
    "width",
    "wmode",
    "wrap",
    // Common SVG surface.
    "alignmentBaseline",
    "attributeName",
    "azimuth",
    "baseFrequency",
    "baselineShift",
    "baseProfile",
    "bbox",
    "begin",
    "by",
    "calcMode",
    "capHeight",
    "clipRule",
    "clipPathUnits",
    "colorInterpolation",
    "colorInterpolationFilters",
    "colorProfile",
    "colorRendering",
    "cursor",
    "cx",
    "cy",
    "d",
    "decelerate",
    "descent",
    "diffuseConstant",
    "direction",
    "display",
    "divisor",
    "dominantBaseline",
    "dur",
    "dx",
    "dy",
    "edgeMode",
    "elevation",
    "enableBackground",
    "end",
    "exponent",
    "externalResourcesRequired",
    "fill",
    "fillOpacity",
    "fillRule",
    "filter",
    "filterRes",
    "filterUnits",
    "floodColor",
    "floodOpacity",
    "focusable",
    "fontFamily",
    "fontSize",
    "fontSizeAdjust",
    "fontStretch",
    "fontStyle",
    "fontVariant",
    "fontWeight",
    "format",
    "from",
    "fr",
    "fx",
    "fy",
    "g1",
    "g2",
    "glyphName",
    "glyphOrientationHorizontal",
    "glyphOrientationVertical",
    "gradientTransform",
    "gradientUnits",
    "hanging",
    "horizAdvX",
    "horizOriginX",
    "ideographic",
    "in",
    "in2",
    "intercept",
    "k",
    "k1",
    "k2",
    "k3",
    "k4",
    "kernelMatrix",
    "kernelUnitLength",
    "keyPoints",
    "keySplines",
    "keyTimes",
    "lengthAdjust",
    "letterSpacing",
    "lightingColor",
    "limitingConeAngle",
    "local",
    "markerEnd",
    "markerHeight",
    "markerMid",
    "markerStart",
    "markerUnits",
    "markerWidth",
    "mask",
    "maskContentUnits",
    "maskUnits",
    "mathematical",
    "mode",
    "numOctaves",
    "offset",
    "opacity",
    "operator",
    "order",
    "orient",
    "orientation",
    "origin",
    "overflow",
    "overlinePosition",
    "overlineThickness",
    "paintOrder",
    "panose1",
    "pathLength",
    "patternContentUnits",
    "patternTransform",
    "patternUnits",
    "ping",
    "points",
    "pointsAtX",
    "pointsAtY",
    "pointsAtZ",
    "preserveAlpha",
    "preserveAspectRatio",
    "primitiveUnits",
    "r",
    "radius",
    "repeatCount",
    "repeatDur",
    "requiredExtensions",
    "requiredFeatures",
    "restart",
    "result",
    "rotate",
    "rx",
    "ry",
    "scale",
    "seed",
    "shapeRendering",
    "side",
    "slope",
    "spacing",
    "specularConstant",
    "specularExponent",
    "speed",
    "spreadMethod",
    "startOffset",
    "stdDeviation",
    "stemh",
    "stemv",
    "stitchTiles",
    "stopColor",
    "stopOpacity",
    "strikethroughPosition",
    "strikethroughThickness",
    "string",
    "stroke",
    "strokeDasharray",
    "strokeDashoffset",
    "strokeLinecap",
    "strokeLinejoin",
    "strokeMiterlimit",
    "strokeOpacity",
    "strokeWidth",
    "surfaceScale",
    "systemLanguage",
    "tableValues",
    "targetX",
    "targetY",
    "textAnchor",
    "textDecoration",
    "textLength",
    "textRendering",
    "to",
    "transform",
    "transformOrigin",
    "u1",
    "u2",
    "underlinePosition",
    "underlineThickness",
    "unicode",
    "unicodeBidi",
    "unicodeRange",
    "unitsPerEm",
    "vAlphabetic",
    "vHanging",
    "vIdeographic",
    "vMathematical",
    "values",
    "vectorEffect",
    "version",
    "vertAdvY",
    "vertOriginX",
    "vertOriginY",
    "viewBox",
    "viewTarget",
    "visibility",
    "wordSpacing",
    "writingMode",
    "x",
    "x1",
    "x2",
    "xChannelSelector",
    "xHeight",
    "xlinkActuate",
    "xlinkArcrole",
    "xlinkHref",
    "xlinkRole",
    "xlinkShow",
    "xlinkTitle",
    "xlinkType",
    "xmlBase",
    "xmlLang",
    "xmlSpace",
    "xmlns",
    "xmlnsXlink",
    "y",
    "y1",
    "y2",
    "yChannelSelector",
    "zoomAndPan",
];

/// Tag-scoped DOM attributes (`S6747`): names that are only valid on the
/// listed intrinsic tags, mirroring `ATTRIBUTE_TAGS_MAP` in the reference
/// `react/no-unknown-property` implementation (eslint-plugin-react 7.37.5).
/// A mapped name on any other tag is reportable; an unmapped name falls back
/// to `REACT_DOM_ATTRIBUTES` and the `data-*`/`aria-*`/`on*` conventions.
pub(crate) const TAG_SCOPED_ATTRIBUTES: &[(&str, &[&str])] = &[
    ("abbr", &["th", "td"]),
    ("charset", &["meta"]),
    ("checked", &["input"]),
    // `image` is required for SVG support, all other tags are HTML.
    (
        "crossOrigin",
        &["script", "img", "video", "audio", "link", "image"],
    ),
    ("displaystyle", &["math"]),
    ("download", &["a", "area"]),
    // https://developer.mozilla.org/en-US/docs/Web/SVG/Attribute/fill
    (
        "fill",
        &[
            "altGlyph",
            "circle",
            "ellipse",
            "g",
            "line",
            "marker",
            "mask",
            "path",
            "polygon",
            "polyline",
            "rect",
            "svg",
            "symbol",
            "text",
            "textPath",
            "tref",
            "tspan",
            "use",
            "animate",
            "animateColor",
            "animateMotion",
            "animateTransform",
            "set",
        ],
    ),
    ("focusable", &["svg"]),
    ("imageSizes", &["link"]),
    ("imageSrcSet", &["link"]),
    ("property", &["meta"]),
    ("viewBox", &["marker", "pattern", "svg", "symbol", "view"]),
    ("as", &["link"]),
    (
        "align",
        &[
            "applet", "caption", "col", "colgroup", "hr", "iframe", "img", "table", "tbody", "td",
            "tfoot", "th", "thead", "tr",
        ],
    ),
    (
        "valign",
        &[
            "tr", "td", "th", "thead", "tbody", "tfoot", "colgroup", "col",
        ],
    ),
    ("noModule", &["script"]),
    // Media events allowed only on audio and video tags.
    ("onAbort", &["audio", "video"]),
    ("onCancel", &["dialog"]),
    ("onCanPlay", &["audio", "video"]),
    ("onCanPlayThrough", &["audio", "video"]),
    ("onClose", &["dialog"]),
    ("onDurationChange", &["audio", "video"]),
    ("onEmptied", &["audio", "video"]),
    ("onEncrypted", &["audio", "video"]),
    ("onEnded", &["audio", "video"]),
    (
        "onError",
        &[
            "audio", "video", "img", "link", "source", "script", "picture", "iframe",
        ],
    ),
    (
        "onLoad",
        &[
            "script", "img", "link", "picture", "iframe", "object", "source",
        ],
    ),
    ("onLoadedData", &["audio", "video"]),
    ("onLoadedMetadata", &["audio", "video"]),
    ("onLoadStart", &["audio", "video"]),
    ("onPause", &["audio", "video"]),
    ("onPlay", &["audio", "video"]),
    ("onPlaying", &["audio", "video"]),
    ("onProgress", &["audio", "video"]),
    ("onRateChange", &["audio", "video"]),
    ("onResize", &["audio", "video"]),
    ("onSeeked", &["audio", "video"]),
    ("onSeeking", &["audio", "video"]),
    ("onStalled", &["audio", "video"]),
    ("onSuspend", &["audio", "video"]),
    ("onTimeUpdate", &["audio", "video"]),
    ("onVolumeChange", &["audio", "video"]),
    ("onWaiting", &["audio", "video"]),
    ("autoPictureInPicture", &["video"]),
    ("controls", &["audio", "video"]),
    ("controlsList", &["audio", "video"]),
    ("disablePictureInPicture", &["video"]),
    ("disableRemotePlayback", &["audio", "video"]),
    ("loop", &["audio", "video"]),
    ("muted", &["audio", "video"]),
    ("playsInline", &["video"]),
    ("allowFullScreen", &["iframe", "video"]),
    ("webkitAllowFullScreen", &["iframe", "video"]),
    ("mozAllowFullScreen", &["iframe", "video"]),
    ("poster", &["video"]),
    ("preload", &["audio", "video"]),
    ("scrolling", &["iframe"]),
    ("returnValue", &["dialog"]),
    ("webkitDirectory", &["input"]),
    ("shadowrootmode", &["template"]),
    ("shadowrootclonable", &["template"]),
    ("shadowrootdelegatesfocus", &["template"]),
    ("shadowrootserializable", &["template"]),
    ("transform-origin", &["rect"]),
];

/// Whether a function-like expression body returns JSX (`strict`) or
/// JSX-or-null somewhere.
pub(crate) fn expression_returns_jsx(expression: &Expression<'_>, strict: bool) -> Option<bool> {
    match expression {
        Expression::ArrowFunctionExpression(arrow) => match &arrow.body {
            ArrowFunctionBody::FunctionBody(body) => Some(body_returns_jsx_mode(body, strict)),
            arrow_body => {
                let mut scanner = JsxOrNullScanner {
                    strict,
                    ..JsxOrNullScanner::default()
                };
                if let Some(expression) = arrow_body.as_expression() {
                    scanner.visit_expression(expression);
                }
                Some(scanner.found)
            }
        },
        Expression::FunctionExpression(function) => function
            .body
            .as_ref()
            .map(|body| body_returns_jsx_mode(body, strict)),
        _ => None,
    }
}
